//! CASM → C source code generator.
//!
//! Translates a `casm::Program` into a self-contained `.c` translation unit.
//! The generated code `#include`s the inline runtime header (no external deps),
//! declares one C function per CASM function, and emits a `crush_main()` entry
//! point that calls the CASM `main` function.
//!
//! ## Emission model
//!
//! CASM is a stack machine; C is register-based.  The emitter implements a
//! **virtual stack** of fresh `_s<N>` temporaries, one per push.  This is
//! identical in spirit to `crush-ptx`'s virtual register approach but targets C
//! scalars instead of PTX registers.
//!
//! ### Scalar fast path (Pathway 1 + 2)
//!
//! When type inference determines that a local is *always* `int64_t` or
//! `double`, the emitter declares a raw C scalar and elides the NaN-boxing
//! overhead entirely.  All arithmetic on those slots uses native C operators
//! (`+`, `-`, `*`, `/`) instead of the `cv_add` helpers, letting the C
//! compiler emit optimal machine code.
//!
//! ### Boxed slow path
//!
//! When inference returns `CrushValue` (dynamic / unknown), the emitter uses
//! the helpers from `crush_rt.h`.

use std::collections::HashMap;
use std::fmt::Write as FmtWrite;

use crate::infer::{InferredType, TypeMap};
use crate::rt_header::RT_HEADER;

/// Options for the AOT compiler.
#[derive(Debug, Default, Clone)]
pub struct AotcOpts {
    /// Target architecture hint (passed as comment, used by the invoker).
    pub target: Option<String>,
    /// Emit AVX2 SIMD for array dot-product loops (Pathway 3, requires `-mavx2`).
    pub simd: bool,
    /// Optimization level to pass to `cc` (0..=3).
    pub opt_level: u8,
}

/// AOT compiler: translates a `casm::Program` to a C string.
pub struct AotcCompiler {
    pub opts: AotcOpts,
}

impl AotcCompiler {
    pub fn new(opts: AotcOpts) -> Self {
        Self { opts }
    }

    /// Compile a CASM program to a C source string.
    pub fn compile(&self, program: &casm::Program) -> anyhow::Result<String> {
        let mut out = String::with_capacity(8192);

        // Emit header
        writeln!(out, "/* Generated by crush-aotc — do not edit */")?;
        if let Some(ref tgt) = self.opts.target {
            writeln!(out, "/* target: {} */", tgt)?;
        }
        if self.opts.simd {
            writeln!(out, "#include <immintrin.h> /* AVX2 SIMD */")?;
        }
        out.push_str(RT_HEADER);
        writeln!(out)?;

        // Forward-declare all functions
        for (name, func) in &program.functions {
            let c_name = mangle(name);
            let params = if func.params.is_empty() {
                "void".to_string()
            } else {
                func.params.iter()
                    .map(|p| format!("CrushValue _p_{}", mangle_local(p)))
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            writeln!(out, "static CrushValue {}({});", c_name, params)?;
        }
        writeln!(out)?;

        // Emit each function
        for (name, func) in &program.functions {
            self.emit_function(name, func, &mut out)?;
        }

        // Emit crush_main entry point
        writeln!(out, "\nint main(void) {{")?;
        writeln!(out, "    crush_main();")?;
        writeln!(out, "    return 0;")?;
        writeln!(out, "}}")?;

        Ok(out)
    }

    fn emit_function(
        &self,
        name: &str,
        func: &casm::Function,
        out: &mut String,
    ) -> anyhow::Result<()> {
        let c_name = mangle(name);
        let tm = TypeMap::infer(&func.body);

        let params = if func.params.is_empty() {
            "void".to_string()
        } else {
            func.params.iter()
                .map(|p| format!("CrushValue _p_{}", mangle_local(p)))
                .collect::<Vec<_>>()
                .join(", ")
        };
        writeln!(out, "static CrushValue {}({}) {{", c_name, params)?;

        // Unbox parameters into locals with their inferred types
        for param in &func.params {
            let inferred = tm.locals.get(param).cloned().unwrap_or(InferredType::Dynamic);
            let name = mangle_local(param);
            match inferred {
                InferredType::Int => writeln!(out, "    int64_t {} = cv_as_int(_p_{});", name, name)?,
                InferredType::Float => writeln!(out, "    double {} = cv_as_float(_p_{});", name, name)?,
                InferredType::Dynamic => writeln!(out, "    CrushValue {} = _p_{};", name, name)?,
            }
        }

        // Declare remaining locals with inferred types
        for (local, inferred) in &tm.locals {
            if func.params.contains(local) {
                continue;
            }
            let cty = match inferred {
                InferredType::Int   => "int64_t",
                InferredType::Float => "double",
                InferredType::Dynamic => "CrushValue",
            };
            writeln!(out, "    {} {} = 0;", cty, mangle_local(local))?;
        }

        // Virtual stack of temporary names
        let mut stack: Vec<(String, InferredType)> = Vec::new();
        let mut tmp_count = 0usize;
        let mut label_count = 0usize;
        // Map CASM instruction index → C label
        let mut labels: HashMap<usize, String> = HashMap::new();

        // Pre-scan for jump targets so we know which indices need labels
        for instr in &func.body {
            if let Some(target) = instr.args.get("target").and_then(|v| v.as_u64()) {
                labels.entry(target as usize).or_insert_with(|| {
                    let l = format!("_L{}", label_count);
                    label_count += 1;
                    l
                });
            }
        }

        let new_tmp = |count: &mut usize, ty: InferredType| -> (String, InferredType) {
            let name = format!("_s{}", *count);
            *count += 1;
            (name, ty)
        };

        for (i, instr) in func.body.iter().enumerate() {
            // Emit label if this is a jump target
            if let Some(lbl) = labels.get(&i) {
                writeln!(out, "  {}:;", lbl)?;
            }

            match instr.op.as_str() {
                // ── Stack literals ──────────────────────────────────────
                "push_int" => {
                    let v = instr.args.get("value").and_then(|v| v.as_i64()).unwrap_or(0);
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Int);
                    writeln!(out, "    int64_t {} = {}LL;", t, v)?;
                    stack.push((t, ty));
                }
                "push_float" => {
                    let v = instr.args.get("value").and_then(|v| v.as_f64()).unwrap_or(0.0);
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Float);
                    writeln!(out, "    double {} = {};", t, c_float_literal(v))?;
                    stack.push((t, ty));
                }
                "push_bool" => {
                    let v = instr.args.get("value").and_then(|v| v.as_bool()).unwrap_or(false);
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    writeln!(out, "    CrushValue {} = {};", t, if v { "CV_TRUE" } else { "CV_FALSE" })?;
                    stack.push((t, ty));
                }
                "push_null" => {
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    writeln!(out, "    CrushValue {} = CV_NULL;", t)?;
                    stack.push((t, ty));
                }
                "push_str" => {
                    let v = instr.args.get("value").and_then(|v| v.as_str()).unwrap_or("");
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    // Strings are NaN-boxed references so cv_is_float/cv_is_string work.
                    writeln!(out, "    CrushValue {} = cv_string(\"{}\");", t, c_escape(v))?;
                    stack.push((t, ty));
                }
                "pop" => { stack.pop(); }
                "dup" => {
                    if let Some(top) = stack.last().cloned() {
                        stack.push(top);
                    }
                }

                // ── Memory ──────────────────────────────────────────────
                "store" => {
                    let name = instr.args.get("name").and_then(|v| v.as_str()).unwrap_or("_");
                    let src = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    // CASM functions begin with stores that bind arguments to parameters.
                    // Arguments are already passed as C function parameters and unboxed into
                    // locals, so these initial stores are no-ops.
                    // NOTE: This makes parameters immutable in the generated C. If Crush
                    // ever needs mutable parameters, skip only the prologue stores or change
                    // the CASM convention so parameters are not initialized via store.
                    if func.params.iter().any(|p| p == name) {
                        continue;
                    }
                    let lname = mangle_local(name);
                    let lty = tm.ctype_for(name);
                    match (lty, &src.1) {
                        ("int64_t", InferredType::Int) => {
                            writeln!(out, "    {} = {};", lname, src.0)?;
                        }
                        ("double", InferredType::Float) => {
                            writeln!(out, "    {} = {};", lname, src.0)?;
                        }
                        ("int64_t", _) => {
                            writeln!(out, "    {} = cv_as_int({});", lname, src.0)?;
                        }
                        ("double", _) => {
                            writeln!(out, "    {} = cv_as_float({});", lname, src.0)?;
                        }
                        _ => {
                            // Dynamic local; coerce src if it's a scalar
                            let rhs = match src.1 {
                                InferredType::Int   => format!("cv_int({})", src.0),
                                InferredType::Float => format!("cv_float({})", src.0),
                                _ => src.0,
                            };
                            writeln!(out, "    {} = {};", lname, rhs)?;
                        }
                    }
                }
                "load" => {
                    let name = instr.args.get("name").and_then(|v| v.as_str()).unwrap_or("_");
                    let lname = mangle_local(name);
                    let inferred = tm.locals.get(name).cloned().unwrap_or(InferredType::Dynamic);
                    stack.push((lname, inferred));
                }

                // ── Arithmetic ──────────────────────────────────────────
                "add" | "sub" | "mul" | "div" | "mod" => {
                    let b = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let a = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let op = instr.op.as_str();
                    let (t, ty, code) = scalar_arith(op, &a, &b, &mut tmp_count);
                    writeln!(out, "    {}", code)?;
                    stack.push((t, ty));
                }
                "neg" => {
                    let a = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let (t, ty) = new_tmp(&mut tmp_count, a.1.clone());
                    let code = match &a.1 {
                        InferredType::Int   => format!("int64_t {} = -{};", t, a.0),
                        InferredType::Float => format!("double {} = -{};", t, a.0),
                        _ => format!("CrushValue {} = cv_neg({});", t, a.0),
                    };
                    writeln!(out, "    {}", code)?;
                    stack.push((t, ty));
                }

                // ── Comparison ──────────────────────────────────────────
                "eq" | "ne" | "lt" | "gt" | "le" | "ge" => {
                    let b = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let a = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let (cmp_macro, c_op) = match instr.op.as_str() {
                        "eq" => ("CV_CMP_EQ", "=="),
                        "ne" => ("CV_CMP_NE", "!="),
                        "lt" => ("CV_CMP_LT", "<"),
                        "gt" => ("CV_CMP_GT", ">"),
                        "le" => ("CV_CMP_LE", "<="),
                        "ge" => ("CV_CMP_GE", ">="),
                        _ => unreachable!()
                    };
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    let code = match (&a.1, &b.1) {
                        (InferredType::Int, InferredType::Int) =>
                            format!("CrushValue {} = ({} {} {}) ? CV_TRUE : CV_FALSE;", t, a.0, c_op, b.0),
                        (InferredType::Float, InferredType::Float) =>
                            format!("CrushValue {} = ({} {} {}) ? CV_TRUE : CV_FALSE;", t, a.0, c_op, b.0),
                        _ =>
                            format!("CrushValue {} = {}({}, {});", t, cmp_macro, a.0, b.0),
                    };
                    writeln!(out, "    {}", code)?;
                    stack.push((t, ty));
                }

                // ── Logical ─────────────────────────────────────────────
                "and" => {
                    let b = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let a = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    writeln!(out, "    CrushValue {} = (cv_truthy({}) && cv_truthy({})) ? CV_TRUE : CV_FALSE;", t, a.0, b.0)?;
                    stack.push((t, ty));
                }
                "or" => {
                    let b = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let a = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    writeln!(out, "    CrushValue {} = (cv_truthy({}) || cv_truthy({})) ? CV_TRUE : CV_FALSE;", t, a.0, b.0)?;
                    stack.push((t, ty));
                }
                "not" => {
                    let a = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    writeln!(out, "    CrushValue {} = cv_truthy({}) ? CV_FALSE : CV_TRUE;", t, a.0)?;
                    stack.push((t, ty));
                }

                // ── Control flow ────────────────────────────────────────
                "jmp" => {
                    let target = instr.args.get("target").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
                    let lbl = labels.entry(target).or_insert_with(|| {
                        let l = format!("_L{}", label_count);
                        label_count += 1;
                        l
                    }).clone();
                    writeln!(out, "    goto {};", lbl)?;
                }
                "jmp_if" => {
                    let target = instr.args.get("target").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
                    let cond = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let lbl = labels.entry(target).or_insert_with(|| {
                        let l = format!("_L{}", label_count);
                        label_count += 1;
                        l
                    }).clone();
                    writeln!(out, "    if (cv_truthy({})) goto {};", cond.0, lbl)?;
                }
                "jmp_if_not" => {
                    let target = instr.args.get("target").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
                    let cond = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let lbl = labels.entry(target).or_insert_with(|| {
                        let l = format!("_L{}", label_count);
                        label_count += 1;
                        l
                    }).clone();
                    let cond_expr = match cond.1 {
                        InferredType::Int   => format!("{} == 0", cond.0),
                        InferredType::Float => format!("{} == 0.0", cond.0),
                        _ => format!("!cv_truthy({})", cond.0),
                    };
                    writeln!(out, "    if ({}) goto {};", cond_expr, lbl)?;
                }
                "ret" => {
                    let val = stack.pop().unwrap_or(("CV_NULL".into(), InferredType::Dynamic));
                    let ret_expr = match val.1 {
                        InferredType::Int   => format!("cv_int({})", val.0),
                        InferredType::Float => format!("cv_float({})", val.0),
                        _ => val.0,
                    };
                    writeln!(out, "    return {};", ret_expr)?;
                }
                "call" => {
                    let func_name = instr.args.get("function").and_then(|v| v.as_str()).unwrap_or("");
                    let argc = instr.args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
                    // Pop args: the frontend pushes user-function call args right-to-left
                    // (first arg ends up on top of stack), so pop gives [first, second, ...]
                    // in the correct parameter order — no reverse needed.
                    let args: Vec<_> = (0..argc).filter_map(|_| stack.pop()).collect();
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    // Box scalar args so every function receives a CrushValue regardless of
                    // the caller's inferred type. The callee unboxes to its own inferred types.
                    let boxed_args: Vec<String> = args.iter().map(|(a, ty)| match ty {
                        InferredType::Int   => format!("cv_int({})", a),
                        InferredType::Float => format!("cv_float({})", a),
                        _ => a.clone(),
                    }).collect();
                    writeln!(out, "    CrushValue {} = {}({});", t, mangle(func_name),
                        boxed_args.join(", "))?;
                    stack.push((t, ty));
                }

                // ── Capability calls ────────────────────────────────────
                "cap_call" => {
                    let cap_name = instr.args.get("name").and_then(|v| v.as_str()).unwrap_or("");
                    let argc = instr.args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
                    let mut args: Vec<_> = (0..argc).filter_map(|_| stack.pop()).collect();
                    args.reverse();
                    // Box int/float args for capabilities
                    let boxed_args: Vec<String> = args.iter().map(|(a, ty)| match ty {
                        InferredType::Int   => format!("cv_int({})", a),
                        InferredType::Float => format!("cv_float({})", a),
                        _ => a.clone(),
                    }).collect();
                    match cap_name {
                        "io.print" => {
                            let arg = boxed_args.first().map(|s| s.as_str()).unwrap_or("CV_NULL");
                            writeln!(out, "    cap_io_print({});", arg)?;
                            let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                            writeln!(out, "    CrushValue {} = CV_NULL;", t)?;
                            stack.push((t, ty));
                        }
                        "math.sqrt"  => emit_math_cap(out, "cap_math_sqrt",  &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.pow"   => emit_math_cap(out, "cap_math_pow",   &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.abs"   => emit_math_cap(out, "cap_math_abs",   &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.floor" => emit_math_cap(out, "cap_math_floor", &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.ceil"  => emit_math_cap(out, "cap_math_ceil",  &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.round" => emit_math_cap(out, "cap_math_round", &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.min"   => emit_math_cap(out, "cap_math_min",   &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.max"   => emit_math_cap(out, "cap_math_max",   &boxed_args, &mut stack, &mut tmp_count)?,
                        "math.pi"    => emit_math_cap(out, "cap_math_pi",    &boxed_args, &mut stack, &mut tmp_count)?,
                        _ => {
                            // Unknown capability — emit comment + NULL result
                            writeln!(out, "    /* unimplemented cap: {} */", cap_name)?;
                            let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                            writeln!(out, "    CrushValue {} = CV_NULL;", t)?;
                            stack.push((t, ty));
                        }
                    }
                }

                // ── Array ops (Pathway 3 hook) ──────────────────────────
                "new_array" => {
                    // Simplified: emit a stub (full array support needs heap)
                    let (t, ty) = new_tmp(&mut tmp_count, InferredType::Dynamic);
                    writeln!(out, "    CrushValue {} = CV_NULL; /* new_array stub */", t)?;
                    stack.push((t, ty));
                }

                // ── Ignored / passthrough ───────────────────────────────
                "break" | "continue" => {
                    // Control flow within loops — emit as-is
                    writeln!(out, "    /* {} */", instr.op)?;
                }
                _ => {
                    writeln!(out, "    /* unhandled op: {} */", instr.op)?;
                }
            }
        }

        // Default return
        writeln!(out, "    return CV_NULL;")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
        Ok(())
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

fn mangle(name: &str) -> String {
    if name == "main" {
        "crush_main".to_string()
    } else {
        name.replace('.', "__").replace('-', "_")
    }
}

fn mangle_local(name: &str) -> String {
    format!("_v_{}", name.replace('.', "__").replace('-', "_"))
}

fn c_float_literal(v: f64) -> String {
    if v.is_nan() { "nan(\"\")".to_string() }
    else if v.is_infinite() { if v > 0.0 { "INFINITY".to_string() } else { "-INFINITY".to_string() } }
    else { format!("{:.17e}", v) }
}

fn c_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r")
}

fn scalar_arith(
    op: &str,
    a: &(String, InferredType),
    b: &(String, InferredType),
    count: &mut usize,
) -> (String, InferredType, String) {
    let t = format!("_s{}", *count);
    *count += 1;
    let c_op = match op { "add"=>"+", "sub"=>"-", "mul"=>"*", "div"=>"/", "mod"=>"%", _=>"+" };
    match (&a.1, &b.1) {
        (InferredType::Int, InferredType::Int) => {
            let code = match op {
                "add" => format!("int64_t {t}; if (__builtin_add_overflow({a}, {b}, &{t})) crush_arith_error(\"arithmetic overflow\");", t=t, a=a.0, b=b.0),
                "sub" => format!("int64_t {t}; if (__builtin_sub_overflow({a}, {b}, &{t})) crush_arith_error(\"arithmetic overflow\");", t=t, a=a.0, b=b.0),
                "mul" => format!("int64_t {t}; if (__builtin_mul_overflow({a}, {b}, &{t})) crush_arith_error(\"arithmetic overflow\");", t=t, a=a.0, b=b.0),
                "div" => format!("int64_t {t}; if ({b} == 0) crush_div_zero(); {t} = {a} / {b};", t=t, a=a.0, b=b.0),
                "mod" => format!("int64_t {t}; if ({b} == 0) crush_div_zero(); {t} = {a} % {b};", t=t, a=a.0, b=b.0),
                _ => format!("int64_t {} = {} {} {};", t, a.0, c_op, b.0),
            };
            (t, InferredType::Int, code)
        }
        (InferredType::Float, InferredType::Float) => {
            let code = match op {
                "div" => format!("double {t}; if ({b} == 0.0) crush_div_zero(); {t} = {a} / {b};", t=t, a=a.0, b=b.0),
                "mod" => format!("double {t}; if ({b} == 0.0) crush_div_zero(); {t} = fmod({a}, {b});", t=t, a=a.0, b=b.0),
                _ => format!("double {} = {} {} {};", t, a.0, c_op, b.0),
            };
            (t, InferredType::Float, code)
        }
        _ => {
            let helper = match op { "add"=>"cv_add", "sub"=>"cv_sub", "mul"=>"cv_mul", "div"=>"cv_div", "mod"=>"cv_mod", _=>"cv_add" };
            // coerce scalars to CrushValue if needed
            let av = match a.1 { InferredType::Int => format!("cv_int({})", a.0), InferredType::Float => format!("cv_float({})", a.0), _ => a.0.clone() };
            let bv = match b.1 { InferredType::Int => format!("cv_int({})", b.0), InferredType::Float => format!("cv_float({})", b.0), _ => b.0.clone() };
            let code = format!("CrushValue {} = {}({}, {});", t, helper, av, bv);
            (t, InferredType::Dynamic, code)
        }
    }
}

fn emit_math_cap(
    out: &mut String,
    func: &str,
    args: &[String],
    stack: &mut Vec<(String, InferredType)>,
    count: &mut usize,
) -> anyhow::Result<()> {
    let t = format!("_s{}", *count);
    *count += 1;
    let args_str = args.join(", ");
    writeln!(out, "    CrushValue {} = {}({});", t, func, args_str)?;
    // The result is already a boxed CrushValue; mark it Dynamic so callers
    // don't try to re-box it with cv_float/cv_int.
    stack.push((t, InferredType::Dynamic));
    Ok(())
}

/// Compile the generated C string to a `.so` via `cc`, returning the path to
/// the compiled library.  Requires a C compiler on PATH.
pub fn compile_to_so(c_source: &str, opts: &AotcOpts) -> anyhow::Result<std::path::PathBuf> {
    use std::io::Write;

    let dir = tempfile::tempdir()?;
    let src_path = dir.path().join("crush_aotc.c");
    let so_path  = dir.path().join("crush_aotc.so");

    std::fs::write(&src_path, c_source)?;

    let opt = format!("-O{}", opts.opt_level);
    let mut cmd = std::process::Command::new("cc");
    cmd.arg("-shared").arg("-fPIC").arg(&opt)
       .arg("-lm")
       .arg("-o").arg(&so_path)
       .arg(&src_path);
    if opts.simd { cmd.arg("-mavx2"); }

    let status = cmd.status()?;
    if !status.success() {
        anyhow::bail!("cc failed with exit code: {:?}", status.code());
    }
    // Copy out of temp dir before it drops
    let out_path = std::env::temp_dir().join("crush_aotc_latest.so");
    std::fs::copy(&so_path, &out_path)?;
    Ok(out_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_emit_simple_add() {
        let source = "fn add(a, b) { return a + b; }";
        let program = crush_frontend::compile_crush_source(source).expect("compile");
        let c = AotcCompiler::new(AotcOpts::default())
            .compile(&program).expect("emit C");
        println!("=== Generated C ===\n{}", c);
        assert!(c.contains("crush_main"));
        // Should have an add function
        assert!(c.contains("add(void)") || c.contains("_s"));
    }

    #[test]
    fn test_emit_int_fast_path() {
        let source = r#"
            fn loop_sum(n) {
                let sum = 0
                let i = 0
                while i < n {
                    let sum = sum + i
                    let i = i + 1
                }
                return sum
            }
        "#;
        let program = crush_frontend::compile_crush_source(source).expect("compile");
        let c = AotcCompiler::new(AotcOpts::default())
            .compile(&program).expect("emit C");
        println!("=== Generated C (loop_sum) ===\n{}", c);
        // Fast path: sum and i should be int64_t scalars
        assert!(c.contains("int64_t"));
    }

    #[test]
    fn test_emit_math_caps() {
        let source = r#"
            fn math_demo() {
                let x = math.sqrt(16)
                let y = math.pow(2, 8)
                return x + y
            }
        "#;
        let program = crush_frontend::compile_crush_source(source).expect("compile");
        let c = AotcCompiler::new(AotcOpts::default())
            .compile(&program).expect("emit C");
        println!("=== Generated C (math) ===\n{}", c);
        assert!(c.contains("cap_math_sqrt"));
        assert!(c.contains("cap_math_pow"));
    }

    #[test]
    fn c_aot_io_print_emits_trailing_newline() {
        let source = r#"
            fn main() {
                print("hello")
            }
        "#;
        let program = crush_frontend::compile_crush_source(source).expect("compile");
        let c = AotcCompiler::new(AotcOpts::default())
            .compile(&program).expect("emit C");
        // The runtime header must contain the single source of truth for the newline.
        assert!(c.contains("crush_io_print_line"), "generated C runtime should contain crush_io_print_line helper");
        // The generated main must call the io.print capability.
        assert!(c.contains("cap_io_print"), "generated C should call cap_io_print");
    }

    #[test]
    fn c_aot_string_tagging_and_equality() {
        let source = r#"
            fn main() {
                let a = "hello"
                let b = "hello"
                let c = (a == b)
                print(c)
            }
        "#;
        let program = crush_frontend::compile_crush_source(source).expect("compile");
        let c = AotcCompiler::new(AotcOpts::default())
            .compile(&program).expect("emit C");
        // Strings must be emitted with the proper NaN-boxed reference tag.
        assert!(c.contains("cv_string(\"hello\")"), "generated C should tag string literals");
        // Equality must use the scheduler-matching helper.
        assert!(c.contains("CV_CMP_EQ"), "generated C should use CV_CMP_EQ for equality");
    }
}
