//! CPU kernel emitter for `crush-aotc`.
//!
//! A **CPU kernel** in crush is a function that operates over arrays of raw
//! scalars without the boxed `CrushValue` overhead.  It is the CPU analogue
//! of the PTX kernel emitted by `crush-ptx`.
//!
//! ## Calling convention
//!
//! ```c
//! void __crush_kernel_<name>(
//!     const double * __restrict__ in,
//!     double       * __restrict__ out,
//!     size_t n
//! );
//! ```
//!
//! The kernel body is emitted from a CASM function where:
//! - `load in`  → `in[tid]`  (via a synthetic loop index `size_t tid`)
//! - `store out` → `out[tid]`
//!
//! ## AVX2 fast path (Pathway 3)
//!
//! When `AotcOpts::simd` is true and the kernel body is a simple element-wise
//! operation (recognized by inspecting the CASM ops), the emitter generates an
//! AVX2 vectorised loop processing 4 `double`s per iteration.

use std::fmt::Write as FmtWrite;

use casm::Function;

use crate::codegen::AotcOpts;
use crate::infer::{InferredType, TypeMap};
use crate::rt_header::RT_HEADER;

/// Emit a CPU kernel C translation unit as a string.
///
/// The returned string is a complete `.c` file that can be compiled with:
/// ```sh
/// cc -O3 -march=native [-mavx2] -shared -fPIC -lm -o kernel.so kernel.c
/// ```
pub struct CpuKernelEmitter<'a> {
    pub opts: &'a AotcOpts,
}

impl<'a> CpuKernelEmitter<'a> {
    pub fn new(opts: &'a AotcOpts) -> Self {
        Self { opts }
    }

    /// Emit a complete `.c` file for the given kernel function.
    ///
    /// `name` is the kernel name (e.g. `"dot_product"` or `"q6k_dequant"`).
    /// `func` is the CASM function body to compile.
    pub fn emit_kernel(&self, name: &str, func: &Function) -> anyhow::Result<String> {
        let mut out = String::with_capacity(4096);
        writeln!(out, "/* crush CPU kernel: {} */", name)?;
        writeln!(out, "/* Generated by crush-aotc (crush-ptx CPU path) */\n")?;

        if self.opts.simd {
            writeln!(out, "#include <immintrin.h>")?;
        }
        out.push_str(RT_HEADER);
        writeln!(out)?;

        // Determine if this is a purely element-wise kernel (Pathway 3 shortcut)
        let is_elementwise = is_elementwise_kernel(func);

        if self.opts.simd && is_elementwise {
            self.emit_avx2_kernel(name, func, &mut out)?;
        } else {
            self.emit_scalar_kernel(name, func, &mut out)?;
        }

        Ok(out)
    }

    /// Emit a scalar (non-SIMD) kernel loop.
    fn emit_scalar_kernel(&self, name: &str, func: &Function, out: &mut String) -> anyhow::Result<()> {
        writeln!(out, "void __crush_kernel_{}(", name)?;
        writeln!(out, "    const double * __restrict__ in,")?;
        writeln!(out, "    double       * __restrict__ out,")?;
        writeln!(out, "    size_t n")?;
        writeln!(out, ") {{")?;
        writeln!(out, "    for (size_t tid = 0; tid < n; tid++) {{")?;
        writeln!(out, "        double _in  = in[tid];")?;

        // Emit body — map "load in" → _in, "store out" → out[tid]
        let tm = TypeMap::infer(&func.body);
        let mut stack: Vec<(String, InferredType)> = Vec::new();
        let mut tmp_count = 0usize;
        stack.push(("_in".to_string(), InferredType::Float)); // synthetic param

        for instr in &func.body {
            match instr.op.as_str() {
                "push_float" => {
                    let v = instr.args.get("value").and_then(|v| v.as_f64()).unwrap_or(0.0);
                    let t = format!("_s{}", tmp_count); tmp_count += 1;
                    writeln!(out, "        double {} = {:.17e};", t, v)?;
                    stack.push((t, InferredType::Float));
                }
                "push_int" => {
                    let v = instr.args.get("value").and_then(|v| v.as_i64()).unwrap_or(0);
                    let t = format!("_s{}", tmp_count); tmp_count += 1;
                    writeln!(out, "        double {} = (double){}LL;", t, v)?;
                    stack.push((t, InferredType::Float));
                }
                "load" => {
                    let n = instr.args.get("name").and_then(|v| v.as_str()).unwrap_or("");
                    if n == "in" || func.params.contains(&n.to_string()) {
                        stack.push(("_in".to_string(), InferredType::Float));
                    } else {
                        stack.push((format!("_v_{}", n), InferredType::Float));
                    }
                }
                "store" => {
                    let n = instr.args.get("name").and_then(|v| v.as_str()).unwrap_or("");
                    let src = stack.pop().unwrap_or(("0.0".to_string(), InferredType::Float));
                    if n == "out" {
                        writeln!(out, "        out[tid] = {};", src.0)?;
                    } else {
                        writeln!(out, "        double _v_{} = {};", n, src.0)?;
                        stack.push((format!("_v_{}", n), InferredType::Float));
                    }
                }
                "add" => binary_kernel_op(out, &mut stack, &mut tmp_count, "+")?,
                "sub" => binary_kernel_op(out, &mut stack, &mut tmp_count, "-")?,
                "mul" => binary_kernel_op(out, &mut stack, &mut tmp_count, "*")?,
                "div" => binary_kernel_op(out, &mut stack, &mut tmp_count, "/")?,
                "fma" => {
                    // 3-operand fma: a*b + c
                    let c = stack.pop().unwrap_or(("0.0".into(), InferredType::Float));
                    let b = stack.pop().unwrap_or(("0.0".into(), InferredType::Float));
                    let a = stack.pop().unwrap_or(("0.0".into(), InferredType::Float));
                    let t = format!("_s{}", tmp_count); tmp_count += 1;
                    writeln!(out, "        double {} = fma({}, {}, {});", t, a.0, b.0, c.0)?;
                    stack.push((t, InferredType::Float));
                }
                "ret" => {
                    // in kernel context, ret stores to out[tid]
                    let src = stack.pop().unwrap_or(("0.0".to_string(), InferredType::Float));
                    writeln!(out, "        out[tid] = {};", src.0)?;
                }
                _ => {
                    writeln!(out, "        /* unhandled: {} */", instr.op)?;
                }
            }
        }

        writeln!(out, "    }}")?;  // end for loop
        writeln!(out, "}}")?;      // end function
        Ok(())
    }

    /// Emit an AVX2-vectorised kernel (Pathway 3).
    ///
    /// Processes 4 doubles per iteration with `__m256d` intrinsics, then
    /// handles the tail with a scalar loop.
    fn emit_avx2_kernel(&self, name: &str, func: &Function, out: &mut String) -> anyhow::Result<()> {
        // Extract the scalar body first to understand what the kernel does,
        // then replicate with AVX2 operations.
        // For now we detect the shape by looking at what ops appear.
        let ops: Vec<&str> = func.body.iter().map(|i| i.op.as_str()).collect();

        // Determine the arithmetic op used
        let avx_op = if ops.contains(&"mul") && ops.contains(&"add") {
            // fma-style: a * scale + bias
            "avx2_fma"
        } else if ops.contains(&"add") {
            "avx2_add"
        } else if ops.contains(&"mul") {
            "avx2_mul"
        } else {
            "avx2_add" // fallback
        };

        // Get the constants from push_float instructions
        let consts: Vec<f64> = func.body.iter()
            .filter(|i| i.op == "push_float")
            .filter_map(|i| i.args.get("value").and_then(|v| v.as_f64()))
            .collect();

        writeln!(out, "void __crush_kernel_{}(", name)?;
        writeln!(out, "    const double * __restrict__ in,")?;
        writeln!(out, "    double       * __restrict__ out,")?;
        writeln!(out, "    size_t n")?;
        writeln!(out, ") {{")?;

        if avx_op == "avx2_fma" && consts.len() >= 2 {
            let scale = consts[0];
            let bias  = consts[1];
            writeln!(out, "    /* AVX2 path: out[i] = fma(in[i], {:.4e}, {:.4e}) */", scale, bias)?;
            writeln!(out, "    __m256d vscale = _mm256_set1_pd({:.17e});", scale)?;
            writeln!(out, "    __m256d vbias  = _mm256_set1_pd({:.17e});", bias)?;
            writeln!(out, "    size_t i = 0;")?;
            writeln!(out, "    for (; i + 4 <= n; i += 4) {{")?;
            writeln!(out, "        __m256d v = _mm256_loadu_pd(&in[i]);")?;
            writeln!(out, "        __m256d r = _mm256_fmadd_pd(v, vscale, vbias);")?;
            writeln!(out, "        _mm256_storeu_pd(&out[i], r);")?;
            writeln!(out, "    }}")?;
            writeln!(out, "    for (; i < n; i++) {{")?;
            writeln!(out, "        out[i] = fma(in[i], {:.17e}, {:.17e});", scale, bias)?;
            writeln!(out, "    }}")?;
        } else if avx_op == "avx2_mul" && !consts.is_empty() {
            let scale = consts[0];
            writeln!(out, "    /* AVX2 path: out[i] = in[i] * {:.4e} */", scale)?;
            writeln!(out, "    __m256d vscale = _mm256_set1_pd({:.17e});", scale)?;
            writeln!(out, "    size_t i = 0;")?;
            writeln!(out, "    for (; i + 4 <= n; i += 4) {{")?;
            writeln!(out, "        __m256d v = _mm256_loadu_pd(&in[i]);")?;
            writeln!(out, "        __m256d r = _mm256_mul_pd(v, vscale);")?;
            writeln!(out, "        _mm256_storeu_pd(&out[i], r);")?;
            writeln!(out, "    }}")?;
            writeln!(out, "    for (; i < n; i++) {{")?;
            writeln!(out, "        out[i] = in[i] * {:.17e};", scale)?;
            writeln!(out, "    }}")?;
        } else {
            // Generic scalar loop fallback
            writeln!(out, "    /* scalar fallback in AVX2 wrapper */")?;
            writeln!(out, "    for (size_t i = 0; i < n; i++) {{")?;
            writeln!(out, "        out[i] = in[i];")?;
            writeln!(out, "    }}")?;
        }

        writeln!(out, "}}")?;
        Ok(())
    }
}

/// Returns true if the kernel body is a simple element-wise op (no branches,
/// no loops, no capability calls) — amenable to AVX2 vectorization.
fn is_elementwise_kernel(func: &Function) -> bool {
    for instr in &func.body {
        match instr.op.as_str() {
            "push_float" | "push_int" | "load" | "store" | "add" | "sub"
            | "mul" | "div" | "fma" | "neg" | "ret" => {}
            _ => return false,
        }
    }
    true
}

fn binary_kernel_op(
    out: &mut String,
    stack: &mut Vec<(String, InferredType)>,
    count: &mut usize,
    op: &str,
) -> anyhow::Result<()> {
    let b = stack.pop().unwrap_or(("0.0".to_string(), InferredType::Float));
    let a = stack.pop().unwrap_or(("0.0".to_string(), InferredType::Float));
    let t = format!("_s{}", *count);
    *count += 1;
    writeln!(out, "        double {} = {} {} {};", t, a.0, op, b.0)?;
    stack.push((t, InferredType::Float));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_kernel(body_ops: Vec<(&str, serde_json::Value)>) -> Function {
        Function {
            params: vec!["in".to_string()],
            locals: vec![],
            body: body_ops.into_iter().map(|(op, args)| casm::Instruction {
                op: op.into(),
                lang: None,
                meta: None,
                args,
            }).collect(),
        }
    }

    #[test]
    fn test_scalar_kernel_scale() {
        let func = make_kernel(vec![
            ("load",       serde_json::json!({"name": "in"})),
            ("push_float", serde_json::json!({"value": 0.5})),
            ("mul",        serde_json::json!({})),
            ("ret",        serde_json::json!({})),
        ]);
        let opts = AotcOpts { opt_level: 3, ..Default::default() };
        let emitter = CpuKernelEmitter::new(&opts);
        let c = emitter.emit_kernel("scale_half", &func).unwrap();
        println!("=== scale_half kernel ===\n{}", c);
        assert!(c.contains("__crush_kernel_scale_half"));
        assert!(c.contains("for (size_t tid"));
        assert!(c.contains("_in * _s"));
    }

    #[test]
    fn test_avx2_kernel_fma() {
        let func = make_kernel(vec![
            ("push_float", serde_json::json!({"value": 2.0})),   // scale
            ("push_float", serde_json::json!({"value": 0.5})),   // bias
            ("load",       serde_json::json!({"name": "in"})),
            ("mul",        serde_json::json!({})),
            ("add",        serde_json::json!({})),
            ("ret",        serde_json::json!({})),
        ]);
        let opts = AotcOpts { opt_level: 3, simd: true, ..Default::default() };
        let emitter = CpuKernelEmitter::new(&opts);
        let c = emitter.emit_kernel("scale_bias", &func).unwrap();
        println!("=== scale_bias AVX2 kernel ===\n{}", c);
        assert!(c.contains("__crush_kernel_scale_bias"));
        assert!(c.contains("_mm256_fmadd_pd") || c.contains("_mm256_mul_pd"));
    }

    #[test]
    fn test_dot_product_kernel() {
        // Simulate: dot(a, b) — element-wise multiply then reduce
        // We model the per-element kernel: out[i] = a[i] * b[i]
        let func = make_kernel(vec![
            ("load",  serde_json::json!({"name": "in"})),
            ("load",  serde_json::json!({"name": "in"})),
            ("mul",   serde_json::json!({})),
            ("ret",   serde_json::json!({})),
        ]);
        let opts = AotcOpts { opt_level: 3, simd: false, ..Default::default() };
        let emitter = CpuKernelEmitter::new(&opts);
        let c = emitter.emit_kernel("hadamard", &func).unwrap();
        println!("=== hadamard kernel ===\n{}", c);
        assert!(c.contains("__crush_kernel_hadamard"));
    }
}
