// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adaptation actions
 */
export type AdaptationAction = "OptimizeToolChain" | "ImproveErrorHandling" | "UpdateAgentSelection" | "ModifyExecutionStrategy" | "LearnNewPatterns";
