// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of adaptation requests
 */
export type AdaptationType = "Performance" | "Reliability" | "Usability" | "Compatibility" | "Learning";
