// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdaptationAction } from "./AdaptationAction";
import type { DelegationStrategy } from "./DelegationStrategy";
import type { ErrorHandling } from "./ErrorHandling";
import type { ExecutionStrategy } from "./ExecutionStrategy";
import type { Expression } from "./Expression";
import type { LearningStrategy } from "./LearningStrategy";
import type { LearningTarget } from "./LearningTarget";
import type { ToolCall } from "./ToolCall";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Extended AST with AI-native constructs
 */
export type AIExpression = { "ai_type": "Query", 
/**
 * Natural language query for AI processing
 */
query: string, 
/**
 * Expected result type
 */
result_type: string | null, 
/**
 * Context information
 */
context: { [key in string]: JsonValue }, } | { "ai_type": "ToolChain", 
/**
 * Chain of tool calls
 */
tools: Array<ToolCall>, 
/**
 * Execution strategy (sequential, parallel, conditional)
 */
strategy: ExecutionStrategy, 
/**
 * Error handling strategy
 */
error_handling: ErrorHandling, } | { "ai_type": "AgentDelegation", 
/**
 * Task description for delegation
 */
task: string, 
/**
 * Target agents (can be patterns or specific IDs)
 */
agents: Array<string>, 
/**
 * Delegation strategy
 */
delegation_strategy: DelegationStrategy, 
/**
 * Expected result format
 */
expected_format: string | null, } | { "ai_type": "LearningLoop", 
/**
 * What to learn from
 */
learning_target: LearningTarget, 
/**
 * Learning strategy
 */
strategy: LearningStrategy, 
/**
 * Adaptation actions
 */
adaptations: Array<AdaptationAction>, } | { "ai_type": "ContextAware", 
/**
 * The wrapped expression
 */
expression: Expression, 
/**
 * Context requirements
 */
requires_context: Array<string>, 
/**
 * Context providers
 */
provides_context: Array<string>, };
