// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollaborationPattern } from "./CollaborationPattern";
import type { ExecutionContext } from "./ExecutionContext";
import type { ParameterSchema } from "./ParameterSchema";

export type AIMetadata = { description: string, ai_tags: Array<string>, required_capabilities: Array<string>, execution_context: ExecutionContext, learning_objectives: Array<string>, collaboration_patterns: Array<CollaborationPattern>, inputs: Array<ParameterSchema>, outputs: Array<ParameterSchema>, complexity: number, };
