// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdaptationType } from "./AdaptationType";
import type { DiscoveryStrategy } from "./DiscoveryStrategy";
import type { KnowledgeType } from "./KnowledgeType";
import type { Priority } from "./Priority";
import type { RetentionPolicy } from "./RetentionPolicy";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * AI-Native Statement extensions
 */
export type AIStatement = { "ai_type": "GoalDeclaration", goal_id: string, description: string, success_criteria: Array<string>, priority: Priority, deadline: string | null, } | { "ai_type": "ProgressUpdate", goal_id: string, progress: number, status_message: string, metrics: { [key in string]: number }, } | { "ai_type": "KnowledgeSharing", knowledge_type: KnowledgeType, content: JsonValue, recipients: Array<string>, retention_policy: RetentionPolicy, } | { "ai_type": "CapabilityDiscovery", domain: string, requirements: Array<string>, discovery_strategy: DiscoveryStrategy, } | { "ai_type": "AdaptationRequest", adaptation_type: AdaptationType, reason: string, parameters: { [key in string]: JsonValue }, };
