// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backoff strategies for retries
 */
export type BackoffStrategy = { "type": "Fixed", delay_ms: bigint, } | { "type": "Exponential", base_delay_ms: bigint, max_delay_ms: bigint, } | { "type": "Linear", increment_ms: bigint, };
