// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Language-agnostic type system for CAST
 */
export type CastType = "Int" | "Float" | "String" | "Bool" | "Null" | { "Array": CastType } | { "Map": CastType } | { "Struct": string } | { "Lambda": { params: Array<CastType>, returns: CastType, } } | "Any" | { "TypeRef": string };
