// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lightweight changelog entry. Date is ISO 8601 string (YYYY-MM-DD).
 */
export type ChangelogEntry = { 
/**
 * ISO 8601 date. E.g. `"2026-06-17"`.
 */
date: string, 
/**
 * What changed and why — the commit message essence.
 */
summary: string, };
