// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollaborationPattern = { pattern_type: string, participants: Array<string>, communication_style: string, decision_making: string, };
