// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `@decision` node recording an architectural choice and its rationale.
 *
 * Agents query `codebase.decisions()` before touching an unusual design to
 * understand why it was chosen over alternatives — and whether conditions
 * that should trigger a re-evaluation are now met.
 */
export type DecisionNode = { 
/**
 * Machine-readable name. Kebab-case. E.g. `"use-rc-refcell-not-arc-mutex"`.
 */
name: string, 
/**
 * The option that was chosen.
 */
chose: string, 
/**
 * Alternatives that were considered and rejected.
 */
over?: Array<string>, 
/**
 * Why this option was chosen.
 */
because: string, 
/**
 * Conditions under which this decision should be revisited.
 */
revisit_if?: Array<string>, };
