// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delegation strategies for agent coordination
 */
export type DelegationStrategy = "FirstAvailable" | "CapabilityMatch" | "ParallelSplit" | "Hierarchical" | { "Consensus": { threshold: number, } } | "Broadcast" | "Best" | "RoundRobin";
