// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discovery strategies for capabilities
 */
export type DiscoveryStrategy = "Broadcast" | "Targeted" | "Hierarchical" | "LearningBased";
