// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DomMutationType = { "type": "SetTextContent" } | { "type": "SetAttribute" } | { "type": "RemoveAttribute" } | { "type": "SetStyle" } | { "type": "SetInnerHtml" } | { "type": "AppendHtml" } | { "type": "Remove" } | { "type": "AddClass" } | { "type": "RemoveClass" };
