// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCall } from "./ToolCall";

/**
 * Error handling strategies
 */
export type ErrorHandling = { "type": "FailFast" } | { "type": "ContinueOnError" } | { "type": "Retry", max_retries: number, retry_condition: string | null, } | { "type": "Fallback", fallback_tools: Array<ToolCall>, };
