// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Likelihood of an error variant being produced by a function.
 */
export type ErrorLikelihood = "likely" | "possible" | "rare";
