// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackoffStrategy } from "./BackoffStrategy";

/**
 * Execution strategies for tool chains
 */
export type ExecutionStrategy = { "type": "Sequential" } | { "type": "Parallel" } | { "type": "Conditional", conditions: Array<string>, } | { "type": "Retry", max_attempts: number, backoff_strategy: BackoffStrategy, };
