// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecutionContext = { environment: Array<string>, resources: Array<string>, permissions: Array<string>, dependencies: Array<string>, };
