// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceLoc } from "./SourceLoc";

/**
 * A site in the CAST where a sum type is matched exhaustively.
 *
 * Populated by the **compiler** when a type appears in `manifest.exhaustive_types`.
 * Not written by source authors directly. Stored in `Program.exhaustive_sites`.
 *
 * Agents query `codebase.exhaustive_sites("Value")` before adding a new variant
 * to know every match site that will need a new arm.
 */
export type ExhaustiveMatchSite = { 
/**
 * The type being matched on. E.g. `"Value"`.
 */
type_name: string, 
/**
 * The function containing this match expression.
 */
function_name: string, 
/**
 * Source location of the match expression.
 */
location: SourceLoc, 
/**
 * Variant arms present in this match.
 */
covered_arms: Array<string>, 
/**
 * Variant arms MISSING from this match (populated after type definition
 * is finalised; empty until then).
 */
missing_arms: Array<string>, 
/**
 * True when the match contains a wildcard arm (`_ => { ... }`).
 *
 * A wildcard silences the exhaustiveness check because it hides any number
 * of unhandled variants.  `check_exhaustiveness()` emits `E-EXH-001` here.
 */
has_wildcard: boolean, };
