// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalResourceType = "Http" | "Git" | "File" | "Database" | { "API": { format: string, } };
