// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeightedError } from "./WeightedError";

/**
 * Function-level semantic annotations.
 *
 * Attached to `Function.annotations`. All fields are optional — partial
 * annotation is valid. Agents use whichever fields are present.
 *
 * Source syntax (planned):
 * ```crush
 * fn execute_one(thread, ...)
 *     @errors  [StackUnderflow, StepQuota, BadJump]
 *     @reads   [thread.ip, thread.stack]
 *     @writes  [thread.ip, thread.stack, thread.out_parts]
 *     @no-write [program]
 * ```
 */
export type FunctionAnnotations = { 
/**
 * Error variants this function may produce.
 * E.g. `["VmError::StackUnderflow", "VmError::StepQuota"]`.
 * Agents use this to know what error handling is required at call sites.
 */
errors: Array<string>, 
/**
 * State paths this function reads but does not own.
 * Helps agents reason about what must be valid before calling this function.
 */
reads: Array<string>, 
/**
 * State paths this function may mutate.
 * Agents check this before passing shared state to the function.
 */
writes: Array<string>, 
/**
 * State paths this function guarantees it does NOT write.
 * Stronger contract than absence from `writes` — explicitly checked by
 * the compiler (planned) and trusted by agents reasoning about const-ness.
 */
does_not_write: Array<string>, 
/**
 * Error paths, code paths, or behavioral variants this test function covers.
 * Only meaningful when the function is a test (name starts with `test_`).
 * `codebase.uncovered_paths()` returns all error paths with no `@covers` test.
 *
 * E.g. `["VmError::StackUnderflow", "VmError::DivByZero"]`
 */
covers: Array<string>, 
/**
 * Invariant names (from the module manifest) this function relies on.
 * An agent changing this function should re-read the listed invariants.
 */
relies_on: Array<string>, 
/**
 * Complexity hint 0–100. Agents use this to decide whether to read
 * the full body or request a summary. 0 = trivial, 100 = extremely complex.
 */
complexity: number | null, 
/**
 * Probabilistic error annotations from `@errors { Variant: likely }` blocks.
 */
errors_weighted?: Array<WeightedError>, 
/**
 * State paths that this function invalidates after it returns.
 * Callers must not hold references to these paths across the call.
 */
invalidates?: Array<string>, 
/**
 * Functions that MUST be called before this one at every call site.
 * `E-MUT-001` is emitted when the ordering is violated.
 */
must_call_before?: Array<string>, 
/**
 * Functions that MUST be called after this one at every call site.
 * `E-MUT-002` is emitted when the ordering is violated.
 */
must_call_after?: Array<string>, };
