// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastType } from "./CastType";
import type { FunctionAnnotations } from "./FunctionAnnotations";
import type { Statement } from "./Statement";
import type { JsonValue } from "./serde_json/JsonValue";

export type Function = { params: Array<[string, CastType]>, body: Array<Statement>, meta: { [key in string]: JsonValue }, 
/**
 * Semantic annotations (@errors, @reads, @writes, @covers, @relies-on).
 * Absent when no annotations were written; all sub-fields are optional.
 */
annotations?: FunctionAnnotations | null, };
