// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalResourceType } from "./ExternalResourceType";

export type ImportStatement = { "type": "CrushModule", module_path: string, alias: string | null, selective: Array<string>, } | { "type": "PolyglotModule", language: string, module_path: string, alias: string | null, selective: Array<string>, } | { "type": "MCPImport", server_url: string, tools: Array<string>, alias: string | null, } | { "type": "Capability", capability_path: string, permissions: Array<string>, alias: string | null, } | { "type": "External", uri: string, resource_type: ExternalResourceType, alias: string | null, } | { "type": "SecureEnv", 
/**
 * Specific keys to import (empty = all keys)
 */
keys: Array<string>, 
/**
 * Alias for the imported secrets module
 */
alias: string | null, 
/**
 * Path to the secrets database (optional, uses default if not specified)
 */
db_path: string | null, };
