// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named, typed contract that must hold for the module to be correct.
 *
 * `@invariant "name" { description: "...", applies_to: [...], consequence: "..." }`
 */
export type Invariant = { 
/**
 * Machine-readable identifier. Kebab-case. E.g. `"rc-refcell-not-send"`.
 * Used as a stable key in the index and in `@relies-on` references.
 */
name: string, 
/**
 * Agent-readable description of what the invariant means.
 */
description: string, 
/**
 * Function or type names this invariant constrains. An agent modifying
 * any of these symbols should re-read the invariant first.
 */
applies_to: Array<string>, 
/**
 * What breaks if this invariant is violated. Helps agents understand
 * the consequence of a change without needing to trace the full call graph.
 */
consequence: string | null, 
/**
 * Optional source expression that can be evaluated to check this invariant.
 * Phase 2b will execute this; Phase 2a only stores it.
 */
check_source?: string | null, };
