// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of knowledge for sharing
 */
export type KnowledgeType = "Pattern" | "Solution" | "BestPractice" | "Warning" | "Insight";
