// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LearningSource = "ExecutionResults" | "UserFeedback" | "EnvironmentObservations" | { "PeerAgents": { agent_ids: Array<string>, } };
