// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pattern } from "./Pattern";
import type { Statement } from "./Statement";

export type MatchArm = { pattern: Pattern, body: Array<Statement>, };
