// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangelogEntry } from "./ChangelogEntry";
import type { Invariant } from "./Invariant";

/**
 * Module-level navigation manifest — the `@module { ... }` annotation.
 *
 * Every Crush source file should declare one. Advisorily enforced today;
 * `--strict-manifest` (planned) will make it a hard compiler error to omit.
 *
 * Attached to `Program.manifest`.
 */
export type ModuleManifest = { 
/**
 * One-line description of what this module does and why it exists.
 * Required. This is what `codebase.modules()` returns — it must fit in
 * one context line and answer "should I read this file?"
 */
purpose: string, 
/**
 * Public symbol names this module exports to callers.
 * Agents use this to know what they can call without reading the source.
 */
exports: Array<string>, 
/**
 * Named invariants this module upholds. Agents read these before touching
 * the module to know what must remain true after their change.
 */
invariants: Array<Invariant>, 
/**
 * Semantically related modules. Not just imports — conceptual coupling.
 * E.g. `scheduler` lists `vm.types` as related because it uses Value/Frame
 * even though vm.types doesn't import scheduler.
 */
related: Array<string>, 
/**
 * Sum types declared as requiring exhaustive match coverage tracking.
 * The compiler records every site that matches on these types in
 * `Program.exhaustive_sites`. Agents query `codebase.exhaustive_sites()`
 * before adding a new variant to know all sites that need updating.
 */
exhaustive_types: Array<string>, 
/**
 * Chronological change log (newest last). Lightweight dejavue integration —
 * the compiler writes here from commit metadata when `--embed-changelog` is set.
 */
changelog: Array<ChangelogEntry>, };
