// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ParameterSchema = { name: string, description: string, type_hint: string, required: boolean, default_value: JsonValue | null, };
