// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expression } from "./Expression";

export type Pattern = { "type": "Literal", value: Expression, } | { "type": "Identifier", name: string, } | { "type": "Struct", name: string, fields: Array<[string, Pattern]>, } | { "type": "Wildcard" };
