// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Priority levels for goals and tasks
 */
export type Priority = "Low" | "Medium" | "High" | "Critical";
