// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIMetadata } from "./AIMetadata";
import type { DecisionNode } from "./DecisionNode";
import type { ExhaustiveMatchSite } from "./ExhaustiveMatchSite";
import type { Function } from "./Function";
import type { ModuleManifest } from "./ModuleManifest";
import type { TemporaryNode } from "./TemporaryNode";
import type { WipNode } from "./WipNode";

export type Program = { cast_version: string, entry: string, lang: string | null, functions: { [key in string]: Function }, 
/**
 * AI execution metadata (goals, tool-chains, delegation).
 */
ai_meta?: AIMetadata | null, 
/**
 * Navigation manifest (@module annotation): purpose, exports, invariants,
 * related modules. Consumed by crush-index to build the queryable index.
 */
manifest?: ModuleManifest | null, 
/**
 * Exhaustive match sites for tracked sum types (compiler-populated).
 * Set for each type listed in `manifest.exhaustive_types`.
 */
exhaustive_sites?: Array<ExhaustiveMatchSite>, 
/**
 * Work-in-progress node, if a `@wip { ... }` block was declared.
 */
wip?: WipNode | null, 
/**
 * Technical-debt nodes from `@temporary { ... }` blocks.
 */
temporaries?: Array<TemporaryNode>, 
/**
 * Architectural decision records from `@decision "name" { ... }` blocks.
 */
decisions?: Array<DecisionNode>, };
