// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A source location used for diagnostics and index navigation.
 */
export type SourceLoc = { 
/**
 * Relative file path from the workspace root.
 */
file: string, 
/**
 * 1-based line number.
 */
line: number, 
/**
 * 1-based column number.
 */
col: number, };
