// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIStatement } from "./AIStatement";
import type { CastType } from "./CastType";
import type { DomMutationType } from "./DomMutationType";
import type { Expression } from "./Expression";
import type { ImportStatement } from "./ImportStatement";
import type { JsonValue } from "./serde_json/JsonValue";

export type Statement = { "type": "VarDecl", name: string, value: Expression, type_hint: CastType, meta: { [key in string]: JsonValue }, } | { "type": "Export", name: string, value: Expression, meta: { [key in string]: JsonValue }, } | { "type": "ExprStmt", expr: Expression, meta: { [key in string]: JsonValue }, } | { "type": "If", condition: Expression, then_body: Array<Statement>, else_body: Array<Statement> | null, meta: { [key in string]: JsonValue }, } | { "type": "While", condition: Expression, body: Array<Statement>, meta: { [key in string]: JsonValue }, } | { "type": "For", variable: string, iterable: Expression, body: Array<Statement>, meta: { [key in string]: JsonValue }, } | { "type": "Return", value: Expression | null, meta: { [key in string]: JsonValue }, } | { "type": "TryCatch", body: Array<Statement>, error_var: string, handler: Array<Statement>, meta: { [key in string]: JsonValue }, } | { "type": "Throw", value: Expression, meta: { [key in string]: JsonValue }, } | { "type": "FunctionDef", name: string, params: Array<[string, CastType]>, body: Array<Statement>, meta: { [key in string]: JsonValue }, } | { "type": "SetField", target: Expression, field: string, value: Expression, meta: { [key in string]: JsonValue }, } | { "type": "LangBlock", 
/**
 * Language name: python, javascript, rust, etc.
 */
lang: string, 
/**
 * Raw source code to execute
 */
code: string, 
/**
 * Variables to inject into the sandbox
 */
variables: Array<string>, 
/**
 * Import statements within the block
 */
imports: Array<ImportStatement>, meta: { [key in string]: JsonValue }, } | { "type": "Import", 
/**
 * The import to resolve
 */
import: ImportStatement, meta: { [key in string]: JsonValue }, } | { "type": "StructDef", name: string, fields: Array<[string, CastType]>, meta: { [key in string]: JsonValue }, } | { "type": "Break", meta: { [key in string]: JsonValue }, } | { "type": "Continue", meta: { [key in string]: JsonValue }, } | { "type": "DomMutate", target: Expression, mutation_type: DomMutationType, value: Expression | null, value2: Expression | null, meta: { [key in string]: JsonValue }, } | { "type": "DomEventListener", target: Expression, event: string, callback: Expression, meta: { [key in string]: JsonValue }, } | { "type": "AI" } & AIStatement;
