// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `@temporary` node declaring technical debt with an intended expiry condition.
 */
export type TemporaryNode = { 
/**
 * Why this temporary code exists.
 */
reason: string, 
/**
 * Condition under which it should be removed.
 */
expires_when?: string | null, 
/**
 * Who is responsible for removing it.
 */
owner?: string | null, 
/**
 * ISO 8601 date when this block was added, e.g. `"2026-06-17"`.
 */
added?: string | null, };
