// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Tool call specification
 */
export type ToolCall = { tool_name: string, parameters: { [key in string]: JsonValue }, result_binding: string | null, condition: string | null, required_capability: string | null, };
