// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterSchema } from "./ParameterSchema";

export type ToolSchema = { name: string, description: string, parameters: { [key in string]: ParameterSchema }, return_type: string, mcp_server: string | null, mcp_method: string | null, };
