// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorLikelihood } from "./ErrorLikelihood";

/**
 * An error variant annotated with a probabilistic likelihood.
 */
export type WeightedError = { 
/**
 * Error variant name, e.g. `"NetworkTimeout"`.
 */
variant: string, 
/**
 * Likelihood level.
 */
likelihood: ErrorLikelihood, };
