// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `@wip` node declaring in-progress work on a module.
 */
export type WipNode = { 
/**
 * One-line description of the in-progress task.
 */
intent: string, 
/**
 * Agent or human who started this work.
 */
started_by?: string | null, 
/**
 * Subtasks already completed.
 */
done?: Array<string>, 
/**
 * Subtasks still to be done.
 */
todo?: Array<string>, 
/**
 * Open questions blocking or complicating completion.
 */
unresolved?: Array<string>, };
