//! CASM → Rust source code generator.

/// Transpile a CASM program to Rust source code.
pub fn gen_rust_source(program: &casm::Program) -> String {
    let mut out = String::new();

    emit_header(&mut out);
    emit_runtime_value(&mut out);
    emit_helpers(&mut out);

    for (name, func) in &program.functions {
        emit_function(&mut out, name, func, program);
    }

    emit_entry_point(&mut out);
    out
}

// ── Header ──────────────────────────────────────────────────────────────────

fn emit_header(out: &mut String) {
    out.push_str(r#"// Generated by crush-aot. Do not edit.
// CASM → Rust transpiled stack machine.
#![allow(non_snake_case, unused_mut, unused_assignments, clippy::all)]
use std::collections::HashMap;
use std::rc::Rc;
use std::cell::RefCell;

"#);
}

// ── RuntimeValue ────────────────────────────────────────────────────────────

fn emit_runtime_value(out: &mut String) {
    out.push_str(r#"#[derive(Debug, Clone)]
pub enum RuntimeValue {
    Int(i64),
    Float(f64),
    Bool(bool),
    Null,
    String(String),
    Array(std::rc::Rc<std::cell::RefCell<Vec<RuntimeValue>>>),
    Object(std::rc::Rc<std::cell::RefCell<std::collections::HashMap<String, RuntimeValue>>>),
}

impl std::fmt::Display for RuntimeValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            RuntimeValue::Int(i) => write!(f, "{}", i),
            RuntimeValue::Float(n) => write!(f, "{}", n),
            RuntimeValue::Bool(b) => write!(f, "{}", b),
            RuntimeValue::Null => write!(f, "null"),
            RuntimeValue::String(s) => write!(f, "\"{}\"", s),
            RuntimeValue::Array(arr) => {{
                let a = arr.borrow();
                write!(f, "[")?;
                for (i, v) in a.iter().enumerate() {{
                    if i > 0 {{ write!(f, ", ")?; }}
                    write!(f, "{}", v)?;
                }}
                write!(f, "]")
            }}
            RuntimeValue::Object(obj) => {{
                let o = obj.borrow();
                write!(f, "{{")?;
                for (i, (k, v)) in o.iter().enumerate() {{
                    if i > 0 {{ write!(f, ", ")?; }}
                    write!(f, "{}: {}", k, v)?;
                }}
                write!(f, "}}")
            }}
        }
    }
}

impl PartialEq for RuntimeValue {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (RuntimeValue::Int(a), RuntimeValue::Int(b)) => a == b,
            (RuntimeValue::Float(a), RuntimeValue::Float(b)) => a == b,
            (RuntimeValue::Bool(a), RuntimeValue::Bool(b)) => a == b,
            (RuntimeValue::Null, RuntimeValue::Null) => true,
            (RuntimeValue::String(a), RuntimeValue::String(b)) => a == b,
            (RuntimeValue::Array(a), RuntimeValue::Array(b)) => *a.borrow() == *b.borrow(),
            (RuntimeValue::Object(a), RuntimeValue::Object(b)) => *a.borrow() == *b.borrow(),
            _ => false,
        }
    }
}

"#);
}

// ── Helpers ─────────────────────────────────────────────────────────────────

fn emit_helpers(out: &mut String) {
    out.push_str(r#"#[inline(always)]
fn truthy(v: &RuntimeValue) -> bool {
    match v { RuntimeValue::Bool(b) => *b, RuntimeValue::Int(i) => *i != 0, RuntimeValue::Null => false, RuntimeValue::Array(a) => !a.borrow().is_empty(), _ => true }
}

fn pop2(stack: &mut Vec<RuntimeValue>) -> (RuntimeValue, RuntimeValue) {
    let b = stack.pop().unwrap_or(RuntimeValue::Null);
    let a = stack.pop().unwrap_or(RuntimeValue::Null);
    (a, b)
}

fn bin_arith(stack: &mut Vec<RuntimeValue>, iop: fn(i64,i64)->i64, fop: fn(f64,f64)->f64) {
    let (a, b) = pop2(stack);
    let r = match (&a, &b) {
        (RuntimeValue::Int(x), RuntimeValue::Int(y)) => RuntimeValue::Int(iop(*x, *y)),
        (RuntimeValue::Float(x), RuntimeValue::Float(y)) => RuntimeValue::Float(fop(*x, *y)),
        (RuntimeValue::Int(x), RuntimeValue::Float(y)) => RuntimeValue::Float(fop(*x as f64, *y)),
        (RuntimeValue::Float(x), RuntimeValue::Int(y)) => RuntimeValue::Float(fop(*x, *y as f64)),
        // A non-numeric operand used to fall through to `RuntimeValue::Null` — SILENTLY. The
        // interpreter raises a TypeError on the same source, so an AOT-compiled binary and
        // `crush-run` returned different answers with no error from either. Crash instead.
        // (String `+` is handled by bin_add before this is ever reached; anything landing here
        // is a genuine type error.)
        _ => {
            eprintln!("crush(aot): type error: arithmetic on non-numeric operands ({:?}, {:?})", a, b);
            std::process::exit(1);
        }
    };
    stack.push(r);
}

/// `+` — numeric addition, or string concatenation when EITHER side is a string.
///
/// MUST match crush-vm's scheduler.rs and portable_vm.rs exactly. These are separate
/// implementations of the same language, and any divergence is a silent miscompile.
fn bin_add(stack: &mut Vec<RuntimeValue>) {
    let is_str = |v: &RuntimeValue| matches!(v, RuntimeValue::String(_));
    let n = stack.len();
    let mixed = n >= 2 && (is_str(&stack[n - 1]) || is_str(&stack[n - 2]));
    if mixed {
        let (a, b) = pop2(stack);
        stack.push(RuntimeValue::String(format!("{}{}", as_text(&a), as_text(&b))));
    } else {
        bin_arith(stack, |a, b| a.wrapping_add(b), |a, b| a + b);
    }
}

fn as_text(v: &RuntimeValue) -> String {
    match v {
        RuntimeValue::String(s) => s.clone(),
        RuntimeValue::Int(i) => i.to_string(),
        RuntimeValue::Float(f) => f.to_string(),
        RuntimeValue::Bool(b) => b.to_string(),
        RuntimeValue::Null => "null".to_string(),
        other => format!("{:?}", other),
    }
}

fn div_zero() -> i64 {
    eprintln!("crush(aot): division by zero");
    std::process::exit(1);
}

fn div_zero_f() -> f64 {
    eprintln!("crush(aot): division by zero");
    std::process::exit(1);
}

fn bin_cmp(stack: &mut Vec<RuntimeValue>, icmp: fn(i64,i64)->bool, fcmp: fn(f64,f64)->bool) {
    let (a, b) = pop2(stack);
    let r = match (&a, &b) {
        (RuntimeValue::Int(x), RuntimeValue::Int(y)) => icmp(*x, *y),
        (RuntimeValue::Float(x), RuntimeValue::Float(y)) => fcmp(*x, *y),
        (RuntimeValue::Int(x), RuntimeValue::Float(y)) => fcmp(*x as f64, *y),
        (RuntimeValue::Float(x), RuntimeValue::Int(y)) => fcmp(*x, *y as f64),
        (RuntimeValue::Bool(x), RuntimeValue::Bool(y)) => x == y,
        (RuntimeValue::Null, RuntimeValue::Null) => true,
        _ => false,
    };
    stack.push(RuntimeValue::Bool(r));
}

fn logic_op(stack: &mut Vec<RuntimeValue>, is_and: bool) {
    let (a, b) = pop2(stack);
    let ta = truthy(&a); let tb = truthy(&b);
    stack.push(RuntimeValue::Bool(if is_and { ta && tb } else { ta || tb }));
}

fn negate(stack: &mut Vec<RuntimeValue>) {
    match stack.pop().unwrap_or(RuntimeValue::Null) {
        RuntimeValue::Int(i) => stack.push(RuntimeValue::Int(-i)),
        RuntimeValue::Float(f) => stack.push(RuntimeValue::Float(-f)),
        _ => stack.push(RuntimeValue::Null),
    }
}

fn do_not(stack: &mut Vec<RuntimeValue>) {
    let v = !truthy(&stack.pop().unwrap_or(RuntimeValue::Null));
    stack.push(RuntimeValue::Bool(v));
}

fn wrap_index(idx: i64, len: usize) -> Option<usize> {
    let ilen = len as i64;
    let wrapped = if idx < 0 { ilen + idx } else { idx };
    if wrapped >= 0 && wrapped < ilen { Some(wrapped as usize) } else { None }
}

"#);
}

// ���─ Function emission ───────────────────────────────────────────────────────

fn emit_function(
    out: &mut String,
    name: &str,
    func: &casm::Function,
    _program: &casm::Program,
) {
    let fn_name = sanitize_fn_name(name);
    let is_main = name == "main";
    let n = func.body.len();

    out.push_str(&format!("#[inline(never)]\nfn {fn_name}("));
    if is_main {
        out.push_str(") -> RuntimeValue {\n");
    } else {
        out.push_str("args: &[RuntimeValue]) -> RuntimeValue {\n");
    }

    // Locals map
    out.push_str("    let mut stack: Vec<RuntimeValue> = Vec::with_capacity(64);\n");
    out.push_str("    let mut locals: HashMap<String, RuntimeValue> = HashMap::new();\n");

    // Load parameters for non-main functions
    if !is_main {
        for (i, param) in func.params.iter().enumerate() {
            out.push_str(&format!(
                "    locals.insert(\"{param}\".to_string(), args.get({i}).cloned().unwrap_or(RuntimeValue::Null));\n"
            ));
        }
    }

    // Dispatch loop
    out.push_str(&format!("    let mut __pc: usize = 0;\n"));
    out.push_str("    loop {\n");
    out.push_str("        match __pc {\n");

    for (i, instr) in func.body.iter().enumerate() {
        out.push_str(&format!("            {i} => {{\n"));
        emit_body(out, instr, i, n);
        out.push_str("            }\n");
    }

    // Default case: halt
    out.push_str("            _ => return stack.pop().unwrap_or(RuntimeValue::Null),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn sanitize_fn_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

// ── Instruction body emission ───────────────────────────────────────────────

fn emit_body(
    out: &mut String,
    instr: &casm::Instruction,
    this_pc: usize,
    total_instrs: usize,
) {
    let args = &instr.args;
    let next = this_pc + 1;
    let next_pc = if next < total_instrs { next } else { total_instrs }; // fall-through
    let ind = "                ";

    let next_pc_str = format!("{ind}__pc = {next_pc};\n{ind}continue;\n");

    match instr.op.as_str() {
        // ── Push ──
        "push_int" => {
            let v = args["value"].as_i64().unwrap_or(0);
            out.push_str(&format!("{ind}stack.push(RuntimeValue::Int({v}));\n"));
            out.push_str(&next_pc_str);
        }
        "push_float" => {
            let v = args["value"].as_f64().unwrap_or(0.0);
            // Use hex literal for exact representation
            out.push_str(&format!("{ind}stack.push(RuntimeValue::Float({v:e}));\n"));
            out.push_str(&next_pc_str);
        }
        "push_bool" => {
            let v = args["value"].as_bool().unwrap_or(false);
            out.push_str(&format!("{ind}stack.push(RuntimeValue::Bool({v}));\n"));
            out.push_str(&next_pc_str);
        }
        "push_null" => {
            out.push_str(&format!("{ind}stack.push(RuntimeValue::Null);\n"));
            out.push_str(&next_pc_str);
        }
        "push_str" => {
            let s = args["value"].as_str().unwrap_or("");
            let escaped = s.escape_default().to_string();
            out.push_str(&format!("{ind}stack.push(RuntimeValue::String(\"{escaped}\".to_string()));\n"));
            out.push_str(&next_pc_str);
        }

        // ── Stack ops ──
        "pop" => {
            out.push_str(&format!("{ind}stack.pop();\n"));
            out.push_str(&next_pc_str);
        }
        "dup" => {
            out.push_str(&format!("{ind}let v = stack.last().map(|x| x.clone()).unwrap_or(RuntimeValue::Null); stack.push(v);\n"));
            out.push_str(&next_pc_str);
        }
        "swap" => {
            out.push_str(&format!("{ind}let len = stack.len(); if len >= 2 {{ let i = len - 1; let j = len - 2; stack.swap(i, j); }}\n"));
            out.push_str(&next_pc_str);
        }

        // ── Locals ──
        "load" => {
            let name = args["name"].as_str().unwrap_or("");
            out.push_str(&format!(
                "{ind}stack.push(locals.get(\"{name}\").cloned().unwrap_or(RuntimeValue::Null));\n"
            ));
            out.push_str(&next_pc_str);
        }
        "store" => {
            let name = args["name"].as_str().unwrap_or("");
            out.push_str(&format!(
                "{ind}let __v = stack.pop().unwrap_or(RuntimeValue::Null); locals.insert(\"{name}\".to_string(), __v);\n"
            ));
            out.push_str(&next_pc_str);
        }

        // ── Arithmetic ──
        "add"  => { out.push_str(&format!("{ind}bin_add(&mut stack);\n")); out.push_str(&next_pc_str); }
        "sub"  => { out.push_str(&format!("{ind}bin_arith(&mut stack, |a,b| a.wrapping_sub(b), |a,b| a-b);\n")); out.push_str(&next_pc_str); }
        "mul"  => { out.push_str(&format!("{ind}bin_arith(&mut stack, |a,b| a.wrapping_mul(b), |a,b| a*b);\n")); out.push_str(&next_pc_str); }
        // Division by zero was SILENTLY yielding 0 here while the interpreter raised
        // VmError::DivisionByZero on the same source. `1 / 0` printed "0" from an AOT binary
        // and errored under crush-run. Same program, different answers, no error. Now both die.
        "div"  => { out.push_str(&format!("{ind}bin_arith(&mut stack, |a,b| if b!=0 {{ a/b }} else {{ div_zero() }}, |a,b| if b!=0.0 {{ a/b }} else {{ div_zero_f() }});\n")); out.push_str(&next_pc_str); }
        "mod"  => { out.push_str(&format!("{ind}bin_arith(&mut stack, |a,b| if b!=0 {{ a%b }} else {{ div_zero() }}, |a,b| if b!=0.0 {{ a%b }} else {{ div_zero_f() }});\n")); out.push_str(&next_pc_str); }
        "neg"  => { out.push_str(&format!("{ind}negate(&mut stack);\n")); out.push_str(&next_pc_str); }

        // ── Math ops ──
        "math_pow" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::Float(x),RuntimeValue::Float(y))=>RuntimeValue::Float(x.powf(*y)), (RuntimeValue::Int(x),RuntimeValue::Int(y))=>RuntimeValue::Float((*x as f64).powf(*y as f64)), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "math_sqrt" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match &v {{ RuntimeValue::Float(x)=>RuntimeValue::Float(x.sqrt()), RuntimeValue::Int(x)=>RuntimeValue::Float((*x as f64).sqrt()), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "math_abs" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match &v {{ RuntimeValue::Int(x)=>RuntimeValue::Int(x.abs()), RuntimeValue::Float(x)=>RuntimeValue::Float(x.abs()), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "math_round" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match &v {{ RuntimeValue::Float(x)=>RuntimeValue::Float(x.round()), RuntimeValue::Int(x)=>RuntimeValue::Int(*x), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "math_floor" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match &v {{ RuntimeValue::Float(x)=>RuntimeValue::Float(x.floor()), RuntimeValue::Int(x)=>RuntimeValue::Int(*x), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "math_ceil" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match &v {{ RuntimeValue::Float(x)=>RuntimeValue::Float(x.ceil()), RuntimeValue::Int(x)=>RuntimeValue::Int(*x), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }

        // ── Comparison ──
        "eq" => { out.push_str(&format!("{ind}bin_cmp(&mut stack, |a,b| a==b, |a,b| a==b);\n")); out.push_str(&next_pc_str); }
        "ne" => { out.push_str(&format!("{ind}bin_cmp(&mut stack, |a,b| a!=b, |a,b| a!=b);\n")); out.push_str(&next_pc_str); }
        "lt" => { out.push_str(&format!("{ind}bin_cmp(&mut stack, |a,b| a<b, |a,b| a<b);\n")); out.push_str(&next_pc_str); }
        "le" => { out.push_str(&format!("{ind}bin_cmp(&mut stack, |a,b| a<=b, |a,b| a<=b);\n")); out.push_str(&next_pc_str); }
        "gt" => { out.push_str(&format!("{ind}bin_cmp(&mut stack, |a,b| a>b, |a,b| a>b);\n")); out.push_str(&next_pc_str); }
        "ge" => { out.push_str(&format!("{ind}bin_cmp(&mut stack, |a,b| a>=b, |a,b| a>=b);\n")); out.push_str(&next_pc_str); }

        // ── Logical ──
        "and"   => { out.push_str(&format!("{ind}logic_op(&mut stack, true);\n")); out.push_str(&next_pc_str); }
        "or"    => { out.push_str(&format!("{ind}logic_op(&mut stack, false);\n")); out.push_str(&next_pc_str); }
        "not"   => { out.push_str(&format!("{ind}do_not(&mut stack);\n")); out.push_str(&next_pc_str); }

        // ── String ops ──
        "str_contains" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::String(h),RuntimeValue::String(n))=>RuntimeValue::Bool(h.contains(n.as_str())), _=>RuntimeValue::Bool(false) }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "str_starts_with" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::String(s),RuntimeValue::String(p))=>RuntimeValue::Bool(s.starts_with(p.as_str())), _=>RuntimeValue::Bool(false) }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "str_ends_with" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::String(s),RuntimeValue::String(p))=>RuntimeValue::Bool(s.ends_with(p.as_str())), _=>RuntimeValue::Bool(false) }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "str_to_upper" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match v {{ RuntimeValue::String(s)=>RuntimeValue::String(s.to_uppercase()), other=>other }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "str_to_lower" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match v {{ RuntimeValue::String(s)=>RuntimeValue::String(s.to_lowercase()), other=>other }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "str_trim" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match v {{ RuntimeValue::String(s)=>RuntimeValue::String(s.trim().to_string()), other=>other }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "str_split" | "str_replace" | "str_join" => {
            out.push_str(&format!("{ind}stack.pop(); stack.pop(); stack.push(RuntimeValue::Null);\n"));
            out.push_str(&next_pc_str);
        }

        // ── Bitwise ops ──
        "bit_and" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::Int(x),RuntimeValue::Int(y))=>RuntimeValue::Int(x & y), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "bit_or" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::Int(x),RuntimeValue::Int(y))=>RuntimeValue::Int(x | y), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "bit_xor" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::Int(x),RuntimeValue::Int(y))=>RuntimeValue::Int(x ^ y), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "bit_not" => {
            out.push_str(&format!("{ind}{{ let v=stack.pop().unwrap_or(RuntimeValue::Null); let r=match &v {{ RuntimeValue::Int(x)=>RuntimeValue::Int(!x), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "shl" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::Int(x),RuntimeValue::Int(y))=>RuntimeValue::Int(x << y), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }
        "shr" => {
            out.push_str(&format!("{ind}{{ let (a,b)=pop2(&mut stack); let r=match (&a,&b) {{ (RuntimeValue::Int(x),RuntimeValue::Int(y))=>RuntimeValue::Int(x >> y), _=>RuntimeValue::Null }}; stack.push(r); }}\n"));
            out.push_str(&next_pc_str);
        }

        // ── Control flow ──
        "jmp" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!("{ind}__pc = {t};\n{ind}continue;\n"));
            } else {
                out.push_str(&next_pc_str);
            }
        }
        "jmp_if" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "{ind}if truthy(stack.last().unwrap_or(&RuntimeValue::Null)) {{ stack.pop(); __pc = {t}; continue; }} else {{ stack.pop(); __pc = {next_pc}; continue; }}\n"
                ));
            } else {
                out.push_str(&next_pc_str);
            }
        }
        "jmp_if_not" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "{ind}if !truthy(stack.last().unwrap_or(&RuntimeValue::Null)) {{ stack.pop(); __pc = {t}; continue; }} else {{ stack.pop(); __pc = {next_pc}; continue; }}\n"
                ));
            } else {
                out.push_str(&next_pc_str);
            }
        }
        "ret" | "halt" => {
            out.push_str(&format!("{ind}return stack.pop().unwrap_or(RuntimeValue::Null);\n"));
        }

        // ── Call ──
        "call" => {
            let target = args["function"].as_str().unwrap_or("");
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
            let fn_name = sanitize_fn_name(target);
            out.push_str(&format!(
                "{ind}{{ let mut __args = Vec::with_capacity({argc});\n\
                 {ind}  for _ in 0..{argc} {{ __args.push(stack.pop().unwrap_or(RuntimeValue::Null)); }}\n\
                 {ind}  __args.reverse();\n\
                 {ind}  let __result = {fn_name}(&__args);\n\
                 {ind}  stack.push(__result);\n\
                 {ind}}}\n"
            ));
            out.push_str(&next_pc_str);
        }

        // ── Arrays ──
        "new_array" => {
            // Size is a pre-allocation hint — elements are pushed separately.
            // Always create an empty array.
            out.push_str(&format!(
                "{ind}{{ stack.push(RuntimeValue::Array(Rc::new(RefCell::new(Vec::new())))); }}\n"
            ));
            out.push_str(&next_pc_str);
        }
        "arr_get" | "index" => {{
            out.push_str(&format!("{ind}{{ let __idx = stack.pop().unwrap_or(RuntimeValue::Null); let __arr = stack.pop(); if let Some(RuntimeValue::Array(ref a)) = __arr {{ let a = a.borrow(); if let RuntimeValue::Int(i) = __idx {{ let __v = wrap_index(i, a.len()).and_then(|j| a.get(j).cloned()).unwrap_or(RuntimeValue::Null); stack.push(__v); }} else {{ stack.push(RuntimeValue::Null); }} }} else {{ stack.push(RuntimeValue::Null); }} }}\n"));
            out.push_str(&next_pc_str);
        }}
        "arr_set" => {{
            out.push_str(&format!("{ind}{{ let __val = stack.pop().unwrap_or(RuntimeValue::Null); let __idx = stack.pop().unwrap_or(RuntimeValue::Null); let __arr = stack.pop(); if let Some(RuntimeValue::Array(ref a)) = __arr {{ if let RuntimeValue::Int(i) = __idx {{ let mut a = a.borrow_mut(); if let Some(j) = wrap_index(i, a.len()) {{ a[j] = __val; }} }} }} }}\n"));
            out.push_str(&next_pc_str);
        }}
        "arr_len" | "len" => {{
            out.push_str(&format!("{ind}{{ let __v = stack.pop().unwrap_or(RuntimeValue::Null); let __l = match &__v {{ RuntimeValue::Array(a) => a.borrow().len() as i64, RuntimeValue::String(s) => s.len() as i64, _ => 0 }}; stack.push(RuntimeValue::Int(__l)); }}\n"));
            out.push_str(&next_pc_str);
        }}
        "arr_push" | "array_push" => {{
            out.push_str(&format!("{ind}{{ let __val = stack.pop().unwrap_or(RuntimeValue::Null); let __arr = stack.pop(); let mut __ok = false; if let Some(RuntimeValue::Array(ref a)) = __arr {{ a.borrow_mut().push(__val); __ok = true; }} if __ok {{ stack.push(__arr.unwrap()); }} else {{ stack.push(RuntimeValue::Null); }} }}\n"));
            out.push_str(&next_pc_str);
        }}
        "arr_pop" | "array_pop" => {{
            out.push_str(&format!("{ind}{{ let __arr = stack.pop(); let __popped; let __pushed; if let Some(RuntimeValue::Array(ref a)) = __arr {{ __popped = a.borrow_mut().pop().unwrap_or(RuntimeValue::Null); __pushed = true; }} else {{ __popped = RuntimeValue::Null; __pushed = false; }} if __pushed {{ stack.push(__arr.unwrap()); }} else {{ stack.push(RuntimeValue::Null); }} stack.push(__popped); }}\n"));
            out.push_str(&next_pc_str);
        }}
        "make_range" => {{
            out.push_str(&format!("{ind}{{ let __end = stack.pop().unwrap_or(RuntimeValue::Null); let __start = stack.pop().unwrap_or(RuntimeValue::Null); let __s = if let RuntimeValue::Int(i) = &__start {{ *i }} else {{ 0 }}; let __e = if let RuntimeValue::Int(i) = &__end {{ *i }} else {{ 0 }}; let __r: Vec<RuntimeValue> = (__s..__e).map(RuntimeValue::Int).collect(); stack.push(RuntimeValue::Array(Rc::new(RefCell::new(__r)))); }}\n"));
            out.push_str(&next_pc_str);
        }}

        // ── Objects ──
        "new_obj" => {{
            out.push_str(&format!("{ind}{{ stack.push(RuntimeValue::Object(Rc::new(RefCell::new(HashMap::new())))); }}\n"));
            out.push_str(&next_pc_str);
        }}
        "get_field" => {{
            let field = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            out.push_str(&format!("{ind}{{ let __obj = stack.pop(); let __v = if let Some(RuntimeValue::Object(ref o)) = __obj {{ o.borrow().get(\"{field}\").cloned().unwrap_or(RuntimeValue::Null) }} else {{ RuntimeValue::Null }}; stack.push(__v); }}\n"));
            out.push_str(&next_pc_str);
        }}
        "set_field" => {{
            let field = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            out.push_str(&format!("{ind}{{ let __val = stack.pop().unwrap_or(RuntimeValue::Null); let __obj = stack.pop(); if let Some(RuntimeValue::Object(ref o)) = __obj {{ o.borrow_mut().insert(\"{field}\".to_string(), __val); }} }}\n"));
            out.push_str(&next_pc_str);
        }}

        // ── Cap calls → inline dispatch ──
        "cap_call" => {
            let cap_name = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
            match cap_name {
                "append" | "push" | "arr.push" | "array.push" => {
                    out.push_str(&format!("{ind}{{ let __val = stack.pop().unwrap_or(RuntimeValue::Null); let __arr = stack.pop(); if let Some(RuntimeValue::Array(ref a)) = __arr {{ a.borrow_mut().push(__val); }} }}\n"));
                    out.push_str(&next_pc_str);
                }
                "arr_get" => {
                    out.push_str(&format!("{ind}{{ let __idx = stack.pop().unwrap_or(RuntimeValue::Null); let __arr = stack.pop(); if let Some(RuntimeValue::Array(ref a)) = __arr {{ let a = a.borrow(); if let RuntimeValue::Int(i) = __idx {{ let __v = wrap_index(i, a.len()).and_then(|j| a.get(j).cloned()).unwrap_or(RuntimeValue::Null); stack.push(__v); }} }} else {{ stack.push(RuntimeValue::Null); }} }}\n"));
                    out.push_str(&next_pc_str);
                }
                "arr_set" => {
                    out.push_str(&format!("{ind}{{ let __val = stack.pop().unwrap_or(RuntimeValue::Null); let __idx = stack.pop().unwrap_or(RuntimeValue::Null); let __arr = stack.pop(); if let Some(RuntimeValue::Array(ref a)) = __arr {{ if let RuntimeValue::Int(i) = __idx {{ let mut a = a.borrow_mut(); if let Some(j) = wrap_index(i, a.len()) {{ a[j] = __val; }} }} }} }}\n"));
                    out.push_str(&next_pc_str);
                }
                "make_range" => {
                    out.push_str(&format!("{ind}{{ let mut __start: i64 = 0; let mut __end: i64 = 100; if {argc} >= 2 {{ let __ev = stack.pop().unwrap_or(RuntimeValue::Null); let __sv = stack.pop().unwrap_or(RuntimeValue::Null); __end = if let RuntimeValue::Int(i) = &__ev {{ *i }} else {{ 100 }}; __start = if let RuntimeValue::Int(i) = &__sv {{ *i }} else {{ 0 }}; }} else if {argc} >= 1 {{ let __ev = stack.pop().unwrap_or(RuntimeValue::Null); __end = if let RuntimeValue::Int(i) = &__ev {{ *i }} else {{ 100 }}; }} let __r: Vec<RuntimeValue> = (__start..__end).map(RuntimeValue::Int).collect(); stack.push(RuntimeValue::Array(Rc::new(RefCell::new(__r)))); }}\n"));
                    out.push_str(&next_pc_str);
                }
                "io.print" | "print" => {
                    out.push_str(&format!("{ind}{{ let __v = stack.pop().unwrap_or(RuntimeValue::Null); println!(\"{{}}\", __v); }}\n"));
                    out.push_str(&next_pc_str);
                }
                _ => {
                    out.push_str(&format!("{ind}for _ in 0..{argc} {{ stack.pop(); }} stack.push(RuntimeValue::Null); // cap_call '{0}' stubbed\n", cap_name.escape_debug()));
                    out.push_str(&next_pc_str);
                }
            }
        }

        // ── Unknown / NOP ──
        _ => {
            out.push_str(&next_pc_str);
        }
    }
}

// ── Entry point ─────────────────────────────────────────────────────────────

fn emit_entry_point(out: &mut String) {
    out.push_str(r#"
#[unsafe(no_mangle)]
pub extern "C" fn crush_run() -> *mut std::ffi::c_char {
    let result = main();
    let json = format!("{}", result);
    let c_str = std::ffi::CString::new(json).unwrap_or_default();
    c_str.into_raw()
}

#[unsafe(no_mangle)]
pub extern "C" fn crush_run_free(s: *mut std::ffi::c_char) {
    if !s.is_null() {
        unsafe { drop(std::ffi::CString::from_raw(s)); }
    }
}
"#);
}
