//! CASM → C source code generator.
//!
//! Transpiles a `casm::Program` into self-contained C99 source with a
//! `switch(pc)` dispatch loop that compilers optimize into jump tables.
//!
//! The generated C defines its own tagged union (`Value`) and stack machine,
//! and exports a `crush_run()` symbol for dlopen-based loading.

use std::collections::HashMap;

/// Transpile a CASM program to C source code.
pub fn gen_c_source(program: &casm::Program) -> String {
    let mut out = String::new();

    emit_c_header(&mut out);
    emit_c_value(&mut out);
    emit_c_helpers(&mut out);

    // Forward declarations (needed because CASM functions may call each other)
    for (name, _func) in &program.functions {
        let fn_name = sanitize_fn_name(name);
        out.push_str(&format!("static Value fn_{fn_name}(void);\n"));
    }
    out.push_str("\n");

    for (name, func) in &program.functions {
        emit_c_function(&mut out, name, func, program);
    }

    emit_c_entry_point(&mut out);
    out
}

// ── Header ──────────────────────────────────────────────────────────────────

fn emit_c_header(out: &mut String) {
    out.push_str(r#"// Generated by crush-aotc --emit c. Do not edit.
// CASM → C transpiled stack machine.
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <ctype.h>

"#);
}

// ── Tagged Value ────────────────────────────────────────────────────────────

fn emit_c_value(out: &mut String) {
    out.push_str(r#"typedef enum {
    TAG_INT,
    TAG_FLOAT,
    TAG_BOOL,
    TAG_NULL,
    TAG_STRING,
    TAG_ARRAY,
    TAG_OBJECT,
} ValueTag;

typedef struct {
    ValueTag tag;
    union {
        int64_t  i;
        double   f;
        bool     b;
        const char* s;
        int      array_idx;
        int      obj_idx;
    };
} Value;

static inline Value mk_int(int64_t i)   { return (Value){TAG_INT, .i=i}; }
static inline Value mk_float(double f)  { return (Value){TAG_FLOAT, .f=f}; }
static inline Value mk_bool(bool b)     { return (Value){TAG_BOOL, .b=b}; }
static inline Value mk_null(void)       { return (Value){TAG_NULL}; }
static inline Value mk_string(const char* s) { return (Value){TAG_STRING, .s=s}; }
static inline Value mk_array(int idx)   { return (Value){TAG_ARRAY, .array_idx=idx}; }
static inline Value mk_object(int idx)  { return (Value){TAG_OBJECT, .obj_idx=idx}; }

// ── Array pool ───────────────────────────────────────────────────────
#define ARRAY_POOL_MAX 64
#define ARRAY_DATA_CAP 65536

typedef struct {
    Value data[ARRAY_DATA_CAP];
    int   len;
} CrushArray;

static CrushArray _arrays[ARRAY_POOL_MAX];
static int        _array_count = 0;

static inline int _alloc_array(void) {
    if (_array_count >= ARRAY_POOL_MAX) return -1;
    _arrays[_array_count].len = 0;
    return _array_count++;
}

static inline int _wrap_index(int idx, int len) {
    if (idx < 0) idx += len;
    return (idx >= 0 && idx < len) ? idx : -1;
}

// ── Object pool ─────────────────────���────────────────────────────────
#define OBJ_POOL_MAX 32
#define OBJ_FIELD_CAP 16

typedef struct {
    const char* key;
    Value val;
} CrushField;

typedef struct {
    CrushField fields[OBJ_FIELD_CAP];
    int   field_count;
} CrushObject;

static CrushObject _objects[OBJ_POOL_MAX];
static int         _object_count = 0;

static inline int _alloc_object(void) {
    if (_object_count >= OBJ_POOL_MAX) return -1;
    _objects[_object_count].field_count = 0;
    return _object_count++;
}

static Value _obj_get(CrushObject* obj, const char* key) {
    for (int i = 0; i < obj->field_count; i++) {
        if (strcmp(obj->fields[i].key, key) == 0)
            return obj->fields[i].val;
    }
    return mk_null();
}

static void _obj_set(CrushObject* obj, const char* key, Value val) {
    for (int i = 0; i < obj->field_count; i++) {
        if (strcmp(obj->fields[i].key, key) == 0) {
            obj->fields[i].val = val;
            return;
        }
    }
    if (obj->field_count < OBJ_FIELD_CAP) {
        obj->fields[obj->field_count].key = key;
        obj->fields[obj->field_count].val = val;
        obj->field_count++;
    }
}

// ── String buffer (for to_upper / to_lower / trim) ────────────────────
#define STRBUF_SIZE 256
static char _strbuf[STRBUF_SIZE];
static int  _strbuf_idx = 0;

static inline const char* _str_alloc(const char* src) {
    int start = _strbuf_idx;
    int i = 0;
    while (src[i] && start + i < STRBUF_SIZE - 1) {
        _strbuf[start + i] = src[i];
        i++;
    }
    _strbuf[start + i] = '\0';
    _strbuf_idx = start + i + 1;
    if (_strbuf_idx >= STRBUF_SIZE) _strbuf_idx = 0;
    return &_strbuf[start];
}

static inline const char* _str_dup(const char* src) {
    return _str_alloc(src);
}

"#);
}

// ── Stack ───────────────────────────────────────────────────────────────────

fn emit_c_helpers(out: &mut String) {
    out.push_str(r#"// ── Stack ──────────────────────────────────────────────────────────
#define STACK_MAX 512
static Value   _stack[STACK_MAX];
static int     _sp = 0;

static void _reset_arrays(void) { _array_count = 0; _object_count = 0; }

static inline void  _push(Value v) { if (_sp < STACK_MAX) _stack[_sp++] = v; }
static inline Value _pop(void)     { return _sp > 0 ? _stack[--_sp] : mk_null(); }
static inline Value _peek(void)    { return _sp > 0 ? _stack[_sp-1] : mk_null(); }
static inline void  _dup(void)     { if (_sp > 0 && _sp < STACK_MAX) _stack[_sp] = _stack[_sp-1], _sp++; }
static inline void  _swap(void)    { if (_sp >= 2) { Value t=_stack[_sp-1]; _stack[_sp-1]=_stack[_sp-2]; _stack[_sp-2]=t; } }

static inline double _to_float(Value v) { return (v.tag == TAG_FLOAT) ? v.f : ((v.tag == TAG_INT) ? (double)v.i : 0.0); }
static inline int64_t _to_int(Value v) { return (v.tag == TAG_INT) ? v.i : ((v.tag == TAG_FLOAT) ? (int64_t)v.f : 0); }

// ── Helpers ──────────────────────────────────────────────────────────────
static inline bool _truthy(Value v) {
    switch (v.tag) {
        case TAG_BOOL: return v.b;
        case TAG_INT:  return v.i != 0;
        case TAG_NULL: return false;
        default:       return true;
    }
}

static inline bool _is_num(Value v) { return v.tag == TAG_INT || v.tag == TAG_FLOAT; }

// ── String rendering (for string concatenation) ─────────────────────────
// Render a Value to its text form. When the result is a numeric value that
// must be formatted into a buffer, writes to `buf` (which must be at least
// STRBUF_SIZE bytes long). Returns a pointer to either a string constant,
// `v.s`, or `buf`.
static inline const char* _to_text_buf(Value v, char* buf, size_t bufsz) {
    switch (v.tag) {
        case TAG_INT:   snprintf(buf, bufsz, "%ld", (long)v.i); return buf;
        case TAG_FLOAT:
            if (isfinite(v.f) && v.f == (double)(int64_t)v.f) {
                snprintf(buf, bufsz, "%.1f", v.f);
            } else {
                snprintf(buf, bufsz, "%.15g", v.f);
            }
            return buf;
        case TAG_BOOL:  return v.b ? "true" : "false";
        case TAG_NULL:  return "null";
        case TAG_STRING: return v.s;
        default:        return "[opaque]";
    }
}
// Convenience wrapper using the global _strbuf (safe only when result is used immediately).
static inline const char* _to_text(Value v) {
    return _to_text_buf(v, _strbuf, STRBUF_SIZE);
}

static inline void _crush_arith_error(const char *msg) {
    fprintf(stderr, "crush(aotc): %s\n", msg);
    exit(1);
}

static inline int _str_contains_ptr(const char* p) {
    return p >= _strbuf && p < _strbuf + STRBUF_SIZE;
}

static Value _add(Value a, Value b) {
    // String concatenation when either operand is a string
    if (a.tag == TAG_STRING || b.tag == TAG_STRING) {
        char _ta[STRBUF_SIZE], _tb[STRBUF_SIZE];
        const char* sa = _to_text_buf(a, _ta, STRBUF_SIZE);
        const char* sb = _to_text_buf(b, _tb, STRBUF_SIZE);
        int slen = (int)(strlen(sa) + strlen(sb));
        if (slen >= STRBUF_SIZE) return mk_null();            // Allocate at the current ring-buffer position so multiple string
            // results can coexist at different positions in _strbuf.
            int start = _strbuf_idx;
            // CRITICAL: sa or sb may point into _strbuf at positions BEFORE `start`.
            // Writing the concatenated result at `start` would overwrite the trailing
            // portion of the source data before it's been read (if slen > start - src_pos).
            // Save _strbuf to a local buffer when either source is in _strbuf.
            char _strbuf_save[STRBUF_SIZE];
            int need_save = _str_contains_ptr(sa) || _str_contains_ptr(sb);
            if (need_save) {
                memcpy(_strbuf_save, _strbuf, STRBUF_SIZE);
                if (_str_contains_ptr(sa)) sa = _strbuf_save + (sa - _strbuf);
                if (_str_contains_ptr(sb)) sb = _strbuf_save + (sb - _strbuf);
            }
            if (start + slen >= STRBUF_SIZE) {
                // The result doesn't fit at the current position; wrap to 0.
                // This may overwrite older data but is the ring-buffer contract.
                // Sources are already in _strbuf_save so there's no overlap.
                start = 0;
            }
            char* buf = &_strbuf[start];
            int pos = 0;
            while (*sa && start + pos < STRBUF_SIZE - 1) { buf[pos++] = *sa++; }
            while (*sb && start + pos < STRBUF_SIZE - 1) { buf[pos++] = *sb++; }
            buf[pos] = '\0';
            _strbuf_idx = start + pos + 1;
            if (_strbuf_idx >= STRBUF_SIZE) _strbuf_idx = 0;
            return mk_string(buf);
    }
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        int64_t out;
        if (__builtin_add_overflow(a.i, b.i, &out)) _crush_arith_error("arithmetic overflow");
        return mk_int(out);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa + fb);
}
static Value _sub(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        int64_t out;
        if (__builtin_sub_overflow(a.i, b.i, &out)) _crush_arith_error("arithmetic overflow");
        return mk_int(out);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa - fb);
}
static Value _mul(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        int64_t out;
        if (__builtin_mul_overflow(a.i, b.i, &out)) _crush_arith_error("arithmetic overflow");
        return mk_int(out);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa * fb);
}
static Value _div(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        if (b.i == 0) _crush_arith_error("division by zero");
        return mk_int(a.i / b.i);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    if (fb == 0.0) _crush_arith_error("division by zero");
    return mk_float(fa / fb);
}
static Value _mod(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        if (b.i == 0) _crush_arith_error("division by zero");
        return mk_int(a.i % b.i);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    if (fb == 0.0) _crush_arith_error("division by zero");
    return mk_float(fmod(fa, fb));
}
static Value _neg(Value v) {
    if (v.tag == TAG_INT) {
        if (v.i == INT64_MIN) _crush_arith_error("arithmetic overflow");
        return mk_int(-v.i);
    }
    if (v.tag == TAG_FLOAT) return mk_float(-v.f);
    _crush_arith_error("type error: negate on non-numeric operand");
    return mk_null();
}
static Value _not(Value v) { return mk_bool(!_truthy(v)); }

static void _cmp_type_error(void) {
    fprintf(stderr, "crush(aotc): type error: ordered comparison on non-numeric operands\n");
    exit(1);
}

static Value _cmp(Value a, Value b, int op) {
    // op: 0=EQ, 1=NE, 2=LT, 3=LE, 4=GT, 5=GE
    bool r = false;
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        switch (op) {
            case 0: r = a.i == b.i; break; case 1: r = a.i != b.i; break;
            case 2: r = a.i <  b.i; break; case 3: r = a.i <= b.i; break;
            case 4: r = a.i >  b.i; break; case 5: r = a.i >= b.i; break;
        }
    } else if (_is_num(a) && _is_num(b)) {
        double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
        double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
        switch (op) {
            case 0: r = fa == fb; break; case 1: r = fa != fb; break;
            case 2: r = fa <  fb; break; case 3: r = fa <= fb; break;
            case 4: r = fa >  fb; break; case 5: r = fa >= fb; break;
        }
    } else if (a.tag == TAG_STRING && b.tag == TAG_STRING && (op == 0 || op == 1)) {
        int c = strcmp(a.s, b.s);
        r = (op == 0) ? (c == 0) : (c != 0);
    } else if (a.tag == TAG_BOOL && b.tag == TAG_BOOL && (op == 0 || op == 1)) {
        r = (op == 0) ? (a.b == b.b) : (a.b != b.b);
    } else if (a.tag == TAG_NULL && b.tag == TAG_NULL && (op == 0 || op == 1)) {
        r = (op == 0);
    }
    return mk_bool(r);
}

"#);
}

// ── Function emission ───────────────────────────────────────────────────────

#[derive(Clone)]
enum LocalType { Value, F64, I64 }

#[derive(Clone)]
struct LocalMeta {
    c_name: String,
    ty: LocalType,
}

fn emit_c_function(
    out: &mut String,
    name: &str,
    func: &casm::Function,
    _program: &casm::Program,
) {
    let fn_name = sanitize_fn_name(name);
    let n = func.body.len();

    // Discover locals by scanning store/load instructions (func.locals may be empty)
    let local_index = discover_locals(&func.body, &func.params, func.type_hints.as_ref());

    out.push_str(&format!("static Value fn_{fn_name}(void) {{\n"));

    // Locals
    for meta in local_index.values() {
        match meta.ty {
            LocalType::F64 => out.push_str(&format!("    double {} = 0.0;\n", meta.c_name)),
            LocalType::I64 => out.push_str(&format!("    int64_t {} = 0;\n", meta.c_name)),
            LocalType::Value => out.push_str(&format!("    Value {} = mk_null();\n", meta.c_name)),
        }
    }

    out.push_str("    int _pc = 0;\n");
    out.push_str("    while (1) {\n");
    out.push_str("        switch (_pc) {\n");

    for (i, instr) in func.body.iter().enumerate() {
        out.push_str(&format!("            case {i}: {{\n"));
        emit_c_instr(out, instr, i, n, &local_index);
        out.push_str("            }\n");
    }

    out.push_str("            default: return mk_null();\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn sanitize_fn_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn infer_types(body: &[casm::Instruction], explicit_hints: Option<&HashMap<String, String>>) -> HashMap<String, String> {
    let mut inferred: HashMap<String, String> = HashMap::new();
    let mut stack: Vec<String> = Vec::new();

    for instr in body {
        match instr.op.as_str() {
            "push_int" => stack.push("Int".to_string()),
            "push_float" => stack.push("Float".to_string()),
            "push_bool" => stack.push("Bool".to_string()),
            "push_str" => stack.push("Str".to_string()),
            "push_null" => stack.push("Null".to_string()),
            "load" => {
                if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                    if let Some(explicit) = explicit_hints.and_then(|h| h.get(name)) {
                        stack.push(explicit.clone());
                    } else if let Some(inf) = inferred.get(name) {
                        stack.push(inf.clone());
                    } else {
                        stack.push("Any".to_string());
                    }
                } else {
                    stack.push("Any".to_string());
                }
            }
            "store" => {
                let ty = stack.pop().unwrap_or_else(|| "Any".to_string());
                if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                    if let Some(existing) = inferred.get(name) {
                        if existing != &ty && existing != "Any" {
                            // Type conflict, widen to Any (Value)
                            inferred.insert(name.to_string(), "Any".to_string());
                        }
                    } else {
                        inferred.insert(name.to_string(), ty);
                    }
                }
            }
            "add" | "sub" | "mul" | "div" | "mod" => {
                let right = stack.pop().unwrap_or_else(|| "Any".to_string());
                let left = stack.pop().unwrap_or_else(|| "Any".to_string());
                if left == "Float" || right == "Float" {
                    stack.push("Float".to_string());
                } else if left == "Int" && right == "Int" {
                    stack.push("Int".to_string());
                } else {
                    stack.push("Any".to_string());
                }
            }
            "neg" => {
                let v = stack.pop().unwrap_or_else(|| "Any".to_string());
                stack.push(v);
            }
            "eq" | "ne" | "lt" | "le" | "gt" | "ge" | "and" | "or" => {
                stack.pop(); stack.pop();
                stack.push("Bool".to_string());
            }
            "not" => {
                stack.pop();
                stack.push("Bool".to_string());
            }
            "vec_add" | "mat_mul" => {
                stack.pop(); stack.pop();
                stack.push("Array".to_string());
            }
            "vec_dot" => {
                stack.pop(); stack.pop();
                stack.push("Float".to_string());
            }
            "len" => {
                stack.pop();
                stack.push("Int".to_string());
            }
            "math_pow" | "math_sqrt" | "math_abs" | "math_round" | "math_floor" | "math_ceil" => {
                if instr.op.as_str() == "math_pow" { stack.pop(); stack.pop(); } else { stack.pop(); }
                stack.push("Float".to_string());
            }
            "pop" => { stack.pop(); }
            "dup" => {
                if let Some(t) = stack.last().cloned() {
                    stack.push(t);
                }
            }
            "swap" => {
                let a = stack.pop().unwrap_or_else(|| "Any".to_string());
                let b = stack.pop().unwrap_or_else(|| "Any".to_string());
                stack.push(a);
                stack.push(b);
            }
            "jmp" | "jmp_if" | "jmp_if_not" => { stack.clear(); }
            _ => {
                // Unknown ops could modify stack unpredictably, but casm is usually strict.
                // We could clear the stack or push 'Any'.
                // Safe approach: we don't know the exact stack depth effect without a full table.
                // Since this is just local inference, we'll keep it simple.
                // In a real pass, we'd need to simulate all opcodes' stack effects.
            }
        }
    }
    inferred
}

/// Pre-scan instructions to discover local variable names from store/load ops.
fn discover_locals(body: &[casm::Instruction], params: &[String], type_hints: Option<&HashMap<String, String>>) -> HashMap<String, LocalMeta> {
    let mut map = HashMap::new();
    let mut next = 0usize;
    let inferred = infer_types(body, type_hints);

    let mut add_local = |name: &str, map: &mut HashMap<String, LocalMeta>, next: &mut usize| {
        if !map.contains_key(name) {
            let explicit = type_hints.and_then(|h| h.get(name)).map(|s| s.as_str());
            let inf = inferred.get(name).map(|s| s.as_str());
            let ty_str = explicit.unwrap_or_else(|| inf.unwrap_or(""));
            
            let ty = match ty_str {
                // TODO: type inference currently produces wrong results for array/varargs ops.
                // Force Value type until inference handles all opcodes correctly.
                // "Float" | "F64" | "F32" => LocalType::F64,
                // "Int" => LocalType::I64,
                _ => LocalType::Value,
            };
            let prefix = match ty {
                LocalType::F64 => "_lf",
                LocalType::I64 => "_li",
                LocalType::Value => "_lv",
            };
            map.insert(name.to_string(), LocalMeta {
                c_name: format!("{}_{}", prefix, next),
                ty,
            });
            *next += 1;
        }
    };

    for p in params { add_local(p, &mut map, &mut next); }
    for instr in body {
        if matches!(instr.op.as_str(), "store" | "load") {
            if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                add_local(name, &mut map, &mut next);
            }
        }
    }
    map
}

// ── Instruction emission ────────────────────────────────────────────────────

fn emit_c_instr(
    out: &mut String,
    instr: &casm::Instruction,
    this_pc: usize,
    total_instrs: usize,
    locals: &HashMap<String, LocalMeta>,
) {
    let args = &instr.args;
    let next = this_pc + 1;
    let next_pc = if next < total_instrs { next } else { total_instrs };

    match instr.op.as_str() {
        // ── Push ──
        "push_int" => {
            let v = args["value"].as_i64().unwrap_or(0);
            out.push_str(&format!("                _push(mk_int({v}LL)); _pc={next_pc}; break;\n"));
        }
        "push_float" => {
            let v = args["value"].as_f64().unwrap_or(0.0);
            out.push_str(&format!("                _push(mk_float({v})); _pc={next_pc}; break;\n"));
        }
        "push_bool" => {
            let v = args["value"].as_bool().unwrap_or(false);
            out.push_str(&format!("                _push(mk_bool({v})); _pc={next_pc}; break;\n"));
        }
        "push_null" => {
            out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break;\n"));
        }
        "push_str" => {
            let s = args["value"].as_str().unwrap_or("");
            let escaped = s.escape_default().to_string();
            out.push_str(&format!("                _push(mk_string(\"{escaped}\")); _pc={next_pc}; break;\n"));
        }

        // ── Stack ops ──
        "pop"  => { out.push_str(&format!("                _pop(); _pc={next_pc}; break;\n")); }
        "dup"  => { out.push_str(&format!("                _dup(); _pc={next_pc}; break;\n")); }
        "swap" => { out.push_str(&format!("                _swap(); _pc={next_pc}; break;\n")); }

        // ── Locals ──
        "load" => {
            let name = args["name"].as_str().unwrap_or("");
            if let Some(meta) = locals.get(name) {
                match meta.ty {
                    LocalType::F64 => out.push_str(&format!("                _push(mk_float({})); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::I64 => out.push_str(&format!("                _push(mk_int({})); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::Value => out.push_str(&format!("                _push({}); _pc={next_pc}; break;\n", meta.c_name)),
                }
            } else {
                out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break;\n"));
            }
        }
        "store" => {
            let name = args["name"].as_str().unwrap_or("");
            if let Some(meta) = locals.get(name) {
                match meta.ty {
                    LocalType::F64 => out.push_str(&format!("                {} = _to_float(_pop()); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::I64 => out.push_str(&format!("                {} = _to_int(_pop()); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::Value => {
                        // Pin strings that live in _strbuf so they survive subsequent
                        // function calls that reuse the ring buffer.
                        out.push_str(&format!(
                            "                {{ Value __sv = _pop(); if (__sv.tag == TAG_STRING && _str_contains_ptr(__sv.s)) {{ __sv.s = _str_dup(__sv.s); }} {} = __sv; }} _pc={next_pc}; break;\n",
                            meta.c_name
                        ));
                    }
                }
            } else {
                out.push_str(&format!("                _pop(); _pc={next_pc}; break;\n"));
            }
        }

        // ── Arithmetic ──
        "add" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_add(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "sub" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_sub(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "mul" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_mul(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "div" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_div(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "mod" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_mod(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "neg" => { out.push_str(&format!("                {{ Value _v = _pop(); _push(_neg(_v)); }} _pc={next_pc}; break;\n")); }
        "vec_add" => {
            out.push_str(&format!(r#"
                {{
                    Value r = _pop();
                    Value l = _pop();
                    if (l.tag == TAG_ARRAY && r.tag == TAG_ARRAY) {{
                        int arr_id = _alloc_array();
                        if (arr_id >= 0) {{
                            CrushArray* la = &_arrays[l.array_idx];
                            CrushArray* ra = &_arrays[r.array_idx];
                            int len = la->len < ra->len ? la->len : ra->len;
                            _arrays[arr_id].len = len;
                            _Pragma("GCC ivdep")
                            for (int i=0; i<len; i++) {{
                                double vf = _to_float(la->data[i]);
                                double vb = _to_float(ra->data[i]);
                                _arrays[arr_id].data[i] = mk_float(vf + vb);
                            }}
                            _push(mk_array(arr_id));
                        }} else {{
                            _push(mk_null());
                        }}
                    }} else {{
                        _push(mk_null());
                    }}
                    _pc={next_pc}; break;
                }}
"#));
        }
        "vec_dot" => {
            out.push_str(&format!(r#"
                {{
                    Value r = _pop();
                    Value l = _pop();
                    if (l.tag == TAG_ARRAY && r.tag == TAG_ARRAY) {{
                        CrushArray* la = &_arrays[l.array_idx];
                        CrushArray* ra = &_arrays[r.array_idx];
                        int len = la->len < ra->len ? la->len : ra->len;
                        double sum = 0.0;
                        _Pragma("GCC ivdep")
                        for (int i=0; i<len; i++) {{
                            double vf = _to_float(la->data[i]);
                            double vb = _to_float(ra->data[i]);
                            sum += vf * vb;
                        }}
                        _push(mk_float(sum));
                    }} else {{
                        _push(mk_null());
                    }}
                    _pc={next_pc}; break;
                }}
"#));
        }
        "mat_mul" => {
            out.push_str(&format!(r#"
                {{
                    Value r = _pop();
                    Value l = _pop();
                    if (l.tag == TAG_ARRAY && r.tag == TAG_ARRAY) {{
                        CrushArray* la = &_arrays[l.array_idx];
                        CrushArray* ra = &_arrays[r.array_idx];
                        if (la->len == 0 || ra->len == 0) {{
                            int arr_id = _alloc_array();
                            _push(arr_id >= 0 ? mk_array(arr_id) : mk_null());
                        }} else {{
                            int rows_a = la->len;
                            int cols_a = la->data[0].tag == TAG_ARRAY ? _arrays[la->data[0].array_idx].len : 0;
                            int cols_b = ra->data[0].tag == TAG_ARRAY ? _arrays[ra->data[0].array_idx].len : 0;
                            
                            int out_id = _alloc_array();
                            if (out_id >= 0) {{
                                _arrays[out_id].len = rows_a;
                                for (int i=0; i<rows_a; i++) {{
                                    int row_id = _alloc_array();
                                    if (row_id >= 0) {{
                                        _arrays[row_id].len = cols_b;
                                        for (int j=0; j<cols_b; j++) {{
                                            double sum = 0.0;
                                            _Pragma("GCC ivdep")
                                            for (int k=0; k<cols_a; k++) {{
                                                double va = 0.0;
                                                if (la->data[i].tag == TAG_ARRAY) {{
                                                    va = _to_float(_arrays[la->data[i].array_idx].data[k]);
                                                }}
                                                double vb = 0.0;
                                                if (ra->data[k].tag == TAG_ARRAY) {{
                                                    vb = _to_float(_arrays[ra->data[k].array_idx].data[j]);
                                                }}
                                                sum += va * vb;
                                            }}
                                            _arrays[row_id].data[j] = mk_float(sum);
                                        }}
                                        _arrays[out_id].data[i] = mk_array(row_id);
                                    }} else {{
                                        _arrays[out_id].data[i] = mk_null();
                                    }}
                                }}
                                _push(mk_array(out_id));
                            }} else {{
                                _push(mk_null());
                            }}
                        }}
                    }} else {{
                        _push(mk_null());
                    }}
                    _pc={next_pc}; break;
                }}
"#));
        }
        // ── Comparison ──
        "eq" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,0)); }} _pc={next_pc}; break;\n")); }
        "ne" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,1)); }} _pc={next_pc}; break;\n")); }
        "lt" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!_is_num(_a) || !_is_num(_b)) _cmp_type_error(); _push(_cmp(_a,_b,2)); }} _pc={next_pc}; break;\n")); }
        "le" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!_is_num(_a) || !_is_num(_b)) _cmp_type_error(); _push(_cmp(_a,_b,3)); }} _pc={next_pc}; break;\n")); }
        "gt" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!_is_num(_a) || !_is_num(_b)) _cmp_type_error(); _push(_cmp(_a,_b,4)); }} _pc={next_pc}; break;\n")); }
        "ge" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!_is_num(_a) || !_is_num(_b)) _cmp_type_error(); _push(_cmp(_a,_b,5)); }} _pc={next_pc}; break;\n")); }

        // ── Logical ──
        "and" => {
            out.push_str(&format!(
                "                {{ bool _tb = _truthy(_pop()); bool _ta = _truthy(_pop()); _push(mk_bool(_ta && _tb)); }} _pc={next_pc}; break;\n"
            ));
        }
        "or" => {
            out.push_str(&format!(
                "                {{ bool _tb = _truthy(_pop()); bool _ta = _truthy(_pop()); _push(mk_bool(_ta || _tb)); }} _pc={next_pc}; break;\n"
            ));
        }
        "not" => { out.push_str(&format!("                {{ Value _v = _pop(); _push(_not(_v)); }} _pc={next_pc}; break;\n")); }

        // ── Bitwise ops ──
        "bit_and" => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i & _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "bit_or"  => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i | _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "bit_xor" => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i ^ _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "bit_not" => {{ out.push_str(&format!("                {{ Value _v = _pop(); if (_v.tag == TAG_INT) {{ _push(mk_int(~_v.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "shl"     => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i << _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "shr"     => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i >> _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}

        // ── Control flow ──
        "jmp" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!("                _pc = {t}; break;\n"));
            } else {
                out.push_str(&format!("                _pc = {next_pc}; break;\n"));
            }
        }
        "jmp_if" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "                if (_truthy(_peek())) {{ _pop(); _pc = {t}; break; }} else {{ _pop(); _pc = {next_pc}; break; }}\n"
                ));
            } else {
                out.push_str(&format!("                _pop(); _pc = {next_pc}; break;\n"));
            }
        }
        "jmp_if_not" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "                if (!_truthy(_peek())) {{ _pop(); _pc = {t}; break; }} else {{ _pop(); _pc = {next_pc}; break; }}\n"
                ));
            } else {
                out.push_str(&format!("                _pop(); _pc = {next_pc}; break;\n"));
            }
        }
        // ── Async / AI opcodes ──
        // AOT backends can't spawn OS threads or yield at the instruction level;
        // these are stubbed to the minimum safe behavior.
        "spawn" => {
            // Pop function name + argc args (left on stack), push null.
            // AOT can't spawn green threads, but we must keep the stack balanced.
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0);
            out.push_str(&format!("                _pop(); // fn name\n"));
            for _ in 0..argc {
                out.push_str(&format!("                _pop(); // arg\n"));
            }
            out.push_str(&format!("                _push(mk_null());\n"));
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }
        "yield" => {
            // Cooperative yield is a no-op in sequential AOT execution.
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }
        "await" => {
            // Pop handle, push null
            out.push_str(&format!("                _pop(); // handle\n"));
            out.push_str(&format!("                _push(mk_null());\n"));
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }

        // ── AI opcodes ──
        // AOT C can't perform AI queries. The JSON config is in the instruction args,
        // NOT on the stack. Push null (matching scheduler/portable VM behavior).
        "ai_query" | "ai_synthesize" | "ai_agent_delegation" | "ai_semantic_match"
        | "ai_learning_loop" | "ai_context_aware" | "ai_toolchain" => {
            out.push_str(&format!("                _push(mk_null());\n"));
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }

        "ret" | "halt" => {
            out.push_str("                return _pop();\n");
        }

        // ── Calls ──
        "call" => {
            let target = args["function"].as_str().unwrap_or("");
            let fn_name = sanitize_fn_name(target);
            // Args are already on the stack; callee's store param instrs pop them.
            out.push_str(&format!(
                "                {{ Value __r = fn_{fn_name}(); _push(__r); }} _pc={next_pc}; break;\n"
            ));
        }

        // ── Arrays ──
        "new_array" => {
            // Size is a pre-allocation hint ��� elements are pushed separately via
            // subsequent push_int + array_push instructions. Always create empty array.
            out.push_str(&format!("                {{ int __ai = _alloc_array(); _push(__ai >= 0 ? mk_array(__ai) : mk_null()); }} _pc={next_pc}; break;\n"));
        }
        "arr_get" | "index" => {{
            out.push_str(&format!("                {{ Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ _push(__a->data[__wi]); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_set" => {{
            out.push_str(&format!("                {{ Value __val_v = _pop(); Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ __a->data[__wi] = __val_v; }} }} }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_len" | "len" => {{
            out.push_str(&format!("                {{ Value __v = _pop(); if (__v.tag == TAG_ARRAY) {{ int __ai = __v.array_idx; _push(mk_int(__ai >= 0 && __ai < _array_count ? (int64_t)_arrays[__ai].len : 0LL)); }} else if (__v.tag == TAG_STRING) {{ _push(mk_int((int64_t)strlen(__v.s))); }} else {{ _push(mk_int(0LL)); }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_push" | "array_push" => {{
            out.push_str(&format!("                {{ Value __val = _pop(); Value __arr = _pop(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len < ARRAY_DATA_CAP) {{ __a->data[__a->len++] = __val; }} }} }} _push(__arr); }} _pc={next_pc}; break;\n"));
        }}
        "arr_pop" | "array_pop" => {{
            out.push_str(&format!("                {{ Value __arr = _pop(); Value __popped = mk_null(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len > 0) {{ __popped = __a->data[--__a->len]; }} }} }} _push(__arr); _push(__popped); }} _pc={next_pc}; break;\n"));
        }}
        "make_range" => {{
            out.push_str(&format!("                {{ Value __end_v = _pop(); Value __start_v = _pop(); int64_t __start = (__start_v.tag == TAG_INT) ? __start_v.i : 0; int64_t __end = (__end_v.tag == TAG_INT) ? __end_v.i : 0; int __ai = _alloc_array(); if (__ai >= 0) {{ CrushArray* __a = &_arrays[__ai]; int64_t __i = __start; int __n = 0; while (__i < __end && __n < ARRAY_DATA_CAP) {{ __a->data[__n++] = mk_int(__i); __i++; }} __a->len = __n; _push(mk_array(__ai)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}

        // ── Objects ──
        "new_obj" => {{
            out.push_str(&format!("                {{ int __oi = _alloc_object(); _push(__oi >= 0 ? mk_object(__oi) : mk_null()); }} _pc={next_pc}; break;\n"));
        }}
        "get_field" => {{
            let field = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let escaped = field.escape_default().to_string();
            out.push_str(&format!("                {{ Value __obj = _pop(); if (__obj.tag == TAG_OBJECT) {{ int __oi = __obj.obj_idx; if (__oi >= 0 && __oi < _object_count) {{ _push(_obj_get(&_objects[__oi], \"{escaped}\")); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}
        "set_field" => {{
            let field = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let escaped = field.escape_default().to_string();
            out.push_str(&format!("                {{ Value __val = _pop(); Value __obj = _pop(); if (__obj.tag == TAG_OBJECT) {{ int __oi = __obj.obj_idx; if (__oi >= 0 && __oi < _object_count) {{ _obj_set(&_objects[__oi], \"{escaped}\", __val); }} }} }} _pc={next_pc}; break;\n"));
        }}

        // ── Cap calls → inline dispatch ──
        "cap_call" => {
            let cap_name = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
            match cap_name {
                "append" | "push" | "arr.push" | "array.push" => {
                    out.push_str(&format!("                {{ Value __val = _pop(); Value __arr = _pop(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len < ARRAY_DATA_CAP) {{ __a->data[__a->len++] = __val; }} }} }} }} _pc={next_pc}; break; // cap_call append/push\n"));
                }
                "arr_get" => {
                    out.push_str(&format!("                {{ Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ _push(__a->data[__wi]); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break; // cap_call arr_get\n"));
                }
                "arr_set" => {
                    out.push_str(&format!("                {{ Value __val_v = _pop(); Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ __a->data[__wi] = __val_v; }} }} }} }} _pc={next_pc}; break; // cap_call arr_set\n"));
                }
                "make_range" => {
                    // Variadic: 0, 1, or 2 args �� args pushed left-to-right, top of stack = last arg
                    out.push_str(&format!("                {{ int64_t __start = 0, __end = 100; if ({argc} >= 2) {{ Value __ev = _pop(); __end = (__ev.tag == TAG_INT) ? __ev.i : 100; Value __sv = _pop(); __start = (__sv.tag == TAG_INT) ? __sv.i : 0; }} else if ({argc} >= 1) {{ Value __ev = _pop(); __end = (__ev.tag == TAG_INT) ? __ev.i : 100; }} int __ai = _alloc_array(); if (__ai >= 0) {{ CrushArray* __a = &_arrays[__ai]; int64_t __i = __start; int __n = 0; while (__i < __end && __n < ARRAY_DATA_CAP) {{ __a->data[__n++] = mk_int(__i); __i++; }} __a->len = __n; _push(mk_array(__ai)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break; // cap_call make_range\n"));
                }
                "io.print" | "print" => {
                    out.push_str(&format!("                {{ Value __pv = _pop(); switch (__pv.tag) {{ case TAG_INT: printf(\"%ld\\n\", (long)__pv.i); break; case TAG_FLOAT: printf(\"%g\\n\", __pv.f); break; case TAG_BOOL: printf(\"%s\\n\", __pv.b ? \"true\" : \"false\"); break; case TAG_NULL: printf(\"null\\n\"); break; case TAG_STRING: printf(\"%s\\n\", __pv.s); break; default: printf(\"[array#%d]\\n\", __pv.array_idx); break; }} }} _pc={next_pc}; break; // cap_call io.print\n"));
                }
                _ => {
                    if argc > 0 {
                        out.push_str(&format!("                for (int __i=0; __i<{argc}; __i++) _pop();\n"));
                    }
                    out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break; // cap_call '{}' stubbed\n", cap_name.escape_default()));
                }
            }
        }

        // ── String ops ──
        "str_contains" => {{
            out.push_str(&format!("                {{ Value __pat = _pop(); Value __s = _pop(); bool __r = false; if (__s.tag == TAG_STRING && __pat.tag == TAG_STRING) {{ __r = strstr(__s.s, __pat.s) != NULL; }} _push(mk_bool(__r)); }} _pc={next_pc}; break;\n"));
        }}
        "str_starts_with" => {{
            out.push_str(&format!("                {{ Value __pfx = _pop(); Value __s = _pop(); bool __r = false; if (__s.tag == TAG_STRING && __pfx.tag == TAG_STRING) {{ size_t __sl = strlen(__s.s); size_t __pl = strlen(__pfx.s); __r = (__sl >= __pl && strncmp(__s.s, __pfx.s, __pl) == 0); }} _push(mk_bool(__r)); }} _pc={next_pc}; break;\n"));
        }}
        "str_ends_with" => {{
            out.push_str(&format!("                {{ Value __sfx = _pop(); Value __s = _pop(); bool __r = false; if (__s.tag == TAG_STRING && __sfx.tag == TAG_STRING) {{ size_t __sl = strlen(__s.s); size_t __xl = strlen(__sfx.s); __r = (__sl >= __xl && strcmp(__s.s + __sl - __xl, __sfx.s) == 0); }} _push(mk_bool(__r)); }} _pc={next_pc}; break;\n"));
        }}
        "str_to_upper" => {{
            // Use ring-buffer append to avoid overwriting other strings in _strbuf.
            // Source may also be in _strbuf — save/restore to local buffer first.
            out.push_str(&format!("                {{ Value __s = _pop(); if (__s.tag == TAG_STRING) {{ const char* __src = __s.s; int __start = _strbuf_idx; char _sv[STRBUF_SIZE]; if (_str_contains_ptr(__src)) {{ memcpy(_sv, _strbuf, STRBUF_SIZE); __src = _sv + (__src - _strbuf); }} int __i = 0; while (__src[__i] && __start + __i < STRBUF_SIZE-1) {{ _strbuf[__start + __i] = (char)toupper((unsigned char)__src[__i]); __i++; }} _strbuf[__start + __i] = '\\0'; _strbuf_idx = __start + __i + 1; if (_strbuf_idx >= STRBUF_SIZE) _strbuf_idx = 0; _push(mk_string(&_strbuf[__start])); }} else {{ _push(__s); }} }} _pc={next_pc}; break;\n"));
        }}
        "str_to_lower" => {{
            out.push_str(&format!("                {{ Value __s = _pop(); if (__s.tag == TAG_STRING) {{ const char* __src = __s.s; int __start = _strbuf_idx; char _sv[STRBUF_SIZE]; if (_str_contains_ptr(__src)) {{ memcpy(_sv, _strbuf, STRBUF_SIZE); __src = _sv + (__src - _strbuf); }} int __i = 0; while (__src[__i] && __start + __i < STRBUF_SIZE-1) {{ _strbuf[__start + __i] = (char)tolower((unsigned char)__src[__i]); __i++; }} _strbuf[__start + __i] = '\\0'; _strbuf_idx = __start + __i + 1; if (_strbuf_idx >= STRBUF_SIZE) _strbuf_idx = 0; _push(mk_string(&_strbuf[__start])); }} else {{ _push(__s); }} }} _pc={next_pc}; break;\n"));
        }}
        "str_trim" => {{
            out.push_str(&format!("                {{ Value __s = _pop(); if (__s.tag == TAG_STRING) {{ const char* __src = __s.s; const char* __start = __src; while (*__start && isspace((unsigned char)*__start)) __start++; const char* __end = __src + strlen(__src); while (__end > __start && isspace((unsigned char)*(__end-1))) __end--; size_t __len = (size_t)(__end - __start); int __pos = _strbuf_idx; char _sv[STRBUF_SIZE]; if (_str_contains_ptr(__start)) {{ memcpy(_sv, _strbuf, STRBUF_SIZE); __start = _sv + (__start - _strbuf); }} if (__len >= (size_t)(STRBUF_SIZE - __pos)) {{ __pos = 0; }} memcpy(&_strbuf[__pos], __start, __len); _strbuf[__pos + __len] = '\\0'; _strbuf_idx = __pos + (int)__len + 1; if (_strbuf_idx >= STRBUF_SIZE) _strbuf_idx = 0; _push(mk_string(&_strbuf[__pos])); }} else {{ _push(__s); }} }} _pc={next_pc}; break;\n"));
        }}
        // Complex string ops: emit as cap_call stubs (need dynamic allocation)
        "str_split" | "str_replace" | "str_join" => {{
            out.push_str(&format!("                _pop(); _pop(); _push(mk_null()); _pc={next_pc}; break; // str_* stubbed (needs dynamic strings)\n"));
        }}

        // ── Unknown / NOP ──
        _ => {
            out.push_str(&format!("                _pc = {next_pc}; break;\n"));
        }
    }
}

// ── Entry point ─────────────────────────────────────────────────────────────

fn emit_c_entry_point(out: &mut String) {
    out.push_str(r#"
// ── C ABI entry point ────���─────────────────────────────────────────────
// Returns the result of fn_main() serialized as a string.
// CAUTION: returns pointer to static buffer — callers must copy immediately.

__attribute__((visibility("default")))
const char* crush_run(void) {
    _sp = 0;  // reset stack
    _reset_arrays();
    Value result = fn_main();
    static char _buf[512];
    switch (result.tag) {
        case TAG_INT:   snprintf(_buf, sizeof(_buf), "%ld", (long)result.i); break;
        case TAG_FLOAT: {
            double __f = result.f;
            if (isfinite(__f) && __f == (double)(int64_t)__f) {
                snprintf(_buf, sizeof(_buf), "%.1f", __f);
            } else {
                snprintf(_buf, sizeof(_buf), "%.15g", __f);
            }
            break;
        }
        case TAG_BOOL:  snprintf(_buf, sizeof(_buf), "%s", result.b ? "true" : "false"); break;
        case TAG_NULL:  snprintf(_buf, sizeof(_buf), "null"); break;
        case TAG_STRING: snprintf(_buf, sizeof(_buf), "\"%s\"", result.s); break;
        case TAG_ARRAY:  snprintf(_buf, sizeof(_buf), "[array#%d len=%d]", result.array_idx, result.array_idx >= 0 && result.array_idx < _array_count ? _arrays[result.array_idx].len : 0); break;
        case TAG_OBJECT: snprintf(_buf, sizeof(_buf), "[object#%d fields=%d]", result.obj_idx, result.obj_idx >= 0 && result.obj_idx < _object_count ? _objects[result.obj_idx].field_count : 0); break;
        default:         snprintf(_buf, sizeof(_buf), "null"); break;
    }
    return _buf;
}

__attribute__((visibility("default")))
void crush_run_free(const char* s) {
    (void)s; // static buffer, no-op
}
"#);
}
