//! CASM → C source code generator.
//!
//! Transpiles a `casm::Program` into self-contained C99 source with a
//! `switch(pc)` dispatch loop that compilers optimize into jump tables.
//!
//! The generated C defines its own tagged union (`Value`) and stack machine,
//! and exports a `crush_run()` symbol for dlopen-based loading.

use std::collections::HashMap;

/// Transpile a CASM program to C source code.
/// Fails with [`crate::UnsupportedOps`] if any instruction has no C
/// translation.
pub fn gen_c_source(program: &casm::Program) -> Result<String, crate::UnsupportedOps> {
    let mut out = String::new();

    emit_c_header(&mut out);
    emit_c_value(&mut out);
    emit_c_helpers(&mut out);
    emit_c_ai_stub(&mut out);
    emit_c_dom_stub(&mut out);

    // Forward declarations (needed because CASM functions may call each other)
    for (name, _func) in &program.functions {
        let fn_name = sanitize_fn_name(name);
        out.push_str(&format!("static Value fn_{fn_name}(void);\n"));
    }
    out.push_str("\n");

    let mut unsupported = Vec::new();
    for (name, func) in &program.functions {
        emit_c_function(&mut out, name, func, program, &mut unsupported);
    }
    if !unsupported.is_empty() {
        return Err(crate::UnsupportedOps {
            backend: "C",
            ops: unsupported,
        });
    }

    emit_c_entry_point(&mut out);
    Ok(out)
}

// ── Header ──────────────────────────────────────────────────────────────────

fn emit_c_header(out: &mut String) {
    out.push_str(r#"// Generated by crush-aotc --emit c. Do not edit.
// CASM → C transpiled stack machine.
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include <ctype.h>

"#);
}

// ── Tagged Value ────────────────────────────────────────────────────────────

fn emit_c_value(out: &mut String) {
    out.push_str(r#"typedef enum {
    TAG_INT,
    TAG_FLOAT,
    TAG_BOOL,
    TAG_NULL,
    TAG_STRING,
    TAG_ARRAY,
    TAG_OBJECT,
} ValueTag;

typedef struct {
    ValueTag tag;
    union {
        int64_t  i;
        double   f;
        bool     b;
        const char* s;
        int      array_idx;
        int      obj_idx;
    };
} Value;

static inline Value mk_int(int64_t i)   { return (Value){TAG_INT, .i=i}; }
static inline Value mk_float(double f)  { return (Value){TAG_FLOAT, .f=f}; }
static inline Value mk_bool(bool b)     { return (Value){TAG_BOOL, .b=b}; }
static inline Value mk_null(void)       { return (Value){TAG_NULL}; }
static inline Value mk_string(const char* s) { return (Value){TAG_STRING, .s=s}; }
static inline Value mk_array(int idx)   { return (Value){TAG_ARRAY, .array_idx=idx}; }
static inline Value mk_object(int idx)  { return (Value){TAG_OBJECT, .obj_idx=idx}; }

// ── Array pool ───────────────────────────────────────────────────────
// Headers live in a static pool (only the slots a run touches cost memory);
// each array's elements are a heap block that grows on demand and is reused by
// the next run. Arrays aren't reclaimed during a run. (CRUSH-223: the pool used
// to be 64 arrays of a fixed 65,536 slots, and running out pushed null or
// dropped elements without an error.)
#define ARRAY_POOL_MAX (1 << 20)

typedef struct {
    Value* data;
    int    len;
    int    cap;
    bool   alive;   // allocated and not yet collected
    bool   mark;    // reached during the current collection
} CrushArray;

static CrushArray _arrays[ARRAY_POOL_MAX];
static int        _array_count = 0;      // high-water mark of slots ever used
static int*       _array_free = NULL;    // slots the collector freed, reused first
static int        _array_free_count = 0;

static inline void _crush_arith_error(const char *msg);
static size_t _gc_allocated = 0;         // bytes allocated since the last collection

// Never fails: exhausting the pool is a runtime error, not a null array.
static inline int _alloc_array(void) {
    int idx;
    if (_array_free_count > 0) {
        idx = _array_free[--_array_free_count];
    } else {
        if (_array_count >= ARRAY_POOL_MAX) _crush_arith_error("array pool exhausted");
        idx = _array_count++;
    }
    _arrays[idx].len = 0;
    _arrays[idx].alive = true;
    _gc_allocated += sizeof(CrushArray);
    return idx;
}

// Make room for `n` elements.
static void _array_reserve(CrushArray* a, int64_t n) {
    if (n <= a->cap) return;
    if (n > INT32_MAX / 2) _crush_arith_error("array too large");
    int cap = a->cap ? a->cap : 8;
    while (cap < n) cap *= 2;
    Value* data = (Value*)realloc(a->data, (size_t)cap * sizeof(Value));
    if (!data) _crush_arith_error("out of memory");
    _gc_allocated += (size_t)(cap - a->cap) * sizeof(Value);
    a->data = data;
    a->cap = cap;
}

static inline void _array_push(CrushArray* a, Value v) {
    _array_reserve(a, (int64_t)a->len + 1);
    a->data[a->len++] = v;
}

static inline int _wrap_index(int idx, int len) {
    if (idx < 0) idx += len;
    return (idx >= 0 && idx < len) ? idx : -1;
}

// ── Object pool ─────────────────────���────────────────────────────────
// Running out of objects or fields is a runtime error (CRUSH-223), not a null.
#define OBJ_POOL_MAX (1 << 16)
#define OBJ_FIELD_CAP 16

typedef struct {
    const char* key;
    Value val;
} CrushField;

typedef struct {
    CrushField fields[OBJ_FIELD_CAP];
    int   field_count;
    bool  alive;
    bool  mark;
} CrushObject;

static CrushObject _objects[OBJ_POOL_MAX];
static int         _object_count = 0;    // high-water mark
static int*        _object_free = NULL;
static int         _object_free_count = 0;

// Field keys are always string literals from the instruction stream, so the
// collector only has to follow field values.
static inline int _alloc_object(void) {
    int idx;
    if (_object_free_count > 0) {
        idx = _object_free[--_object_free_count];
    } else {
        if (_object_count >= OBJ_POOL_MAX) _crush_arith_error("object pool exhausted");
        idx = _object_count++;
    }
    _objects[idx].field_count = 0;
    _objects[idx].alive = true;
    _gc_allocated += sizeof(CrushObject);
    return idx;
}

static Value _obj_get(CrushObject* obj, const char* key) {
    for (int i = 0; i < obj->field_count; i++) {
        if (strcmp(obj->fields[i].key, key) == 0)
            return obj->fields[i].val;
    }
    return mk_null();
}

static void _obj_set(CrushObject* obj, const char* key, Value val) {
    for (int i = 0; i < obj->field_count; i++) {
        if (strcmp(obj->fields[i].key, key) == 0) {
            obj->fields[i].val = val;
            return;
        }
    }
    if (obj->field_count >= OBJ_FIELD_CAP) _crush_arith_error("object has too many fields (max 16)");
    obj->fields[obj->field_count].key = key;
    obj->fields[obj->field_count].val = val;
    obj->field_count++;
}

// ── AI stub helper (CRUSH-32 follow-up) ─────────────────────────────
// Mirrors the {ok, kind, echo} shape used by `crush_lang_sdk::ai_native` so
// emitted C programs agree with the 5 VM tiers at differential-cmp time.
// Args ride on instruction args (not on the VM stack); `echo` is always an
// empty Array here.
static Value mk_ai_stub(const char* kind) {
    int __oi = _alloc_object();
    if (__oi < 0) return mk_null();
    _obj_set(&_objects[__oi], "ok", mk_bool(true));
    _obj_set(&_objects[__oi], "kind", mk_string(kind));
    int __ai = _alloc_array();
    if (__ai >= 0) {
        _arrays[__ai].len = 0;
        _obj_set(&_objects[__oi], "echo", mk_array(__ai));
    } else {
        _obj_set(&_objects[__oi], "echo", mk_null());
    }
    return mk_object(__oi);
}

// ---- DOM stub helper (CRUSH-33 Commit 2) ----
// Mirror of `mk_ai_stub` above for the DOM opcode family. Mirrors the
// {ok, kind, echo} shape used by `crush_lang_sdk::dom_native` so emitted C
// programs agree with the 5 VM tiers at differential-cmp time. Args ride
// on instruction args (not on the VM stack); echo is always an empty
// Array here.
static Value mk_dom_stub(const char* kind) {
    int __oi = _alloc_object();
    if (__oi < 0) return mk_null();
    _obj_set(&_objects[__oi], "ok", mk_bool(true));
    _obj_set(&_objects[__oi], "kind", mk_string(kind));
    int __ai = _alloc_array();
    if (__ai >= 0) {
        _arrays[__ai].len = 0;
        _obj_set(&_objects[__oi], "echo", mk_array(__ai));
    } else {
        _obj_set(&_objects[__oi], "echo", mk_null());
    }
    return mk_object(__oi);
}


// ── Strings ─────────────────────────────────────────────────────────
// Every string built at run time is its own heap block, kept until the next
// crush_run() frees them all. Strings are immutable, so values can share a
// block. (CRUSH-216: this used to be one 256-byte ring buffer, so a string held
// in a variable was overwritten by later string work and long strings were
// silently truncated.)
static char** _str_blocks = NULL;
static size_t _str_block_count = 0;
static size_t _str_block_cap = 0;
static bool*  _str_marks = NULL;      // parallel to _str_blocks during a collection

static char* _str_new(size_t len) {
    if (_str_block_count == _str_block_cap) {
        size_t cap = _str_block_cap ? _str_block_cap * 2 : 256;
        char** blocks = (char**)realloc(_str_blocks, cap * sizeof(char*));
        if (!blocks) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
        _str_blocks = blocks;
        _str_block_cap = cap;
    }
    char* p = (char*)malloc(len + 1);
    if (!p) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
    p[len] = '\0';
    _str_blocks[_str_block_count++] = p;
    _gc_allocated += len + 1;
    return p;
}

static void _reset_strings(void) {
    for (size_t i = 0; i < _str_block_count; i++) free(_str_blocks[i]);
    _str_block_count = 0;
}

static inline const char* _str_alloc(const char* src) {
    size_t len = strlen(src);
    char* p = _str_new(len);
    memcpy(p, src, len);
    return p;
}

static inline const char* _str_dup(const char* src) {
    return _str_alloc(src);
}

static const char* _str_map_case(const char* src, int upper) {
    size_t len = strlen(src);
    char* p = _str_new(len);
    for (size_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)src[i];
        p[i] = (char)(upper ? toupper(c) : tolower(c));
    }
    return p;
}

static const char* _str_trim(const char* src) {
    const char* start = src;
    while (*start && isspace((unsigned char)*start)) start++;
    const char* end = src + strlen(src);
    while (end > start && isspace((unsigned char)*(end - 1))) end--;
    size_t len = (size_t)(end - start);
    char* p = _str_new(len);
    memcpy(p, start, len);
    return p;
}

// Read one line from stdin. EOF and read errors both produce an empty string;
// a trailing LF or CRLF terminator is removed before the value is copied into
// the generated runtime's string buffer.
static inline const char* io_read_line(void) {
    static char input[4096];
    if (fgets(input, sizeof(input), stdin) == NULL) {
        input[0] = '\0';
    }
    size_t len = strlen(input);
    while (len > 0 && (input[len - 1] == '\n' || input[len - 1] == '\r')) {
        input[--len] = '\0';
    }
    return _str_dup(input);
}

"#);
}

// ── Stack ───────────────────────────────────────────────────────────────────

fn emit_c_helpers(out: &mut String) {
    out.push_str(r#"// ── Stack ──────────────────────────────────────────────────────────
// Grows on demand. (CRUSH-223: a fixed 512 slots silently dropped pushes past
// the end, so deep recursion read null and failed with a bogus type error.)
static Value*  _stack = NULL;
static int     _stack_cap = 0;
static int     _sp = 0;

static void _stack_grow(void) {
    int cap = _stack_cap ? _stack_cap * 2 : 1024;
    Value* stack = (Value*)realloc(_stack, (size_t)cap * sizeof(Value));
    if (!stack) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
    _stack = stack;
    _stack_cap = cap;
}

static void _reset_arrays(void) {
    _array_count = 0; _array_free_count = 0;
    _object_count = 0; _object_free_count = 0;
}

// ── Locals ──────────────────────────────────────────────────────────
// Every function's locals live in one heap stack (not C locals) so the
// collector can see them. A function takes a frame on entry and releases it
// on return; index through `_locals` each time, since it can move.
static Value* _locals = NULL;
static int    _locals_cap = 0;
static int    _lsp = 0;

static int _frame_enter(int n) {
    int base = _lsp;
    if (base + n > _locals_cap) {
        int cap = _locals_cap ? _locals_cap : 1024;
        while (cap < base + n) cap *= 2;
        Value* locals = (Value*)realloc(_locals, (size_t)cap * sizeof(Value));
        if (!locals) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
        _locals = locals;
        _locals_cap = cap;
    }
    for (int i = 0; i < n; i++) _locals[base + i] = mk_null();
    _lsp = base + n;
    return base;
}

// ── Garbage collection ──────────────────────────────────────────────
// Mark-and-sweep, run only at a safepoint: the top of a function's dispatch
// loop, between instructions. There every live value is on the value stack or
// in a locals frame (a call keeps its arguments on the stack and holds nothing
// in C variables), so those two are the whole root set. Allocation only counts
// bytes. CRUSH_GC_STRESS=1 collects at every safepoint, for tests.
static size_t _gc_threshold = 1 << 20;
static bool   _gc_stress = false;
static Value* _gc_work = NULL;
static int    _gc_work_len = 0, _gc_work_cap = 0;

static void _gc_push(Value v) {
    if (v.tag != TAG_STRING && v.tag != TAG_ARRAY && v.tag != TAG_OBJECT) return;
    if (_gc_work_len == _gc_work_cap) {
        int cap = _gc_work_cap ? _gc_work_cap * 2 : 1024;
        Value* work = (Value*)realloc(_gc_work, (size_t)cap * sizeof(Value));
        if (!work) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
        _gc_work = work;
        _gc_work_cap = cap;
    }
    _gc_work[_gc_work_len++] = v;
}

static int _gc_ptr_cmp(const void* a, const void* b) {
    uintptr_t x = (uintptr_t)*(char* const*)a, y = (uintptr_t)*(char* const*)b;
    return x < y ? -1 : x > y;
}

// A string is a heap block when its pointer is in the (sorted) registry;
// anything else is a literal from the instruction stream.
static void _gc_mark_string(const char* s) {
    size_t lo = 0, hi = _str_block_count;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if ((uintptr_t)_str_blocks[mid] < (uintptr_t)s) lo = mid + 1; else hi = mid;
    }
    if (lo < _str_block_count && _str_blocks[lo] == s) _str_marks[lo] = true;
}

static void _gc_collect(void) {
    qsort(_str_blocks, _str_block_count, sizeof(char*), _gc_ptr_cmp);
    _str_marks = (bool*)realloc(_str_marks, (_str_block_count ? _str_block_count : 1) * sizeof(bool));
    if (!_str_marks) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
    memset(_str_marks, 0, _str_block_count * sizeof(bool));
    for (int i = 0; i < _array_count; i++) _arrays[i].mark = false;
    for (int i = 0; i < _object_count; i++) _objects[i].mark = false;

    _gc_work_len = 0;
    for (int i = 0; i < _sp; i++) _gc_push(_stack[i]);
    for (int i = 0; i < _lsp; i++) _gc_push(_locals[i]);
    while (_gc_work_len > 0) {
        Value v = _gc_work[--_gc_work_len];
        if (v.tag == TAG_STRING) {
            _gc_mark_string(v.s);
        } else if (v.tag == TAG_ARRAY && v.array_idx >= 0 && v.array_idx < _array_count) {
            CrushArray* a = &_arrays[v.array_idx];
            if (a->mark) continue;
            a->mark = true;
            for (int i = 0; i < a->len; i++) _gc_push(a->data[i]);
        } else if (v.tag == TAG_OBJECT && v.obj_idx >= 0 && v.obj_idx < _object_count) {
            CrushObject* o = &_objects[v.obj_idx];
            if (o->mark) continue;
            o->mark = true;
            for (int i = 0; i < o->field_count; i++) _gc_push(o->fields[i].val);
        }
    }

    size_t live = 0, kept = 0;
    for (size_t i = 0; i < _str_block_count; i++) {
        if (_str_marks[i]) { live += strlen(_str_blocks[i]) + 1; _str_blocks[kept++] = _str_blocks[i]; }
        else free(_str_blocks[i]);
    }
    _str_block_count = kept;

    _array_free = (int*)realloc(_array_free, (_array_count ? _array_count : 1) * sizeof(int));
    _array_free_count = 0;
    for (int i = 0; i < _array_count; i++) {
        CrushArray* a = &_arrays[i];
        if (a->alive && !a->mark) {
            a->alive = false;
            a->len = 0;
            // Keep small buffers for reuse; give big ones back.
            if (a->cap > 64) { free(a->data); a->data = NULL; a->cap = 0; }
        }
        if (a->alive) live += sizeof(CrushArray) + (size_t)a->cap * sizeof(Value);
        else _array_free[_array_free_count++] = i;
    }
    _object_free = (int*)realloc(_object_free, (_object_count ? _object_count : 1) * sizeof(int));
    _object_free_count = 0;
    for (int i = 0; i < _object_count; i++) {
        CrushObject* o = &_objects[i];
        if (o->alive && !o->mark) o->alive = false;
        if (o->alive) live += sizeof(CrushObject);
        else _object_free[_object_free_count++] = i;
    }

    _gc_allocated = 0;
    _gc_threshold = live * 2 > ((size_t)1 << 20) ? live * 2 : ((size_t)1 << 20);
}

static inline void _gc_safepoint(void) {
    if (_gc_stress || _gc_allocated >= _gc_threshold) _gc_collect();
}

static inline void  _push(Value v) { if (_sp == _stack_cap) _stack_grow(); _stack[_sp++] = v; }
static inline Value _pop(void)     { return _sp > 0 ? _stack[--_sp] : mk_null(); }
static inline Value _peek(void)    { return _sp > 0 ? _stack[_sp-1] : mk_null(); }
static inline void  _dup(void)     { if (_sp > 0) _push(_stack[_sp-1]); }
static inline void  _swap(void)    { if (_sp >= 2) { Value t=_stack[_sp-1]; _stack[_sp-1]=_stack[_sp-2]; _stack[_sp-2]=t; } }

static inline double _to_float(Value v) { return (v.tag == TAG_FLOAT) ? v.f : ((v.tag == TAG_INT) ? (double)v.i : 0.0); }
static inline int64_t _to_int(Value v) { return (v.tag == TAG_INT) ? v.i : ((v.tag == TAG_FLOAT) ? (int64_t)v.f : 0); }

// ── Helpers ──────────────────────────────────────────────────────────────
static inline bool _truthy(Value v) {
    switch (v.tag) {
        case TAG_BOOL: return v.b;
        case TAG_INT:  return v.i != 0;
        case TAG_FLOAT: return v.f != 0.0;
        case TAG_NULL: return false;
        // Canonical rule (CRUSH-134): "" and empty collections are falsy.
        case TAG_STRING: return v.s != NULL && v.s[0] != '\0';
        case TAG_ARRAY: return _arrays[v.array_idx].len != 0;
        case TAG_OBJECT: return _objects[v.obj_idx].field_count != 0;
        default:       return true;
    }
}

static inline bool _is_num(Value v) { return v.tag == TAG_INT || v.tag == TAG_FLOAT; }

// ── Value text (print, string concatenation, crush_run's result) ─────────
// Large enough for any double written without an exponent (~330 chars).
#define TEXTBUF_SIZE 512

// A float the way the VM prints it (Rust `f64` Display, crush-vm io_print.rs):
// the shortest digits that read back as the same double, never an exponent,
// and `.0` on finite whole numbers. `NaN`, `inf`, `-inf` as Rust spells them.
static const char* _float_text(double f, char* buf) {
    if (isnan(f)) return "NaN";
    if (isinf(f)) return f > 0 ? "inf" : "-inf";
    if (f == trunc(f)) { snprintf(buf, TEXTBUF_SIZE, "%.1f", f); return buf; }
    char sci[40];
    for (int prec = 0; prec < 17; prec++) {
        snprintf(sci, sizeof(sci), "%.*e", prec, f);
        if (strtod(sci, NULL) == f) break;
    }
    // sci is "[-]d[.ddd]e[+-]xx": split into digits and a decimal exponent.
    const char* p = sci;
    char* out = buf;
    if (*p == '-') { *out++ = '-'; p++; }
    char digits[24]; int nd = 0;
    while (*p && *p != 'e') { if (*p != '.') digits[nd++] = *p; p++; }
    int exp10 = atoi(p + 1);   // value = d.ddd × 10^exp10
    while (nd > 1 && digits[nd - 1] == '0') nd--;
    if (exp10 < 0) {
        *out++ = '0'; *out++ = '.';
        for (int i = -1; i > exp10; i--) *out++ = '0';
        for (int i = 0; i < nd; i++) *out++ = digits[i];
    } else {
        // Not a whole number, so the digits run past the decimal point.
        for (int i = 0; i <= exp10; i++) *out++ = i < nd ? digits[i] : '0';
        *out++ = '.';
        for (int i = exp10 + 1; i < nd; i++) *out++ = digits[i];
    }
    *out = '\0';
    return buf;
}

// Render a Value to text. Numbers are written into `buf` (TEXTBUF_SIZE bytes);
// the result is `buf`, a string constant, or `v.s`.
static inline const char* _to_text_buf(Value v, char* buf) {
    switch (v.tag) {
        case TAG_INT:   snprintf(buf, TEXTBUF_SIZE, "%ld", (long)v.i); return buf;
        case TAG_FLOAT: return _float_text(v.f, buf);
        case TAG_BOOL:  return v.b ? "true" : "false";
        case TAG_NULL:  return "null";
        case TAG_STRING: return v.s;
        default:        return "[opaque]";
    }
}

static inline void _crush_arith_error(const char *msg) {
    fprintf(stderr, "crush(aotc): %s\n", msg);
    exit(1);
}

static const char* _conv_chr(int64_t codepoint) {
    static char buffers[16][5];
    static int slot = 0;
    uint32_t cp;
    if (codepoint < 0 || codepoint > 0x10FFFF ||
        (codepoint >= 0xD800 && codepoint <= 0xDFFF)) {
        _crush_arith_error("conv.chr: invalid Unicode codepoint");
    }
    cp = (uint32_t)codepoint;
    char* out = buffers[slot++ % 16];
    if (cp <= 0x7F) { out[0] = (char)cp; out[1] = '\0'; }
    else if (cp <= 0x7FF) {
        out[0] = (char)(0xC0 | (cp >> 6)); out[1] = (char)(0x80 | (cp & 0x3F)); out[2] = '\0';
    } else if (cp <= 0xFFFF) {
        out[0] = (char)(0xE0 | (cp >> 12)); out[1] = (char)(0x80 | ((cp >> 6) & 0x3F));
        out[2] = (char)(0x80 | (cp & 0x3F)); out[3] = '\0';
    } else {
        out[0] = (char)(0xF0 | (cp >> 18)); out[1] = (char)(0x80 | ((cp >> 12) & 0x3F));
        out[2] = (char)(0x80 | ((cp >> 6) & 0x3F)); out[3] = (char)(0x80 | (cp & 0x3F)); out[4] = '\0';
    }
    return _str_alloc(out);   // the 16 rotating slots aren't durable once stored
}

static int64_t _conv_ord(const char* s) {
    const unsigned char* p = (const unsigned char*)s;
    uint32_t cp; size_t width;
    if (!p[0]) _crush_arith_error("conv.ord: expected one Unicode character");
    if (p[0] < 0x80) { cp = p[0]; width = 1; }
    else if (p[0] >= 0xC2 && p[0] <= 0xDF) { cp = p[0] & 0x1F; width = 2; }
    else if (p[0] >= 0xE0 && p[0] <= 0xEF) { cp = p[0] & 0x0F; width = 3; }
    else if (p[0] >= 0xF0 && p[0] <= 0xF4) { cp = p[0] & 0x07; width = 4; }
    else _crush_arith_error("conv.ord: invalid UTF-8 character");
    for (size_t i = 1; i < width; i++) {
        if ((p[i] & 0xC0) != 0x80) _crush_arith_error("conv.ord: invalid UTF-8 character");
        cp = (cp << 6) | (p[i] & 0x3F);
    }
    if ((width == 2 && cp < 0x80) || (width == 3 && cp < 0x800) ||
        (width == 4 && cp < 0x10000) || cp > 0x10FFFF ||
        (cp >= 0xD800 && cp <= 0xDFFF) || p[width] != '\0') {
        _crush_arith_error("conv.ord: expected one Unicode character");
    }
    return (int64_t)cp;
}

static Value _add(Value a, Value b) {
    // String concatenation when either operand is a string
    if (a.tag == TAG_STRING || b.tag == TAG_STRING) {
        char _ta[TEXTBUF_SIZE], _tb[TEXTBUF_SIZE];
        const char* sa = _to_text_buf(a, _ta);
        const char* sb = _to_text_buf(b, _tb);
        size_t la = strlen(sa), lb = strlen(sb);
        char* buf = _str_new(la + lb);
        memcpy(buf, sa, la);
        memcpy(buf + la, sb, lb);
        return mk_string(buf);
    }
    if (a.tag == TAG_ARRAY && b.tag == TAG_ARRAY) {
        // Array concatenation: a new array, neither operand changes (#75, CRUSH-135).
        int id = _alloc_array();
        CrushArray* la = &_arrays[a.array_idx];
        CrushArray* ra = &_arrays[b.array_idx];
        _array_reserve(&_arrays[id], (int64_t)la->len + ra->len);
        // An empty array may have no data block; memcpy with NULL is undefined even for 0 bytes.
        if (la->len > 0) memcpy(_arrays[id].data, la->data, sizeof(Value) * (size_t)la->len);
        if (ra->len > 0) memcpy(_arrays[id].data + la->len, ra->data, sizeof(Value) * (size_t)ra->len);
        _arrays[id].len = la->len + ra->len;
        return mk_array(id);
    }
    if (!_is_num(a) || !_is_num(b)) _crush_arith_error("type error: + on non-numeric operands");
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        int64_t out;
        if (__builtin_add_overflow(a.i, b.i, &out)) _crush_arith_error("arithmetic overflow");
        return mk_int(out);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa + fb);
}
static Value _sub(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        int64_t out;
        if (__builtin_sub_overflow(a.i, b.i, &out)) _crush_arith_error("arithmetic overflow");
        return mk_int(out);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa - fb);
}
static Value _mul(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        int64_t out;
        if (__builtin_mul_overflow(a.i, b.i, &out)) _crush_arith_error("arithmetic overflow");
        return mk_int(out);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa * fb);
}
static Value _div(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        if (b.i == 0) _crush_arith_error("division by zero");
        // INT64_MIN / -1 overflows (SIGFPE on x86); report it like the Rust backend.
        if (a.i == INT64_MIN && b.i == -1) _crush_arith_error("arithmetic overflow");
        return mk_int(a.i / b.i);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    if (fb == 0.0) _crush_arith_error("division by zero");
    return mk_float(fa / fb);
}
static Value _mod(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        if (b.i == 0) _crush_arith_error("division by zero");
        if (a.i == INT64_MIN && b.i == -1) _crush_arith_error("arithmetic overflow");
        return mk_int(a.i % b.i);
    }
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    if (fb == 0.0) _crush_arith_error("division by zero");
    return mk_float(fmod(fa, fb));
}
static Value _neg(Value v) {
    if (v.tag == TAG_INT) {
        if (v.i == INT64_MIN) _crush_arith_error("arithmetic overflow");
        return mk_int(-v.i);
    }
    if (v.tag == TAG_FLOAT) return mk_float(-v.f);
    _crush_arith_error("type error: negate on non-numeric operand");
    return mk_null();
}
static Value _not(Value v) { return mk_bool(!_truthy(v)); }

static void _cmp_type_error(void) {
    fprintf(stderr, "crush(aotc): type error: ordered comparison on non-numeric operands\n");
    exit(1);
}

static Value _cmp(Value a, Value b, int op) {
    // op: 0=EQ, 1=NE, 2=LT, 3=LE, 4=GT, 5=GE
    bool r = false;
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        switch (op) {
            case 0: r = a.i == b.i; break; case 1: r = a.i != b.i; break;
            case 2: r = a.i <  b.i; break; case 3: r = a.i <= b.i; break;
            case 4: r = a.i >  b.i; break; case 5: r = a.i >= b.i; break;
        }
    } else if (_is_num(a) && _is_num(b)) {
        double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
        double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
        switch (op) {
            case 0: r = fa == fb; break; case 1: r = fa != fb; break;
            case 2: r = fa <  fb; break; case 3: r = fa <= fb; break;
            case 4: r = fa >  fb; break; case 5: r = fa >= fb; break;
        }
    } else if (a.tag == TAG_STRING && b.tag == TAG_STRING) {
        /* strcmp compares as unsigned char: UTF-8 byte order = code point
           order, matching every other backend (CRUSH-136). */
        int c = strcmp(a.s, b.s);
        switch (op) {
            case 0: r = c == 0; break; case 1: r = c != 0; break;
            case 2: r = c <  0; break; case 3: r = c <= 0; break;
            case 4: r = c >  0; break; case 5: r = c >= 0; break;
        }
    } else if (a.tag == TAG_BOOL && b.tag == TAG_BOOL && (op == 0 || op == 1)) {
        r = (op == 0) ? (a.b == b.b) : (a.b != b.b);
    } else if (a.tag == TAG_NULL && b.tag == TAG_NULL && (op == 0 || op == 1)) {
        r = (op == 0);
    }
    return mk_bool(r);
}

"#);
}

// ── Function emission ───────────────────────────────────────────────────────

#[derive(Clone)]
enum LocalType { Value, F64, I64 }

#[derive(Clone)]
struct LocalMeta {
    c_name: String,
    ty: LocalType,
}

fn emit_c_function(
    out: &mut String,
    name: &str,
    func: &casm::Function,
    _program: &casm::Program,
    unsupported: &mut Vec<String>,
) {
    let fn_name = sanitize_fn_name(name);
    let n = func.body.len();

    // Discover locals by scanning store/load instructions (func.locals may be empty)
    let local_index = discover_locals(&func.body, &func.params, func.type_hints.as_ref());

    out.push_str(&format!("static Value fn_{fn_name}(void) {{\n"));

    // Locals: `Value` locals are a frame on the collector-visible `_locals`
    // stack (see `discover_locals`); typed ones would stay C variables.
    out.push_str(&format!("    int __lb = _frame_enter({});\n", local_index.len()));
    for meta in local_index.values() {
        match meta.ty {
            LocalType::F64 => out.push_str(&format!("    double {} = 0.0;\n", meta.c_name)),
            LocalType::I64 => out.push_str(&format!("    int64_t {} = 0;\n", meta.c_name)),
            LocalType::Value => {}
        }
    }

    out.push_str("    int _pc = 0;\n");
    out.push_str("    while (1) {\n");
    out.push_str("        _gc_safepoint();\n");
    out.push_str("        switch (_pc) {\n");

    for (i, instr) in func.body.iter().enumerate() {
        out.push_str(&format!("            case {i}: {{\n"));
        if let Some(op) = emit_c_instr(out, instr, i, n, &local_index) {
            unsupported.push(format!("{op} (fn {name}, instruction {i})"));
        }
        out.push_str("            }\n");
    }

    out.push_str("            default: _lsp = __lb; return mk_null();\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

/// C identifier body for a Crush function (emitted as `fn_<this>`); same scheme as
/// the Rust backend.
fn sanitize_fn_name(name: &str) -> String {
    crate::names::mangle(name)
}

fn infer_types(body: &[casm::Instruction], explicit_hints: Option<&HashMap<String, String>>) -> HashMap<String, String> {
    let mut inferred: HashMap<String, String> = HashMap::new();
    let mut stack: Vec<String> = Vec::new();

    for instr in body {
        match instr.op.as_str() {
            "push_int" => stack.push("Int".to_string()),
            "push_float" => stack.push("Float".to_string()),
            "push_bool" => stack.push("Bool".to_string()),
            "push_str" => stack.push("Str".to_string()),
            "push_null" => stack.push("Null".to_string()),
            "load" => {
                if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                    if let Some(explicit) = explicit_hints.and_then(|h| h.get(name)) {
                        stack.push(explicit.clone());
                    } else if let Some(inf) = inferred.get(name) {
                        stack.push(inf.clone());
                    } else {
                        stack.push("Any".to_string());
                    }
                } else {
                    stack.push("Any".to_string());
                }
            }
            "store" => {
                let ty = stack.pop().unwrap_or_else(|| "Any".to_string());
                if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                    if let Some(existing) = inferred.get(name) {
                        if existing != &ty && existing != "Any" {
                            // Type conflict, widen to Any (Value)
                            inferred.insert(name.to_string(), "Any".to_string());
                        }
                    } else {
                        inferred.insert(name.to_string(), ty);
                    }
                }
            }
            "add" | "sub" | "mul" | "div" | "mod" => {
                let right = stack.pop().unwrap_or_else(|| "Any".to_string());
                let left = stack.pop().unwrap_or_else(|| "Any".to_string());
                if left == "Float" || right == "Float" {
                    stack.push("Float".to_string());
                } else if left == "Int" && right == "Int" {
                    stack.push("Int".to_string());
                } else {
                    stack.push("Any".to_string());
                }
            }
            "neg" => {
                let v = stack.pop().unwrap_or_else(|| "Any".to_string());
                stack.push(v);
            }
            "eq" | "ne" | "lt" | "le" | "gt" | "ge" | "and" | "or" => {
                stack.pop(); stack.pop();
                stack.push("Bool".to_string());
            }
            "not" => {
                stack.pop();
                stack.push("Bool".to_string());
            }
            "vec_add" | "mat_mul" => {
                stack.pop(); stack.pop();
                stack.push("Array".to_string());
            }
            "vec_dot" => {
                stack.pop(); stack.pop();
                stack.push("Float".to_string());
            }
            "len" => {
                stack.pop();
                stack.push("Int".to_string());
            }
            "math_pow" | "math_sqrt" | "math_abs" | "math_round" | "math_floor" | "math_ceil" => {
                if instr.op.as_str() == "math_pow" { stack.pop(); stack.pop(); } else { stack.pop(); }
                stack.push("Float".to_string());
            }
            "pop" => { stack.pop(); }
            "dup" => {
                if let Some(t) = stack.last().cloned() {
                    stack.push(t);
                }
            }
            "swap" => {
                let a = stack.pop().unwrap_or_else(|| "Any".to_string());
                let b = stack.pop().unwrap_or_else(|| "Any".to_string());
                stack.push(a);
                stack.push(b);
            }
            "jmp" | "jmp_if" | "jmp_if_not" => { stack.clear(); }
            _ => {
                // Unknown ops could modify stack unpredictably, but casm is usually strict.
                // We could clear the stack or push 'Any'.
                // Safe approach: we don't know the exact stack depth effect without a full table.
                // Since this is just local inference, we'll keep it simple.
                // In a real pass, we'd need to simulate all opcodes' stack effects.
            }
        }
    }
    inferred
}

/// Pre-scan instructions to discover local variable names from store/load ops.
fn discover_locals(body: &[casm::Instruction], params: &[String], type_hints: Option<&HashMap<String, String>>) -> HashMap<String, LocalMeta> {
    let mut map = HashMap::new();
    let mut next = 0usize;
    let inferred = infer_types(body, type_hints);

    let mut add_local = |name: &str, map: &mut HashMap<String, LocalMeta>, next: &mut usize| {
        if !map.contains_key(name) {
            let explicit = type_hints.and_then(|h| h.get(name)).map(|s| s.as_str());
            let inf = inferred.get(name).map(|s| s.as_str());
            let ty_str = explicit.unwrap_or_else(|| inf.unwrap_or(""));
            
            let ty = match ty_str {
                // TODO: type inference currently produces wrong results for array/varargs ops.
                // Force Value type until inference handles all opcodes correctly.
                // "Float" | "F64" | "F32" => LocalType::F64,
                // "Int" => LocalType::I64,
                _ => LocalType::Value,
            };
            let prefix = match ty {
                LocalType::F64 => "_lf",
                LocalType::I64 => "_li",
                LocalType::Value => "_lv",
            };
            let c_name = match ty {
                LocalType::Value => format!("_locals[__lb + {next}]"),
                _ => format!("{}_{}", prefix, next),
            };
            map.insert(name.to_string(), LocalMeta {
                c_name,
                ty,
            });
            *next += 1;
        }
    };

    for p in params { add_local(p, &mut map, &mut next); }
    for instr in body {
        if matches!(instr.op.as_str(), "store" | "load") {
            if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                add_local(name, &mut map, &mut next);
            }
        }
    }
    map
}

// ── Instruction emission ────────────────────────────────────────────────────

/// Emits one instruction; returns a description of it if it has no C
/// translation.
fn emit_c_instr(
    out: &mut String,
    instr: &casm::Instruction,
    this_pc: usize,
    total_instrs: usize,
    locals: &HashMap<String, LocalMeta>,
) -> Option<String> {
    let mut unsupported = None;
    let args = &instr.args;
    let next = this_pc + 1;
    let next_pc = if next < total_instrs { next } else { total_instrs };

    match instr.op.as_str() {
        // ── Push ──
        "push_int" => {
            let v = args["value"].as_i64().unwrap_or(0);
            out.push_str(&format!("                _push(mk_int({v}LL)); _pc={next_pc}; break;\n"));
        }
        "push_float" => {
            let v = args["value"].as_f64().unwrap_or(0.0);
            out.push_str(&format!("                _push(mk_float({})); _pc={next_pc}; break;\n", c_double_literal(v)));
        }
        "push_bool" => {
            let v = args["value"].as_bool().unwrap_or(false);
            out.push_str(&format!("                _push(mk_bool({v})); _pc={next_pc}; break;\n"));
        }
        "push_null" => {
            out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break;\n"));
        }
        "push_str" => {
            let s = args["value"].as_str().unwrap_or("");
            let escaped = s.escape_default().to_string();
            out.push_str(&format!("                _push(mk_string(\"{escaped}\")); _pc={next_pc}; break;\n"));
        }

        // ── Stack ops ──
        "pop"  => { out.push_str(&format!("                _pop(); _pc={next_pc}; break;\n")); }
        "dup"  => { out.push_str(&format!("                _dup(); _pc={next_pc}; break;\n")); }
        "swap" => { out.push_str(&format!("                _swap(); _pc={next_pc}; break;\n")); }

        // ── Locals ──
        "load" => {
            let name = args["name"].as_str().unwrap_or("");
            if let Some(meta) = locals.get(name) {
                match meta.ty {
                    LocalType::F64 => out.push_str(&format!("                _push(mk_float({})); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::I64 => out.push_str(&format!("                _push(mk_int({})); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::Value => out.push_str(&format!("                _push({}); _pc={next_pc}; break;\n", meta.c_name)),
                }
            } else {
                out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break;\n"));
            }
        }
        "store" => {
            let name = args["name"].as_str().unwrap_or("");
            if let Some(meta) = locals.get(name) {
                match meta.ty {
                    LocalType::F64 => out.push_str(&format!("                {} = _to_float(_pop()); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::I64 => out.push_str(&format!("                {} = _to_int(_pop()); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::Value => {
                        out.push_str(&format!("                {} = _pop(); _pc={next_pc}; break;\n", meta.c_name));
                    }
                }
            } else {
                out.push_str(&format!("                _pop(); _pc={next_pc}; break;\n"));
            }
        }

        // ── Arithmetic ──
        "add" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_add(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "sub" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_sub(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "mul" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_mul(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "div" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_div(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "mod" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_mod(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "neg" => { out.push_str(&format!("                {{ Value _v = _pop(); _push(_neg(_v)); }} _pc={next_pc}; break;\n")); }
        "vec_add" => {
            out.push_str(&format!(r#"
                {{
                    Value r = _pop();
                    Value l = _pop();
                    if (l.tag == TAG_ARRAY && r.tag == TAG_ARRAY) {{
                        int arr_id = _alloc_array();
                        if (arr_id >= 0) {{
                            CrushArray* la = &_arrays[l.array_idx];
                            CrushArray* ra = &_arrays[r.array_idx];
                            int len = la->len < ra->len ? la->len : ra->len;
                            _array_reserve(&_arrays[arr_id], len);
                            _arrays[arr_id].len = len;
                            _Pragma("GCC ivdep")
                            for (int i=0; i<len; i++) {{
                                double vf = _to_float(la->data[i]);
                                double vb = _to_float(ra->data[i]);
                                _arrays[arr_id].data[i] = mk_float(vf + vb);
                            }}
                            _push(mk_array(arr_id));
                        }} else {{
                            _push(mk_null());
                        }}
                    }} else {{
                        _push(mk_null());
                    }}
                    _pc={next_pc}; break;
                }}
"#));
        }
        "vec_dot" => {
            out.push_str(&format!(r#"
                {{
                    Value r = _pop();
                    Value l = _pop();
                    if (l.tag == TAG_ARRAY && r.tag == TAG_ARRAY) {{
                        CrushArray* la = &_arrays[l.array_idx];
                        CrushArray* ra = &_arrays[r.array_idx];
                        int len = la->len < ra->len ? la->len : ra->len;
                        double sum = 0.0;
                        _Pragma("GCC ivdep")
                        for (int i=0; i<len; i++) {{
                            double vf = _to_float(la->data[i]);
                            double vb = _to_float(ra->data[i]);
                            sum += vf * vb;
                        }}
                        _push(mk_float(sum));
                    }} else {{
                        _push(mk_null());
                    }}
                    _pc={next_pc}; break;
                }}
"#));
        }
        "mat_mul" => {
            out.push_str(&format!(r#"
                {{
                    Value r = _pop();
                    Value l = _pop();
                    if (l.tag == TAG_ARRAY && r.tag == TAG_ARRAY) {{
                        CrushArray* la = &_arrays[l.array_idx];
                        CrushArray* ra = &_arrays[r.array_idx];
                        if (la->len == 0 || ra->len == 0) {{
                            int arr_id = _alloc_array();
                            _push(arr_id >= 0 ? mk_array(arr_id) : mk_null());
                        }} else {{
                            // Every row of l must be an array of cols_a values, r must have
                            // cols_a rows of cols_b values. Array data is sized to its length,
                            // so a ragged or mismatched input would read past the block.
                            int rows_a = la->len;
                            int cols_a = la->data[0].tag == TAG_ARRAY ? _arrays[la->data[0].array_idx].len : -1;
                            int cols_b = ra->data[0].tag == TAG_ARRAY ? _arrays[ra->data[0].array_idx].len : -1;
                            if (cols_a < 0 || cols_b < 0 || ra->len != cols_a) _crush_arith_error("mat_mul: shape mismatch");
                            for (int i=0; i<rows_a; i++) {{
                                if (la->data[i].tag != TAG_ARRAY || _arrays[la->data[i].array_idx].len != cols_a) _crush_arith_error("mat_mul: shape mismatch");
                            }}
                            for (int k=0; k<cols_a; k++) {{
                                if (ra->data[k].tag != TAG_ARRAY || _arrays[ra->data[k].array_idx].len != cols_b) _crush_arith_error("mat_mul: shape mismatch");
                            }}

                            int out_id = _alloc_array();
                            if (out_id >= 0) {{
                                _array_reserve(&_arrays[out_id], rows_a);
                                _arrays[out_id].len = rows_a;
                                for (int i=0; i<rows_a; i++) {{
                                    int row_id = _alloc_array();
                                    if (row_id >= 0) {{
                                        _array_reserve(&_arrays[row_id], cols_b);
                                        _arrays[row_id].len = cols_b;
                                        for (int j=0; j<cols_b; j++) {{
                                            double sum = 0.0;
                                            _Pragma("GCC ivdep")
                                            for (int k=0; k<cols_a; k++) {{
                                                double va = 0.0;
                                                if (la->data[i].tag == TAG_ARRAY) {{
                                                    va = _to_float(_arrays[la->data[i].array_idx].data[k]);
                                                }}
                                                double vb = 0.0;
                                                if (ra->data[k].tag == TAG_ARRAY) {{
                                                    vb = _to_float(_arrays[ra->data[k].array_idx].data[j]);
                                                }}
                                                sum += va * vb;
                                            }}
                                            _arrays[row_id].data[j] = mk_float(sum);
                                        }}
                                        _arrays[out_id].data[i] = mk_array(row_id);
                                    }} else {{
                                        _arrays[out_id].data[i] = mk_null();
                                    }}
                                }}
                                _push(mk_array(out_id));
                            }} else {{
                                _push(mk_null());
                            }}
                        }}
                    }} else {{
                        _push(mk_null());
                    }}
                    _pc={next_pc}; break;
                }}
"#));
        }
        // ── Comparison ──
        "eq" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,0)); }} _pc={next_pc}; break;\n")); }
        "ne" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,1)); }} _pc={next_pc}; break;\n")); }
        "lt" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!(_is_num(_a) && _is_num(_b)) && !(_a.tag == TAG_STRING && _b.tag == TAG_STRING)) _cmp_type_error(); _push(_cmp(_a,_b,2)); }} _pc={next_pc}; break;\n")); }
        "le" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!(_is_num(_a) && _is_num(_b)) && !(_a.tag == TAG_STRING && _b.tag == TAG_STRING)) _cmp_type_error(); _push(_cmp(_a,_b,3)); }} _pc={next_pc}; break;\n")); }
        "gt" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!(_is_num(_a) && _is_num(_b)) && !(_a.tag == TAG_STRING && _b.tag == TAG_STRING)) _cmp_type_error(); _push(_cmp(_a,_b,4)); }} _pc={next_pc}; break;\n")); }
        "ge" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (!(_is_num(_a) && _is_num(_b)) && !(_a.tag == TAG_STRING && _b.tag == TAG_STRING)) _cmp_type_error(); _push(_cmp(_a,_b,5)); }} _pc={next_pc}; break;\n")); }

        // ── Logical ──
        "and" => {
            out.push_str(&format!(
                "                {{ bool _tb = _truthy(_pop()); bool _ta = _truthy(_pop()); _push(mk_bool(_ta && _tb)); }} _pc={next_pc}; break;\n"
            ));
        }
        "or" => {
            out.push_str(&format!(
                "                {{ bool _tb = _truthy(_pop()); bool _ta = _truthy(_pop()); _push(mk_bool(_ta || _tb)); }} _pc={next_pc}; break;\n"
            ));
        }
        "not" => { out.push_str(&format!("                {{ Value _v = _pop(); _push(_not(_v)); }} _pc={next_pc}; break;\n")); }

        // ── Bitwise ops ──
        "bit_and" => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i & _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "bit_or"  => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i | _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "bit_xor" => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i ^ _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "bit_not" => {{ out.push_str(&format!("                {{ Value _v = _pop(); if (_v.tag == TAG_INT) {{ _push(mk_int(~_v.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "shl"     => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i << _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}
        "shr"     => {{ out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); if (_a.tag == TAG_INT && _b.tag == TAG_INT) {{ _push(mk_int(_a.i >> _b.i)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n")); }}

        // ── Control flow ──
        "jmp" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!("                _pc = {t}; break;\n"));
            } else {
                out.push_str(&format!("                _pc = {next_pc}; break;\n"));
            }
        }
        "jmp_if" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "                if (_truthy(_peek())) {{ _pop(); _pc = {t}; break; }} else {{ _pop(); _pc = {next_pc}; break; }}\n"
                ));
            } else {
                out.push_str(&format!("                _pop(); _pc = {next_pc}; break;\n"));
            }
        }
        "jmp_if_not" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "                if (!_truthy(_peek())) {{ _pop(); _pc = {t}; break; }} else {{ _pop(); _pc = {next_pc}; break; }}\n"
                ));
            } else {
                out.push_str(&format!("                _pop(); _pc = {next_pc}; break;\n"));
            }
        }
        // ── Async / AI opcodes ──
        // AOT backends can't spawn OS threads or yield at the instruction level;
        // these are stubbed to the minimum safe behavior.
        "spawn" => {
            // Pop function name + argc args (left on stack), push null.
            // AOT can't spawn green threads, but we must keep the stack balanced.
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0);
            out.push_str(&format!("                _pop(); // fn name\n"));
            for _ in 0..argc {
                out.push_str(&format!("                _pop(); // arg\n"));
            }
            out.push_str(&format!("                _push(mk_null());\n"));
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }
        "yield" => {
            // Cooperative yield is a no-op in sequential AOT execution.
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }
        "await" => {
            // Pop handle, push null
            out.push_str(&format!("                _pop(); // handle\n"));
            out.push_str(&format!("                _push(mk_null());\n"));
            out.push_str(&format!("                _pc={next_pc}; break;\n"));
        }

        // ── AI opcodes ──
        // AOT C can't perform AI queries. The JSON config is in the instruction args,
        // NOT on the stack. Push null (matching scheduler/portable VM behavior).
        // ── AI opcodes ──
        // CRUSH-32 follow-up: per-opcode inline stub emit (`mk_ai_stub`), so all
        // 5 execution tiers agree at differential-cmp time. Args ride on
        // instruction args (not on the VM stack); echo is always an empty
        // Array here.
        "ai_query" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"query\")); _pc={next_pc}; break;\n"));
        }
        "ai_synthesize" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"synthesize\")); _pc={next_pc}; break;\n"));
        }
        "ai_agent_delegation" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"agent_delegation\")); _pc={next_pc}; break;\n"));
        }
        "ai_semantic_match" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"semantic_match\")); _pc={next_pc}; break;\n"));
        }
        "ai_learning_loop" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"learning_loop\")); _pc={next_pc}; break;\n"));
        }
        "ai_context_aware" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"context_aware\")); _pc={next_pc}; break;\n"));
        }
        "ai_toolchain" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"toolchain\")); _pc={next_pc}; break;\n"));
        }
        "ai_goal_declaration" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"goal_declaration\")); _pc={next_pc}; break;\n"));
        }
        "ai_progress_update" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"progress_update\")); _pc={next_pc}; break;\n"));
        }
        "ai_knowledge_sharing" => {
            out.push_str(&format!("                _push(mk_ai_stub(\"knowledge_sharing\")); _pc={next_pc}; break;\n"));
        }

        // ── DOM opcodes (CRUSH-33 Commit 2) ─────────────────────────────────
        // Per-opcode inline stub emit (`mk_dom_stub`), so all 5 execution
        // tiers agree at differential-cmp time. Mirror of the AI per-opcode
        // arms above. Slots are 0x9A-0x9F (CRUD/nav) and 0xB5-0xB8
        // (parent/attr/text/event) per CRUSH-33 Commit 1.
        "dom_query" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"query\")); _pc={next_pc}; break;\n"));
        }
        "dom_get" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"get\")); _pc={next_pc}; break;\n"));
        }
        "dom_set" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"set\")); _pc={next_pc}; break;\n"));
        }
        "dom_create" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"create\")); _pc={next_pc}; break;\n"));
        }
        "dom_remove" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"remove\")); _pc={next_pc}; break;\n"));
        }
        "dom_child" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"child\")); _pc={next_pc}; break;\n"));
        }
        "dom_parent" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"parent\")); _pc={next_pc}; break;\n"));
        }
        "dom_attr" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"attr\")); _pc={next_pc}; break;\n"));
        }
        "dom_text" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"text\")); _pc={next_pc}; break;\n"));
        }
        "dom_event" => {
            out.push_str(&format!("                _push(mk_dom_stub(\"event\")); _pc={next_pc}; break;\n"));
        }

        "ret" | "halt" => {
            out.push_str("                { Value __ret = _pop(); _lsp = __lb; return __ret; }\n");
        }

        // ── Calls ──
        "call" => {
            let target = args["function"].as_str().unwrap_or("");
            let fn_name = sanitize_fn_name(target);
            // Args are already on the stack; callee's store param instrs pop them.
            out.push_str(&format!(
                "                {{ Value __r = fn_{fn_name}(); _push(__r); }} _pc={next_pc}; break;\n"
            ));
        }

        // ── Arrays ──
        "new_array" => {
            // Size is a pre-allocation hint ��� elements are pushed separately via
            // subsequent push_int + array_push instructions. Always create empty array.
            out.push_str(&format!("                {{ int __ai = _alloc_array(); _push(__ai >= 0 ? mk_array(__ai) : mk_null()); }} _pc={next_pc}; break;\n"));
        }
        "arr_get" | "index" => {{
            out.push_str(&format!("                {{ Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ _push(__a->data[__wi]); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_set" => {{
            out.push_str(&format!("                {{ Value __val_v = _pop(); Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ __a->data[__wi] = __val_v; }} }} }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_len" | "len" => {{
            out.push_str(&format!("                {{ Value __v = _pop(); if (__v.tag == TAG_ARRAY) {{ int __ai = __v.array_idx; _push(mk_int(__ai >= 0 && __ai < _array_count ? (int64_t)_arrays[__ai].len : 0LL)); }} else if (__v.tag == TAG_STRING) {{ _push(mk_int((int64_t)strlen(__v.s))); }} else {{ _push(mk_int(0LL)); }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_push" | "array_push" => {{
            out.push_str(&format!("                {{ Value __val = _pop(); Value __arr = _pop(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; _array_push(__a, __val); }} }} _push(__arr); }} _pc={next_pc}; break;\n"));
        }}
        "arr_pop" | "array_pop" => {{
            out.push_str(&format!("                {{ Value __arr = _pop(); Value __popped = mk_null(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len > 0) {{ __popped = __a->data[--__a->len]; }} }} }} _push(__arr); _push(__popped); }} _pc={next_pc}; break;\n"));
        }}
        "make_range" => {{
            out.push_str(&format!("                {{ Value __end_v = _pop(); Value __start_v = _pop(); int64_t __start = (__start_v.tag == TAG_INT) ? __start_v.i : 0; int64_t __end = (__end_v.tag == TAG_INT) ? __end_v.i : 0; int __ai = _alloc_array(); if (__ai >= 0) {{ CrushArray* __a = &_arrays[__ai]; if (__end > __start) _array_reserve(__a, __end - __start); int __n = 0; for (int64_t __i = __start; __i < __end; __i++) __a->data[__n++] = mk_int(__i); __a->len = __n; _push(mk_array(__ai)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}

        // ── Objects ──
        "new_obj" => {{
            out.push_str(&format!("                {{ int __oi = _alloc_object(); _push(__oi >= 0 ? mk_object(__oi) : mk_null()); }} _pc={next_pc}; break;\n"));
        }}
        "get_field" => {{
            let field = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let escaped = field.escape_default().to_string();
            out.push_str(&format!("                {{ Value __obj = _pop(); if (__obj.tag == TAG_OBJECT) {{ int __oi = __obj.obj_idx; if (__oi >= 0 && __oi < _object_count) {{ _push(_obj_get(&_objects[__oi], \"{escaped}\")); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}
        "set_field" => {{
            let field = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let escaped = field.escape_default().to_string();
            out.push_str(&format!("                {{ Value __val = _pop(); Value __obj = _pop(); if (__obj.tag == TAG_OBJECT) {{ int __oi = __obj.obj_idx; if (__oi >= 0 && __oi < _object_count) {{ _obj_set(&_objects[__oi], \"{escaped}\", __val); }} }} _push(__obj); }} _pc={next_pc}; break;\n"));
        }}

        // ── Cap calls → inline dispatch ──
        "cap_call" => {
            let cap_name = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
            match cap_name {
                "append" | "push" | "arr.push" | "array.push" => {
                    out.push_str(&format!("                {{ Value __val = _pop(); Value __arr = _pop(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; _array_push(__a, __val); }} }} }} _pc={next_pc}; break; // cap_call append/push\n"));
                }
                "arr_get" => {
                    out.push_str(&format!("                {{ Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ _push(__a->data[__wi]); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break; // cap_call arr_get\n"));
                }
                "arr_set" => {
                    out.push_str(&format!("                {{ Value __val_v = _pop(); Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ __a->data[__wi] = __val_v; }} }} }} }} _pc={next_pc}; break; // cap_call arr_set\n"));
                }
                "make_range" => {
                    // Variadic: 0, 1, or 2 args �� args pushed left-to-right, top of stack = last arg
                    out.push_str(&format!("                {{ int64_t __start = 0, __end = 100; if ({argc} >= 2) {{ Value __ev = _pop(); __end = (__ev.tag == TAG_INT) ? __ev.i : 100; Value __sv = _pop(); __start = (__sv.tag == TAG_INT) ? __sv.i : 0; }} else if ({argc} >= 1) {{ Value __ev = _pop(); __end = (__ev.tag == TAG_INT) ? __ev.i : 100; }} int __ai = _alloc_array(); if (__ai >= 0) {{ CrushArray* __a = &_arrays[__ai]; if (__end > __start) _array_reserve(__a, __end - __start); int __n = 0; for (int64_t __i = __start; __i < __end; __i++) __a->data[__n++] = mk_int(__i); __a->len = __n; _push(mk_array(__ai)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break; // cap_call make_range\n"));
                }
                "io.read" => {
                    out.push_str(&format!("                {{ _push(mk_string(io_read_line())); }} _pc={next_pc}; break; // cap_call io.read\n"));
                }
                "conv.chr" => {
                    out.push_str(&format!("                {{ Value __v = _pop(); if (__v.tag != TAG_INT) _crush_arith_error(\"conv.chr: expected int\"); _push(mk_string(_conv_chr(__v.i))); }} _pc={next_pc}; break; // cap_call conv.chr\n"));
                }
                "conv.ord" => {
                    out.push_str(&format!("                {{ Value __v = _pop(); if (__v.tag != TAG_STRING) _crush_arith_error(\"conv.ord: expected string\"); _push(mk_int(_conv_ord(__v.s))); }} _pc={next_pc}; break; // cap_call conv.ord\n"));
                }
                "io.print" | "print" => {
                    // Same text as string concatenation (`_to_text_buf`), and pushes null like
                    // the VM: the CASM pops print's result, so pushing nothing popped the
                    // caller's pending operand instead (CRUSH-216).
                    out.push_str(&format!("                {{ Value __pv = _pop(); char __tb[TEXTBUF_SIZE]; if (__pv.tag == TAG_ARRAY) printf(\"[array#%d]\\n\", __pv.array_idx); else printf(\"%s\\n\", _to_text_buf(__pv, __tb)); _push(mk_null()); }} _pc={next_pc}; break; // cap_call io.print\n"));
                }
                _ => unsupported = Some(format!("cap_call '{cap_name}'")),
            }
        }

        // ── String ops ──
        "str_contains" => {{
            out.push_str(&format!("                {{ Value __pat = _pop(); Value __s = _pop(); bool __r = false; if (__s.tag == TAG_STRING && __pat.tag == TAG_STRING) {{ __r = strstr(__s.s, __pat.s) != NULL; }} _push(mk_bool(__r)); }} _pc={next_pc}; break;\n"));
        }}
        "str_starts_with" => {{
            out.push_str(&format!("                {{ Value __pfx = _pop(); Value __s = _pop(); bool __r = false; if (__s.tag == TAG_STRING && __pfx.tag == TAG_STRING) {{ size_t __sl = strlen(__s.s); size_t __pl = strlen(__pfx.s); __r = (__sl >= __pl && strncmp(__s.s, __pfx.s, __pl) == 0); }} _push(mk_bool(__r)); }} _pc={next_pc}; break;\n"));
        }}
        "str_ends_with" => {{
            out.push_str(&format!("                {{ Value __sfx = _pop(); Value __s = _pop(); bool __r = false; if (__s.tag == TAG_STRING && __sfx.tag == TAG_STRING) {{ size_t __sl = strlen(__s.s); size_t __xl = strlen(__sfx.s); __r = (__sl >= __xl && strcmp(__s.s + __sl - __xl, __sfx.s) == 0); }} _push(mk_bool(__r)); }} _pc={next_pc}; break;\n"));
        }}
        "str_to_upper" => {{
            out.push_str(&format!("                {{ Value __s = _pop(); _push(__s.tag == TAG_STRING ? mk_string(_str_map_case(__s.s, 1)) : __s); }} _pc={next_pc}; break;\n"));
        }}
        "str_to_lower" => {{
            out.push_str(&format!("                {{ Value __s = _pop(); _push(__s.tag == TAG_STRING ? mk_string(_str_map_case(__s.s, 0)) : __s); }} _pc={next_pc}; break;\n"));
        }}
        "str_trim" => {{
            out.push_str(&format!("                {{ Value __s = _pop(); _push(__s.tag == TAG_STRING ? mk_string(_str_trim(__s.s)) : __s); }} _pc={next_pc}; break;\n"));
        }}
        // `str_split` / `str_replace` / `str_join` need dynamic strings this
        // backend doesn't have; they used to compile to a null stub.
        "nop" => out.push_str(&format!("                _pc = {next_pc}; break;\n")),
        _ => unsupported = Some(format!("`{}`", instr.op)),
    }
    unsupported
}

/// A C `double` literal that reads back as exactly `v`. Rust's `{v}` Display writes
/// `1e20` as `100000000000000000000`, an integer literal too large for C (CRUSH-216);
/// `{v:?}` is the shortest round-trip form and uses an exponent when that's shorter.
fn c_double_literal(v: f64) -> String {
    if v.is_nan() {
        "NAN".to_string()
    } else if v.is_infinite() {
        if v > 0.0 { "INFINITY".to_string() } else { "(-INFINITY)".to_string() }
    } else {
        format!("{v:?}")
    }
}

// ── Entry point ─────────────────────────────────────────────────────────────

fn emit_c_entry_point(out: &mut String) {
    out.push_str(r#"
// ── C ABI entry point ────���─────────────────────────────────────────────
// Returns the result of fn_main() serialized as a string.
// CAUTION: returns pointer to static buffer — callers must copy immediately.

__attribute__((visibility("default")))
const char* crush_run(void) {
    _sp = 0;  // reset stack
    _lsp = 0;
    _reset_arrays();
    _reset_strings();
    _gc_allocated = 0;
    _gc_threshold = 1 << 20;
    const char* __stress = getenv("CRUSH_GC_STRESS");
    _gc_stress = __stress != NULL && __stress[0] != '\0' && __stress[0] != '0';
    Value result = fn_main();
    // The host prints the result through its own stdout; flush ours first so
    // the program's output comes before it (CRUSH-216).
    fflush(stdout);
    static char _buf[512];
    char __tb[TEXTBUF_SIZE];
    switch (result.tag) {
        case TAG_INT:   snprintf(_buf, sizeof(_buf), "%ld", (long)result.i); break;
        case TAG_FLOAT: snprintf(_buf, sizeof(_buf), "%s", _float_text(result.f, __tb)); break;
        case TAG_BOOL:  snprintf(_buf, sizeof(_buf), "%s", result.b ? "true" : "false"); break;
        case TAG_NULL:  snprintf(_buf, sizeof(_buf), "null"); break;
        case TAG_STRING: {
            // A string can be any length, so it gets its own buffer, valid until
            // the next crush_run() (a fixed 512 bytes truncated longer results).
            static char* _str_result = NULL;
            size_t __n = strlen(result.s) + 3;
            char* __r = (char*)realloc(_str_result, __n);
            if (!__r) { fprintf(stderr, "crush(aotc): out of memory\n"); exit(1); }
            _str_result = __r;
            snprintf(_str_result, __n, "\"%s\"", result.s);
            return _str_result;
        }
        case TAG_ARRAY:  snprintf(_buf, sizeof(_buf), "[array#%d len=%d]", result.array_idx, result.array_idx >= 0 && result.array_idx < _array_count ? _arrays[result.array_idx].len : 0); break;
        case TAG_OBJECT: snprintf(_buf, sizeof(_buf), "[object#%d fields=%d]", result.obj_idx, result.obj_idx >= 0 && result.obj_idx < _object_count ? _objects[result.obj_idx].field_count : 0); break;
        default:         snprintf(_buf, sizeof(_buf), "null"); break;
    }
    return _buf;
}

__attribute__((visibility("default")))
void crush_run_free(const char* s) {
    (void)s; // static buffer, no-op
}
"#);
}

// CRUSH-32 follow-up: AI stub emitter (no-op marker). The `mk_ai_stub` C
// function above lives inside the `r#"..."#` prelude emitted by
// `emit_c_value`; this Rust-side emitter exists so `gen_c_source` can
// call `emit_c_ai_stub(&mut out)` symmetrically with the AOT-Rust
// `codegen.rs::emit_ai_stub`. Real C-only helpers, if ever needed, get
// added here at module scope -- never inside the `r#"..."#` prelude
// (earlier fetch where these helpers were placed inside the prelude
// raw-string caused a structural parse error).
fn emit_c_ai_stub(_out: &mut String) {}

// CRUSH-33 Commit 2: DOM stub emitter (no-op marker). The `mk_dom_stub` C
// function above lives inside the `r#"..."#` prelude emitted by
// `emit_c_value`; this Rust-side emitter exists so `gen_c_source` can
// call `emit_c_dom_stub(&mut out)` symmetrically with the AOT-Rust
// `codegen.rs::emit_dom_stub`. Real C-only helpers, if ever needed, get
// added here at module scope -- never inside the `r#"..."#` prelude
// (an earlier fetch had these helpers inside the prelude raw-string and
// caused a structural parse error).
fn emit_c_dom_stub(_out: &mut String) {}
