//! CASM → C source code generator.
//!
//! Transpiles a `casm::Program` into self-contained C99 source with a
//! `switch(pc)` dispatch loop that compilers optimize into jump tables.
//!
//! The generated C defines its own tagged union (`Value`) and stack machine,
//! and exports a `crush_run()` symbol for dlopen-based loading.

use std::collections::HashMap;

/// Transpile a CASM program to C source code.
pub fn gen_c_source(program: &casm::Program) -> String {
    let mut out = String::new();

    emit_c_header(&mut out);
    emit_c_value(&mut out);
    emit_c_helpers(&mut out);

    for (name, func) in &program.functions {
        emit_c_function(&mut out, name, func, program);
    }

    emit_c_entry_point(&mut out);
    out
}

// ── Header ──────────────────────────────────────────────────────────────────

fn emit_c_header(out: &mut String) {
    out.push_str(r#"// Generated by crush-aotc --emit c. Do not edit.
// CASM → C transpiled stack machine.
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

"#);
}

// ── Tagged Value ────────────────────────────────────────────────────────────

fn emit_c_value(out: &mut String) {
    out.push_str(r#"typedef enum {
    TAG_INT,
    TAG_FLOAT,
    TAG_BOOL,
    TAG_NULL,
    TAG_STRING,
    TAG_ARRAY,
} ValueTag;

typedef struct {
    ValueTag tag;
    union {
        int64_t  i;
        double   f;
        bool     b;
        const char* s;
        int      array_idx;
    };
} Value;

static inline Value mk_int(int64_t i)   { return (Value){TAG_INT, .i=i}; }
static inline Value mk_float(double f)  { return (Value){TAG_FLOAT, .f=f}; }
static inline Value mk_bool(bool b)     { return (Value){TAG_BOOL, .b=b}; }
static inline Value mk_null(void)       { return (Value){TAG_NULL}; }
static inline Value mk_string(const char* s) { return (Value){TAG_STRING, .s=s}; }
static inline Value mk_array(int idx)   { return (Value){TAG_ARRAY, .array_idx=idx}; }

// ── Array pool ───────────────────────────────────────────────────────
#define ARRAY_POOL_MAX 64
#define ARRAY_DATA_CAP 1024

typedef struct {
    Value data[ARRAY_DATA_CAP];
    int   len;
} CrushArray;

static CrushArray _arrays[ARRAY_POOL_MAX];
static int        _array_count = 0;

static inline int _alloc_array(void) {
    if (_array_count >= ARRAY_POOL_MAX) return -1;
    _arrays[_array_count].len = 0;
    return _array_count++;
}

static inline int _wrap_index(int idx, int len) {
    if (idx < 0) idx += len;
    return (idx >= 0 && idx < len) ? idx : -1;
}

"#);
}

// ── Stack ───────────────────────────────────────────────────────────────────

fn emit_c_helpers(out: &mut String) {
    out.push_str(r#"// ── Stack ──────────────────────────────────────────────────────────
#define STACK_MAX 512
static Value   _stack[STACK_MAX];
static int     _sp = 0;

static void _reset_arrays(void) { _array_count = 0; }

static inline void  _push(Value v) { if (_sp < STACK_MAX) _stack[_sp++] = v; }
static inline Value _pop(void)     { return _sp > 0 ? _stack[--_sp] : mk_null(); }
static inline Value _peek(void)    { return _sp > 0 ? _stack[_sp-1] : mk_null(); }
static inline void  _dup(void)     { if (_sp > 0 && _sp < STACK_MAX) _stack[_sp] = _stack[_sp-1], _sp++; }
static inline void  _swap(void)    { if (_sp >= 2) { Value t=_stack[_sp-1]; _stack[_sp-1]=_stack[_sp-2]; _stack[_sp-2]=t; } }

static inline double _to_float(Value v) { return (v.tag == TAG_FLOAT) ? v.f : ((v.tag == TAG_INT) ? (double)v.i : 0.0); }
static inline int64_t _to_int(Value v) { return (v.tag == TAG_INT) ? v.i : ((v.tag == TAG_FLOAT) ? (int64_t)v.f : 0); }

// ── Helpers ──────────────────────────────────────────────────────────────
static inline bool _truthy(Value v) {
    switch (v.tag) {
        case TAG_BOOL: return v.b;
        case TAG_INT:  return v.i != 0;
        case TAG_NULL: return false;
        default:       return true;
    }
}

static inline bool _is_num(Value v) { return v.tag == TAG_INT || v.tag == TAG_FLOAT; }

static Value _add(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) return mk_int(a.i + b.i);
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa + fb);
}
static Value _sub(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) return mk_int(a.i - b.i);
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa - fb);
}
static Value _mul(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) return mk_int(a.i * b.i);
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fa * fb);
}
static Value _div(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) return mk_int(b.i != 0 ? a.i / b.i : 0);
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fb != 0.0 ? fa / fb : 0.0);
}
static Value _mod(Value a, Value b) {
    if (a.tag == TAG_INT && b.tag == TAG_INT) return mk_int(b.i != 0 ? a.i % b.i : 0);
    double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
    double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
    return mk_float(fb != 0.0 ? fmod(fa, fb) : 0.0);
}
static Value _neg(Value v) {
    if (v.tag == TAG_INT)  return mk_int(-v.i);
    if (v.tag == TAG_FLOAT) return mk_float(-v.f);
    return mk_null();
}
static Value _not(Value v) { return mk_bool(!_truthy(v)); }

static Value _cmp(Value a, Value b, int op) {
    // op: 0=EQ, 1=NE, 2=LT, 3=LE, 4=GT, 5=GE
    bool r = false;
    if (a.tag == TAG_INT && b.tag == TAG_INT) {
        switch (op) {
            case 0: r = a.i == b.i; break; case 1: r = a.i != b.i; break;
            case 2: r = a.i <  b.i; break; case 3: r = a.i <= b.i; break;
            case 4: r = a.i >  b.i; break; case 5: r = a.i >= b.i; break;
        }
    } else if (_is_num(a) && _is_num(b)) {
        double fa = (a.tag == TAG_INT) ? (double)a.i : a.f;
        double fb = (b.tag == TAG_INT) ? (double)b.i : b.f;
        switch (op) {
            case 0: r = fa == fb; break; case 1: r = fa != fb; break;
            case 2: r = fa <  fb; break; case 3: r = fa <= fb; break;
            case 4: r = fa >  fb; break; case 5: r = fa >= fb; break;
        }
    } else if (a.tag == TAG_BOOL && b.tag == TAG_BOOL) {
        r = (op == 0) ? (a.b == b.b) : (a.b != b.b);
    } else if (a.tag == TAG_NULL && b.tag == TAG_NULL) {
        r = (op == 0);
    }
    return mk_bool(r);
}

"#);
}

// ── Function emission ───────────────────────────────────────────────────────

#[derive(Clone)]
enum LocalType { Value, F64, I64 }

#[derive(Clone)]
struct LocalMeta {
    c_name: String,
    ty: LocalType,
}

fn emit_c_function(
    out: &mut String,
    name: &str,
    func: &casm::Function,
    _program: &casm::Program,
) {
    let fn_name = sanitize_fn_name(name);
    let n = func.body.len();

    // Discover locals by scanning store/load instructions (func.locals may be empty)
    let local_index = discover_locals(&func.body, &func.params, func.type_hints.as_ref());

    out.push_str(&format!("static Value fn_{fn_name}(void) {{\n"));

    // Locals
    for meta in local_index.values() {
        match meta.ty {
            LocalType::F64 => out.push_str(&format!("    double {} = 0.0;\n", meta.c_name)),
            LocalType::I64 => out.push_str(&format!("    int64_t {} = 0;\n", meta.c_name)),
            LocalType::Value => out.push_str(&format!("    Value {} = mk_null();\n", meta.c_name)),
        }
    }

    out.push_str("    int _pc = 0;\n");
    out.push_str("    while (1) {\n");
    out.push_str("        switch (_pc) {\n");

    for (i, instr) in func.body.iter().enumerate() {
        out.push_str(&format!("            case {i}: {{\n"));
        emit_c_instr(out, instr, i, n, &local_index);
        out.push_str("            }\n");
    }

    out.push_str("            default: return mk_null();\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

fn sanitize_fn_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

/// Pre-scan instructions to discover local variable names from store/load ops.
fn discover_locals(body: &[casm::Instruction], params: &[String], type_hints: Option<&HashMap<String, String>>) -> HashMap<String, LocalMeta> {
    let mut map = HashMap::new();
    let mut next = 0usize;

    let mut add_local = |name: &str, map: &mut HashMap<String, LocalMeta>, next: &mut usize| {
        if !map.contains_key(name) {
            let ty_str = type_hints.and_then(|h| h.get(name)).map(|s| s.as_str()).unwrap_or("");
            let ty = match ty_str {
                "Float" | "F64" | "F32" => LocalType::F64,
                "Int" => LocalType::I64,
                _ => LocalType::Value,
            };
            let prefix = match ty {
                LocalType::F64 => "_lf",
                LocalType::I64 => "_li",
                LocalType::Value => "_lv",
            };
            map.insert(name.to_string(), LocalMeta {
                c_name: format!("{}_{}", prefix, next),
                ty,
            });
            *next += 1;
        }
    };

    for p in params { add_local(p, &mut map, &mut next); }
    for instr in body {
        if matches!(instr.op.as_str(), "store" | "load") {
            if let Some(name) = instr.args.get("name").and_then(|v| v.as_str()) {
                add_local(name, &mut map, &mut next);
            }
        }
    }
    map
}

// ── Instruction emission ────────────────────────────────────────────────────

fn emit_c_instr(
    out: &mut String,
    instr: &casm::Instruction,
    this_pc: usize,
    total_instrs: usize,
    locals: &HashMap<String, LocalMeta>,
) {
    let args = &instr.args;
    let next = this_pc + 1;
    let next_pc = if next < total_instrs { next } else { total_instrs };

    match instr.op.as_str() {
        // ── Push ──
        "push_int" => {
            let v = args["value"].as_i64().unwrap_or(0);
            out.push_str(&format!("                _push(mk_int({v}LL)); _pc={next_pc}; break;\n"));
        }
        "push_float" => {
            let v = args["value"].as_f64().unwrap_or(0.0);
            out.push_str(&format!("                _push(mk_float({v})); _pc={next_pc}; break;\n"));
        }
        "push_bool" => {
            let v = args["value"].as_bool().unwrap_or(false);
            out.push_str(&format!("                _push(mk_bool({v})); _pc={next_pc}; break;\n"));
        }
        "push_null" => {
            out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break;\n"));
        }
        "push_str" => {
            let s = args["value"].as_str().unwrap_or("");
            let escaped = s.escape_default().to_string();
            out.push_str(&format!("                _push(mk_string(\"{escaped}\")); _pc={next_pc}; break;\n"));
        }

        // ── Stack ops ──
        "pop"  => { out.push_str(&format!("                _pop(); _pc={next_pc}; break;\n")); }
        "dup"  => { out.push_str(&format!("                _dup(); _pc={next_pc}; break;\n")); }
        "swap" => { out.push_str(&format!("                _swap(); _pc={next_pc}; break;\n")); }

        // ── Locals ──
        "load" => {
            let name = args["name"].as_str().unwrap_or("");
            if let Some(meta) = locals.get(name) {
                match meta.ty {
                    LocalType::F64 => out.push_str(&format!("                _push(mk_float({})); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::I64 => out.push_str(&format!("                _push(mk_int({})); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::Value => out.push_str(&format!("                _push({}); _pc={next_pc}; break;\n", meta.c_name)),
                }
            } else {
                out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break;\n"));
            }
        }
        "store" => {
            let name = args["name"].as_str().unwrap_or("");
            if let Some(meta) = locals.get(name) {
                match meta.ty {
                    LocalType::F64 => out.push_str(&format!("                {} = _to_float(_pop()); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::I64 => out.push_str(&format!("                {} = _to_int(_pop()); _pc={next_pc}; break;\n", meta.c_name)),
                    LocalType::Value => out.push_str(&format!("                {} = _pop(); _pc={next_pc}; break;\n", meta.c_name)),
                }
            } else {
                out.push_str(&format!("                _pop(); _pc={next_pc}; break;\n"));
            }
        }

        // ── Arithmetic ──
        "add" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_add(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "sub" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_sub(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "mul" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_mul(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "div" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_div(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "mod" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_mod(_a,_b)); }} _pc={next_pc}; break;\n")); }
        "neg" => { out.push_str(&format!("                {{ Value _v = _pop(); _push(_neg(_v)); }} _pc={next_pc}; break;\n")); }

        // ── Comparison ──
        "eq" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,0)); }} _pc={next_pc}; break;\n")); }
        "ne" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,1)); }} _pc={next_pc}; break;\n")); }
        "lt" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,2)); }} _pc={next_pc}; break;\n")); }
        "le" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,3)); }} _pc={next_pc}; break;\n")); }
        "gt" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,4)); }} _pc={next_pc}; break;\n")); }
        "ge" => { out.push_str(&format!("                {{ Value _b = _pop(); Value _a = _pop(); _push(_cmp(_a,_b,5)); }} _pc={next_pc}; break;\n")); }

        // ── Logical ──
        "and" => {
            out.push_str(&format!(
                "                {{ bool _tb = _truthy(_pop()); bool _ta = _truthy(_pop()); _push(mk_bool(_ta && _tb)); }} _pc={next_pc}; break;\n"
            ));
        }
        "or" => {
            out.push_str(&format!(
                "                {{ bool _tb = _truthy(_pop()); bool _ta = _truthy(_pop()); _push(mk_bool(_ta || _tb)); }} _pc={next_pc}; break;\n"
            ));
        }
        "not" => { out.push_str(&format!("                {{ Value _v = _pop(); _push(_not(_v)); }} _pc={next_pc}; break;\n")); }

        // ── Control flow ──
        "jmp" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!("                _pc = {t}; break;\n"));
            } else {
                out.push_str(&format!("                _pc = {next_pc}; break;\n"));
            }
        }
        "jmp_if" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "                if (_truthy(_peek())) {{ _pop(); _pc = {t}; break; }} else {{ _pop(); _pc = {next_pc}; break; }}\n"
                ));
            } else {
                out.push_str(&format!("                _pop(); _pc = {next_pc}; break;\n"));
            }
        }
        "jmp_if_not" => {
            if let Some(target) = args["target"].as_u64() {
                let t = target as usize;
                out.push_str(&format!(
                    "                if (!_truthy(_peek())) {{ _pop(); _pc = {t}; break; }} else {{ _pop(); _pc = {next_pc}; break; }}\n"
                ));
            } else {
                out.push_str(&format!("                _pop(); _pc = {next_pc}; break;\n"));
            }
        }
        "ret" | "halt" => {
            out.push_str("                return _pop();\n");
        }

        // ── Calls ──
        "call" => {
            let target = args["function"].as_str().unwrap_or("");
            let fn_name = sanitize_fn_name(target);
            // Args are already on the stack; callee's store param instrs pop them.
            out.push_str(&format!(
                "                {{ Value __r = fn_{fn_name}(); _push(__r); }} _pc={next_pc}; break;\n"
            ));
        }

        // ── Arrays ──
        "new_array" => {
            // Size is a pre-allocation hint ��� elements are pushed separately via
            // subsequent push_int + array_push instructions. Always create empty array.
            out.push_str(&format!("                {{ int __ai = _alloc_array(); _push(__ai >= 0 ? mk_array(__ai) : mk_null()); }} _pc={next_pc}; break;\n"));
        }
        "arr_get" | "index" => {{
            out.push_str(&format!("                {{ Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ _push(__a->data[__wi]); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_set" => {{
            out.push_str(&format!("                {{ Value __val_v = _pop(); Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ __a->data[__wi] = __val_v; }} }} }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_len" | "len" => {{
            out.push_str(&format!("                {{ Value __v = _pop(); if (__v.tag == TAG_ARRAY) {{ int __ai = __v.array_idx; _push(mk_int(__ai >= 0 && __ai < _array_count ? (int64_t)_arrays[__ai].len : 0LL)); }} else if (__v.tag == TAG_STRING) {{ _push(mk_int((int64_t)strlen(__v.s))); }} else {{ _push(mk_int(0LL)); }} }} _pc={next_pc}; break;\n"));
        }}
        "arr_push" | "array_push" => {{
            out.push_str(&format!("                {{ Value __val = _pop(); Value __arr = _pop(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len < ARRAY_DATA_CAP) {{ __a->data[__a->len++] = __val; }} }} }} _push(__arr); }} _pc={next_pc}; break;\n"));
        }}
        "arr_pop" | "array_pop" => {{
            out.push_str(&format!("                {{ Value __arr = _pop(); Value __popped = mk_null(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len > 0) {{ __popped = __a->data[--__a->len]; }} }} }} _push(__arr); _push(__popped); }} _pc={next_pc}; break;\n"));
        }}
        "make_range" => {{
            out.push_str(&format!("                {{ Value __end_v = _pop(); Value __start_v = _pop(); int64_t __start = (__start_v.tag == TAG_INT) ? __start_v.i : 0; int64_t __end = (__end_v.tag == TAG_INT) ? __end_v.i : 0; int __ai = _alloc_array(); if (__ai >= 0) {{ CrushArray* __a = &_arrays[__ai]; int64_t __i = __start; int __n = 0; while (__i < __end && __n < ARRAY_DATA_CAP) {{ __a->data[__n++] = mk_int(__i); __i++; }} __a->len = __n; _push(mk_array(__ai)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break;\n"));
        }}

        // ── Cap calls → inline dispatch ──
        "cap_call" => {
            let cap_name = args.get("name").and_then(|v| v.as_str()).unwrap_or("");
            let argc = args.get("argc").and_then(|v| v.as_u64()).unwrap_or(0) as usize;
            match cap_name {
                "append" | "push" | "arr.push" | "array.push" => {
                    out.push_str(&format!("                {{ Value __val = _pop(); Value __arr = _pop(); if (__arr.tag == TAG_ARRAY) {{ int __ai = __arr.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; if (__a->len < ARRAY_DATA_CAP) {{ __a->data[__a->len++] = __val; }} }} }} }} _pc={next_pc}; break; // cap_call append/push\n"));
                }
                "arr_get" => {
                    out.push_str(&format!("                {{ Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ _push(__a->data[__wi]); }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break; // cap_call arr_get\n"));
                }
                "arr_set" => {
                    out.push_str(&format!("                {{ Value __val_v = _pop(); Value __idx_v = _pop(); Value __arr_v = _pop(); if (__arr_v.tag == TAG_ARRAY && __idx_v.tag == TAG_INT) {{ int __ai = __arr_v.array_idx; if (__ai >= 0 && __ai < _array_count) {{ CrushArray* __a = &_arrays[__ai]; int __wi = _wrap_index((int)__idx_v.i, __a->len); if (__wi >= 0) {{ __a->data[__wi] = __val_v; }} }} }} }} _pc={next_pc}; break; // cap_call arr_set\n"));
                }
                "make_range" => {
                    // Variadic: 0, 1, or 2 args �� args pushed left-to-right, top of stack = last arg
                    out.push_str(&format!("                {{ int64_t __start = 0, __end = 100; if ({argc} >= 2) {{ Value __ev = _pop(); __end = (__ev.tag == TAG_INT) ? __ev.i : 100; Value __sv = _pop(); __start = (__sv.tag == TAG_INT) ? __sv.i : 0; }} else if ({argc} >= 1) {{ Value __ev = _pop(); __end = (__ev.tag == TAG_INT) ? __ev.i : 100; }} int __ai = _alloc_array(); if (__ai >= 0) {{ CrushArray* __a = &_arrays[__ai]; int64_t __i = __start; int __n = 0; while (__i < __end && __n < ARRAY_DATA_CAP) {{ __a->data[__n++] = mk_int(__i); __i++; }} __a->len = __n; _push(mk_array(__ai)); }} else {{ _push(mk_null()); }} }} _pc={next_pc}; break; // cap_call make_range\n"));
                }
                "io.print" | "print" => {
                    out.push_str(&format!("                {{ Value __pv = _pop(); switch (__pv.tag) {{ case TAG_INT: printf(\"%ld\\n\", (long)__pv.i); break; case TAG_FLOAT: printf(\"%g\\n\", __pv.f); break; case TAG_BOOL: printf(\"%s\\n\", __pv.b ? \"true\" : \"false\"); break; case TAG_NULL: printf(\"null\\n\"); break; case TAG_STRING: printf(\"%s\\n\", __pv.s); break; default: printf(\"[array#%d]\\n\", __pv.array_idx); break; }} }} _pc={next_pc}; break; // cap_call io.print\n"));
                }
                _ => {
                    if argc > 0 {
                        out.push_str(&format!("                for (int __i=0; __i<{argc}; __i++) _pop();\n"));
                    }
                    out.push_str(&format!("                _push(mk_null()); _pc={next_pc}; break; // cap_call '{}' stubbed\n", cap_name.escape_default()));
                }
            }
        }

        // ── Unknown / NOP ──
        _ => {
            out.push_str(&format!("                _pc = {next_pc}; break;\n"));
        }
    }
}

// ── Entry point ─────────────────────────────────────────────────────────────

fn emit_c_entry_point(out: &mut String) {
    out.push_str(r#"
// ── C ABI entry point ────���─────────────────────────────────────────────
// Returns the result of fn_main() serialized as a string.
// CAUTION: returns pointer to static buffer — callers must copy immediately.

__attribute__((visibility("default")))
const char* crush_run(void) {
    _sp = 0;  // reset stack
    _reset_arrays();
    Value result = fn_main();
    static char _buf[512];
    switch (result.tag) {
        case TAG_INT:   snprintf(_buf, sizeof(_buf), "%ld", (long)result.i); break;
        case TAG_FLOAT: snprintf(_buf, sizeof(_buf), "%.15g", result.f); break;
        case TAG_BOOL:  snprintf(_buf, sizeof(_buf), "%s", result.b ? "true" : "false"); break;
        case TAG_NULL:  snprintf(_buf, sizeof(_buf), "null"); break;
        case TAG_STRING: snprintf(_buf, sizeof(_buf), "\"%s\"", result.s); break;
        case TAG_ARRAY:  snprintf(_buf, sizeof(_buf), "[array#%d len=%d]", result.array_idx, result.array_idx >= 0 && result.array_idx < _array_count ? _arrays[result.array_idx].len : 0); break;
        default:         snprintf(_buf, sizeof(_buf), "null"); break;
    }
    return _buf;
}

__attribute__((visibility("default")))
void crush_run_free(const char* s) {
    (void)s; // static buffer, no-op
}
"#);
}
