//! Dynamic loader for AOT-compiled Crush modules.
//!
//! Wraps `libloading::Library` with a type-safe API for calling
//! AOT-compiled Crush functions.

use anyhow::{Context, Result};
use libloading::{Library, Symbol};
use std::ffi::{c_char, CStr};
use std::path::Path;

/// A loaded AOT-compiled Crush module.
///
/// Internally holds a `libloading::Library` — as long as this struct
/// is alive, the `.so` is loaded and its symbols are callable.
pub struct Module {
    _library: Library,
    crush_run: unsafe extern "C" fn() -> *mut c_char,
    crush_run_free: unsafe extern "C" fn(*mut c_char),
}

impl Module {
    /// Load an AOT-compiled Crush module from a `.so`/`.dylib`/`.dll` file.
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        // Safety: we trust the .so to have the right ABI (it was generated by our codegen)
        let lib = unsafe {
            Library::new(path)
                .with_context(|| format!("Failed to load AOT module from '{}'", path.display()))?
        };

        // Extract function pointers now (they borrow `lib`)
        let crush_run: unsafe extern "C" fn() -> *mut c_char = unsafe {
            let sym: Symbol<unsafe extern "C" fn() -> *mut c_char> = lib
                .get(b"crush_run\0")
                .with_context(|| format!("Module '{}' is missing crush_run symbol", path.display()))?;
            *sym
        };

        let crush_run_free: unsafe extern "C" fn(*mut c_char) = unsafe {
            let sym: Symbol<unsafe extern "C" fn(*mut c_char)> = lib
                .get(b"crush_run_free\0")
                .with_context(|| format!("Module '{}' is missing crush_run_free symbol", path.display()))?;
            *sym
        };

        Ok(Self {
            _library: lib,
            crush_run,
            crush_run_free,
        })
    }

    /// Call the main entry point and return the result as a parsed `RuntimeValue`.
    ///
    /// The AOT-generated module serializes the result as a string via `Display`,
    /// and we parse it back into a typed value.
    pub fn call_main(&self) -> Result<crush_vm::RuntimeValue> {
        let c_str = unsafe { (self.crush_run)() };
        if c_str.is_null() {
            anyhow::bail!("crush_run returned null pointer");
        }

        let rust_str = unsafe { CStr::from_ptr(c_str) }
            .to_str()
            .context("crush_run returned invalid UTF-8")?
            .to_string();

        // Free the C string
        unsafe { (self.crush_run_free)(c_str) };

        // Parse back: the generated code uses RuntimeValue's Display format
        parse_runtime_value(&rust_str)
    }
}

/// Parse a string back into a `RuntimeValue`.
///
/// The generated code outputs via `Display`:
/// - `42` → Int(42)
/// - `3.14` → Float(3.14)
/// - `true` / `false` → Bool
/// - `null` → Null
/// - `"hello"` → String("hello")
fn parse_runtime_value(s: &str) -> Result<crush_vm::RuntimeValue> {
    let s = s.trim();

    // Bool
    if s == "true" { return Ok(crush_vm::RuntimeValue::Bool(true)); }
    if s == "false" { return Ok(crush_vm::RuntimeValue::Bool(false)); }

    // Null
    if s == "null" { return Ok(crush_vm::RuntimeValue::Null); }

    // String (quoted)
    if s.starts_with('"') && s.ends_with('"') {
        let inner = &s[1..s.len()-1];
        return Ok(crush_vm::RuntimeValue::String(inner.to_string()));
    }

    // Float (contains '.' or 'e')
    if s.contains('.') || s.contains('e') || s.contains('E') {
        if let Ok(f) = s.parse::<f64>() {
            return Ok(crush_vm::RuntimeValue::Float(f));
        }
    }

    // Int
    if let Ok(i) = s.parse::<i64>() {
        return Ok(crush_vm::RuntimeValue::Int(i));
    }

    // Fallback: string
    Ok(crush_vm::RuntimeValue::String(s.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_int() {
        assert_eq!(parse_runtime_value("42").unwrap(), crush_vm::RuntimeValue::Int(42));
    }

    #[test]
    fn test_parse_float() {
        assert_eq!(parse_runtime_value("3.14").unwrap(), crush_vm::RuntimeValue::Float(3.14));
    }

    #[test]
    fn test_parse_bool() {
        assert_eq!(parse_runtime_value("true").unwrap(), crush_vm::RuntimeValue::Bool(true));
        assert_eq!(parse_runtime_value("false").unwrap(), crush_vm::RuntimeValue::Bool(false));
    }

    #[test]
    fn test_parse_null() {
        assert_eq!(parse_runtime_value("null").unwrap(), crush_vm::RuntimeValue::Null);
    }

    #[test]
    fn test_parse_string() {
        assert_eq!(
            parse_runtime_value("\"hello\"").unwrap(),
            crush_vm::RuntimeValue::String("hello".to_string())
        );
    }
}
