#[cfg(test)]
mod adapter_tests {
    // CRUSH-36 Commit 2 Sub-Commit 1 (post-Fix-#7 note): the original
    // `use anyhow::Result;` alias was added during Fix #5 with the
    // hypothesis that bare `Result<...>` in the Frontend trait body vs
    // fully-qualified `anyhow::Result<...>` in MockFrontend's impl caused a
    // cross-scope alias-resolution mismatch in trait-method signature
    // matching. After 5 fixes, the actual root cause was identified as
    // Fix #6 -- the missing blanket
    // `impl<T: Frontend + Send + Sync> LanguageAdapter for T` was the
    // actual architectural closure of `Frontend: LanguageAdapter`. The
    // blanket is now in place at crates/crush-walker-core/src/lib.rs and
    // MockFrontend's impl Frontend checks out cleanly without needing the
    // alias in scope here.
    //
    // For FUTURE test mods in sibling crates (CRUSH-37 Java, CRUSH-38
    // Kotlin, CRUSH-43+) following the same pattern: if the test mod body
    // uses bare `Result<...>` matching the Frontend trait body's bare
    // `Result<...>`, add `use anyhow::Result;` at file scope to bring the
    // alias into scope (avoid cross-scope resolution differences in
    // trait-method signature matching). If bodies always use fully-qualified
    // `anyhow::Result<...>`, no alias is needed.
    //
    // This test mod's MockFrontend uses fully-qualified types throughout,
    // so we omit the alias here. (It would otherwise generate an
    // unused-imports warning.)
    use crate::{AdapterRegistry, FeatureReport, Frontend, LanguageAdapter};
    use crush_cast::Program;

    struct MockAdapter {
        lang: &'static str,
        exts: &'static [&'static str],
    }

    impl LanguageAdapter for MockAdapter {
        fn language_name(&self) -> &'static str { self.lang }
        fn file_extensions(&self) -> &[&'static str] { self.exts }
        fn walk(&self, _source: &str, _filename: &str) -> anyhow::Result<(FeatureReport, Program)> {
            Ok((FeatureReport { lang: self.lang.to_string(), ..Default::default() }, Program::default()))
        }
    }

    #[test]
    fn test_registry_walk_by_extension() {
        let mut registry = AdapterRegistry::new();
        registry.register(Box::new(MockAdapter { lang: "testlang", exts: &["tl", "test"] }));

        let (report, _program) = registry.walk("dummy source", "hello.tl").unwrap();
        assert_eq!(report.lang, "testlang");
    }

    #[test]
    fn test_registry_walk_unknown_extension() {
        let registry = AdapterRegistry::new();
        let result = registry.walk("source", "file.unknown");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("no walker registered"));
    }

    #[test]
    fn test_registry_multiple_adapters() {
        let mut registry = AdapterRegistry::new();
        registry.register(Box::new(MockAdapter { lang: "python", exts: &["py"] }));
        registry.register(Box::new(MockAdapter { lang: "rust", exts: &["rs"] }));

        let (r1, _) = registry.walk("x = 1", "test.py").unwrap();
        let (r2, _) = registry.walk("fn main(){}", "test.rs").unwrap();
        assert_eq!(r1.lang, "python");
        assert_eq!(r2.lang, "rust");
    }

    #[test]
    fn test_registry_can_handle() {
        let mut registry = AdapterRegistry::new();
        registry.register(Box::new(MockAdapter { lang: "go", exts: &["go"] }));

        assert!(registry.walk("", "test.go").is_ok());
        assert!(registry.walk("", "test.rs").is_err());
    }

    #[test]
    fn test_registry_languages() {
        let mut registry = AdapterRegistry::new();
        registry.register(Box::new(MockAdapter { lang: "a", exts: &["a"] }));
        registry.register(Box::new(MockAdapter { lang: "b", exts: &["b"] }));

        let langs = registry.languages();
        assert!(langs.contains(&"a"));
        assert!(langs.contains(&"b"));
    }

    // ── CRUSH-36 Commit 2 Sub-Commit 1 (A->B) tests ──────────────────────
    //
    // Frontend: LanguageAdapter supertrait tie + default `walk` test
    // (see `pub trait Frontend: LanguageAdapter { ... }` in
    // crates/crush-walker-core/src/lib.rs:113). Verifies the structural
    // coercion `Box<dyn Frontend> -> Box<dyn LanguageAdapter>` works
    // WITHOUT any wrapper struct. Before CRUSH-36 Commit 2, every
    // `impl Frontend for X` required a separate adapter struct (e.g.
    // `RustAdapter` generated by `impl_adapter_from_frontend!`) to
    // satisfy LanguageAdapter. The supertrait tie removes that wrapper
    // requirement: the default `walk` on Frontend satisfies the
    // LanguageAdapter::walk bound, and language_name + file_extensions
    // are already declared on Frontend. After this commit, every Frontend
    // impl can register in AdapterRegistry directly via the structural
    // coercion, and the compiler enforces the relationship.

    struct MockFrontend;

    impl Frontend for MockFrontend {
        fn language_name(&self) -> &'static str { "mock_frontend" }
        fn file_extensions(&self) -> &[&'static str] { &["mockfe"] }
        fn parse(&self, _source: &str) -> anyhow::Result<Box<dyn std::any::Any>> {
            Ok(Box::new(()))
        }
        fn analyze(&self, _ast: &Box<dyn std::any::Any>) -> anyhow::Result<FeatureReport> {
            let mut r = FeatureReport::default();
            r.lang = "mock_frontend".to_string();
            Ok(r)
        }
        fn lower(&self, _ast: Box<dyn std::any::Any>) -> anyhow::Result<Program> {
            Ok(Program::default())
        }
        // walk inherits the default from Frontend that wraps
        // `frontend_pipeline` (so MockFrontend satisfies LanguageAdapter's
        // `walk` bound via the supertrait tie without explicit body).
    }

    #[test]
    fn frontend_to_adapter_structural_coercion_via_supertrait_tie() {
        let mut registry = AdapterRegistry::new();

        // Compile-time proof: Box<dyn Frontend> coerces to Box<dyn
        // LanguageAdapter>. This is the structural-coercion unlock that
        // CRUSH-36 Commit 2 Sub-Commit 1 introduces.
        let frontend_box: Box<dyn Frontend> = Box::new(MockFrontend);
        let adapter_box: Box<dyn LanguageAdapter> = frontend_box;

        registry.register(adapter_box);
        let langs = registry.languages();
        assert!(
            langs.contains(&"mock_frontend"),
            "MockFrontend must register as a LanguageAdapter via supertrait tie; got: {:?}",
            langs
        );

        // Compile-time check: invoking walk via registry should also work
        // (proves the inherited default walk on Frontend satisfies the
        // LanguageAdapter::walk requirement end-to-end).
        let (report, _program) = registry.walk("unused", "hello.mockfe").unwrap();
        assert_eq!(report.lang, "mock_frontend");
    }
}
