# Generated by export-py from crush-cast Rust types.
# Do not edit manually — re-run `cargo run -p crush-cast --bin export-py`.

from __future__ import annotations

import dataclasses
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple, Union
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal  # type: ignore

JsonValue = Any

@dataclass
class _CastTypeArray:
    Array: CastType

@dataclass
class _CastTypeMap:
    Map: CastType

@dataclass
class _CastTypeStruct:
    Struct: str

@dataclass
class _CastTypeLambda:
    returns: CastType
    params: List[CastType] = field(default_factory=list)

@dataclass
class _CastTypeTypeRef:
    TypeRef: str

CastType = Union[Literal["Int"], Literal["Float"], Literal["String"], Literal["Bool"], Literal["Null"], Literal["Any"], _CastTypeArray, _CastTypeMap, _CastTypeStruct, _CastTypeLambda, _CastTypeTypeRef]

@dataclass
class Program:
    cast_version: str
    entry: str
    lang: Optional[str] = None
    functions: Dict[str, Function] = field(default_factory=dict)
    ai_meta: Optional[AIMetadata] = None

@dataclass
class Function:
    params: List[Tuple[str, CastType]] = field(default_factory=list)
    body: List[Statement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)

@dataclass
class VarDecl:
    name: str
    value: Expression
    type_hint: CastType = "Any"
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["VarDecl"] = "VarDecl"

@dataclass
class Export:
    name: str
    value: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Export"] = "Export"

@dataclass
class ExprStmt:
    expr: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["ExprStmt"] = "ExprStmt"

@dataclass
class If:
    condition: Expression
    then_body: List[Statement] = field(default_factory=list)
    else_body: Optional[List[Statement]] = None
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["If"] = "If"

@dataclass
class While:
    condition: Expression
    body: List[Statement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["While"] = "While"

@dataclass
class For:
    variable: str
    iterable: Expression
    body: List[Statement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["For"] = "For"

@dataclass
class Return:
    value: Optional[Expression] = None
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Return"] = "Return"

@dataclass
class TryCatch:
    error_var: str
    body: List[Statement] = field(default_factory=list)
    handler: List[Statement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["TryCatch"] = "TryCatch"

@dataclass
class Throw:
    value: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Throw"] = "Throw"

@dataclass
class FunctionDef:
    name: str
    params: List[Tuple[str, CastType]] = field(default_factory=list)
    body: List[Statement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["FunctionDef"] = "FunctionDef"

@dataclass
class SetField:
    target: Expression
    field: str
    value: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["SetField"] = "SetField"

@dataclass
class LangBlock:
    lang: str
    code: str
    variables: List[str] = field(default_factory=list)
    imports: List[ImportStatement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["LangBlock"] = "LangBlock"

@dataclass
class Import:
    import_: ImportStatement
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Import"] = "Import"

@dataclass
class StructDef:
    name: str
    fields: List[Tuple[str, CastType]] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["StructDef"] = "StructDef"

@dataclass
class Break:
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Break"] = "Break"

@dataclass
class Continue:
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Continue"] = "Continue"

@dataclass
class DomMutate:
    target: Expression
    mutation_type: DomMutationType
    value: Optional[Expression] = None
    value2: Optional[Expression] = None
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["DomMutate"] = "DomMutate"

@dataclass
class DomEventListener:
    target: Expression
    event: str
    callback: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["DomEventListener"] = "DomEventListener"

@dataclass
class AIStmt:
    ai: AIStatement
    type: Literal["AI"] = "AI"

Statement = Union[VarDecl, Export, ExprStmt, If, While, For, Return, TryCatch, Throw, FunctionDef, SetField, LangBlock, Import, StructDef, Break, Continue, DomMutate, DomEventListener, AIStmt]

@dataclass
class SetTextContent:
    type: Literal["SetTextContent"] = "SetTextContent"

@dataclass
class SetAttribute:
    type: Literal["SetAttribute"] = "SetAttribute"

@dataclass
class RemoveAttribute:
    type: Literal["RemoveAttribute"] = "RemoveAttribute"

@dataclass
class SetStyle:
    type: Literal["SetStyle"] = "SetStyle"

@dataclass
class SetInnerHtml:
    type: Literal["SetInnerHtml"] = "SetInnerHtml"

@dataclass
class AppendHtml:
    type: Literal["AppendHtml"] = "AppendHtml"

@dataclass
class Remove:
    type: Literal["Remove"] = "Remove"

@dataclass
class AddClass:
    type: Literal["AddClass"] = "AddClass"

@dataclass
class RemoveClass:
    type: Literal["RemoveClass"] = "RemoveClass"

DomMutationType = Union[SetTextContent, SetAttribute, RemoveAttribute, SetStyle, SetInnerHtml, AppendHtml, Remove, AddClass, RemoveClass]

@dataclass
class QuerySelector:
    type: Literal["QuerySelector"] = "QuerySelector"

@dataclass
class QuerySelectorAll:
    type: Literal["QuerySelectorAll"] = "QuerySelectorAll"

@dataclass
class GetElementById:
    type: Literal["GetElementById"] = "GetElementById"

@dataclass
class GetElementsByClassName:
    type: Literal["GetElementsByClassName"] = "GetElementsByClassName"

@dataclass
class GetElementsByTagName:
    type: Literal["GetElementsByTagName"] = "GetElementsByTagName"

DomQueryType = Union[QuerySelector, QuerySelectorAll, GetElementById, GetElementsByClassName, GetElementsByTagName]

@dataclass
class IntLiteral:
    value: int
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["IntLiteral"] = "IntLiteral"

@dataclass
class FloatLiteral:
    value: float
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["FloatLiteral"] = "FloatLiteral"

@dataclass
class StringLiteral:
    value: str
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["StringLiteral"] = "StringLiteral"

@dataclass
class BoolLiteral:
    value: bool
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["BoolLiteral"] = "BoolLiteral"

@dataclass
class NullLiteral:
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["NullLiteral"] = "NullLiteral"

@dataclass
class Var:
    name: str
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Var"] = "Var"

@dataclass
class BinaryOp:
    operator: str
    left: Expression
    right: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["BinaryOp"] = "BinaryOp"

@dataclass
class UnaryOp:
    operator: str
    operand: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["UnaryOp"] = "UnaryOp"

@dataclass
class Call:
    function: str
    args: List[Expression] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Call"] = "Call"

@dataclass
class CapabilityCall:
    name: str
    args: List[Expression] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["CapabilityCall"] = "CapabilityCall"

@dataclass
class Pipeline:
    segments: List[Expression] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Pipeline"] = "Pipeline"

@dataclass
class Spawn:
    function: str
    args: List[Expression] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Spawn"] = "Spawn"

@dataclass
class Lambda:
    params: List[Tuple[str, CastType]] = field(default_factory=list)
    body: List[Statement] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Lambda"] = "Lambda"

@dataclass
class Yield:
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Yield"] = "Yield"

@dataclass
class NewStruct:
    name: str
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["NewStruct"] = "NewStruct"

@dataclass
class GetField:
    target: Expression
    field: str
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["GetField"] = "GetField"

@dataclass
class Range:
    start: Expression
    end: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Range"] = "Range"

@dataclass
class Await:
    expression: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Await"] = "Await"

@dataclass
class ArrayLiteral:
    elements: List[Expression] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["ArrayLiteral"] = "ArrayLiteral"

@dataclass
class ObjectLiteral:
    properties: List[Tuple[str, Expression]] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["ObjectLiteral"] = "ObjectLiteral"

@dataclass
class Index:
    target: Expression
    index: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Index"] = "Index"

@dataclass
class DomQuery:
    query_type: DomQueryType
    selector: Expression
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["DomQuery"] = "DomQuery"

@dataclass
class Match:
    expression: Expression
    arms: List[MatchArm] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)
    type: Literal["Match"] = "Match"

@dataclass
class AIExpr:
    ai: AIExpression
    type: Literal["AI"] = "AI"

Expression = Union[IntLiteral, FloatLiteral, StringLiteral, BoolLiteral, NullLiteral, Var, BinaryOp, UnaryOp, Call, CapabilityCall, Pipeline, Spawn, Lambda, Yield, NewStruct, GetField, Range, Await, ArrayLiteral, ObjectLiteral, Index, DomQuery, Match, AIExpr]

@dataclass
class MatchArm:
    pattern: Pattern
    body: List[Statement] = field(default_factory=list)

@dataclass
class LiteralPattern:
    value: Expression
    type: Literal["Literal"] = "Literal"

@dataclass
class IdentifierPattern:
    name: str
    type: Literal["Identifier"] = "Identifier"

@dataclass
class StructPattern:
    name: str
    fields: List[Tuple[str, Pattern]] = field(default_factory=list)
    type: Literal["Struct"] = "Struct"

@dataclass
class WildcardPattern:
    type: Literal["Wildcard"] = "Wildcard"

Pattern = Union[LiteralPattern, IdentifierPattern, StructPattern, WildcardPattern]

@dataclass
class CrushModule:
    module_path: str
    alias: Optional[str] = None
    selective: List[str] = field(default_factory=list)
    type: Literal["CrushModule"] = "CrushModule"

@dataclass
class PolyglotModule:
    language: str
    module_path: str
    alias: Optional[str] = None
    selective: List[str] = field(default_factory=list)
    type: Literal["PolyglotModule"] = "PolyglotModule"

@dataclass
class MCPImport:
    server_url: str
    tools: List[str] = field(default_factory=list)
    alias: Optional[str] = None
    type: Literal["MCPImport"] = "MCPImport"

@dataclass
class CapabilityImport:
    capability_path: str
    permissions: List[str] = field(default_factory=list)
    alias: Optional[str] = None
    type: Literal["Capability"] = "Capability"

@dataclass
class ExternalImport:
    uri: str
    resource_type: ExternalResourceType
    alias: Optional[str] = None
    type: Literal["External"] = "External"

@dataclass
class SecureEnvImport:
    keys: List[str] = field(default_factory=list)
    alias: Optional[str] = None
    db_path: Optional[str] = None
    type: Literal["SecureEnv"] = "SecureEnv"

ImportStatement = Union[CrushModule, PolyglotModule, MCPImport, CapabilityImport, ExternalImport, SecureEnvImport]

@dataclass
class _ExternalResourceTypeAPI:
    format: str

ExternalResourceType = Union[Literal["Http"], Literal["Git"], Literal["File"], Literal["Database"], _ExternalResourceTypeAPI]

@dataclass
class Query:
    query: str
    result_type: Optional[str] = None
    context: Dict[str, Any] = field(default_factory=dict)
    ai_type: Literal["Query"] = "Query"

@dataclass
class ToolChain:
    strategy: ExecutionStrategy
    error_handling: ErrorHandling
    tools: List[ToolCall] = field(default_factory=list)
    ai_type: Literal["ToolChain"] = "ToolChain"

@dataclass
class AgentDelegation:
    task: str
    delegation_strategy: DelegationStrategy
    agents: List[str] = field(default_factory=list)
    expected_format: Optional[str] = None
    ai_type: Literal["AgentDelegation"] = "AgentDelegation"

@dataclass
class LearningLoop:
    learning_target: LearningTarget
    strategy: LearningStrategy
    adaptations: List[AdaptationAction] = field(default_factory=list)
    ai_type: Literal["LearningLoop"] = "LearningLoop"

@dataclass
class ContextAware:
    expression: Expression
    requires_context: List[str] = field(default_factory=list)
    provides_context: List[str] = field(default_factory=list)
    ai_type: Literal["ContextAware"] = "ContextAware"

@dataclass
class SemanticMatch:
    target: Expression
    concept: str
    confidence_threshold: float
    ai_type: Literal["SemanticMatch"] = "SemanticMatch"

@dataclass
class Synthesize:
    output_type: CastType
    constraints: List[str] = field(default_factory=list)
    context_refs: List[Expression] = field(default_factory=list)
    examples: Optional[List[Expression]] = None
    ai_type: Literal["Synthesize"] = "Synthesize"

AIExpression = Union[Query, ToolChain, AgentDelegation, LearningLoop, ContextAware, SemanticMatch, Synthesize]

@dataclass
class GoalDeclaration:
    goal_id: str
    description: str
    priority: Priority
    success_criteria: List[str] = field(default_factory=list)
    deadline: Optional[str] = None
    ai_type: Literal["GoalDeclaration"] = "GoalDeclaration"

@dataclass
class ProgressUpdate:
    goal_id: str
    progress: float
    status_message: str
    metrics: Dict[str, float] = field(default_factory=dict)
    ai_type: Literal["ProgressUpdate"] = "ProgressUpdate"

@dataclass
class KnowledgeSharing:
    knowledge_type: KnowledgeType
    content: Any
    retention_policy: RetentionPolicy
    recipients: List[str] = field(default_factory=list)
    ai_type: Literal["KnowledgeSharing"] = "KnowledgeSharing"

@dataclass
class CapabilityDiscovery:
    domain: str
    discovery_strategy: DiscoveryStrategy
    requirements: List[str] = field(default_factory=list)
    ai_type: Literal["CapabilityDiscovery"] = "CapabilityDiscovery"

@dataclass
class AdaptationRequest:
    adaptation_type: AdaptationType
    reason: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    ai_type: Literal["AdaptationRequest"] = "AdaptationRequest"

@dataclass
class SemanticSwitch:
    target: Expression
    cases: List[Tuple[str, List[Statement]]] = field(default_factory=list)
    fallback: Optional[List[Statement]] = None
    ai_type: Literal["SemanticSwitch"] = "SemanticSwitch"

AIStatement = Union[GoalDeclaration, ProgressUpdate, KnowledgeSharing, CapabilityDiscovery, AdaptationRequest, SemanticSwitch]

@dataclass
class AIMetadata:
    description: str
    execution_context: ExecutionContext
    ai_tags: List[str] = field(default_factory=list)
    required_capabilities: List[str] = field(default_factory=list)
    learning_objectives: List[str] = field(default_factory=list)
    collaboration_patterns: List[CollaborationPattern] = field(default_factory=list)
    inputs: List[ParameterSchema] = field(default_factory=list)
    outputs: List[ParameterSchema] = field(default_factory=list)
    complexity: int = 0

@dataclass
class ToolCall:
    tool_name: str
    parameters: Dict[str, Any] = field(default_factory=dict)
    result_binding: Optional[str] = None
    condition: Optional[str] = None

@dataclass
class Sequential:
    type: Literal["Sequential"] = "Sequential"

@dataclass
class Parallel:
    type: Literal["Parallel"] = "Parallel"

@dataclass
class Conditional:
    conditions: List[str] = field(default_factory=list)
    type: Literal["Conditional"] = "Conditional"

@dataclass
class RetryStrategy:
    max_attempts: int
    backoff_strategy: BackoffStrategy
    type: Literal["Retry"] = "Retry"

ExecutionStrategy = Union[Sequential, Parallel, Conditional, RetryStrategy]

@dataclass
class FailFast:
    type: Literal["FailFast"] = "FailFast"

@dataclass
class ContinueOnError:
    type: Literal["ContinueOnError"] = "ContinueOnError"

@dataclass
class RetryError:
    max_retries: int
    retry_condition: Optional[str] = None
    type: Literal["Retry"] = "Retry"

@dataclass
class Fallback:
    fallback_tools: List[ToolCall] = field(default_factory=list)
    type: Literal["Fallback"] = "Fallback"

ErrorHandling = Union[FailFast, ContinueOnError, RetryError, Fallback]

@dataclass
class FixedBackoff:
    delay_ms: int
    type: Literal["Fixed"] = "Fixed"

@dataclass
class ExponentialBackoff:
    base_delay_ms: int
    max_delay_ms: int
    type: Literal["Exponential"] = "Exponential"

@dataclass
class LinearBackoff:
    increment_ms: int
    type: Literal["Linear"] = "Linear"

BackoffStrategy = Union[FixedBackoff, ExponentialBackoff, LinearBackoff]

@dataclass
class _DelegationStrategyConsensus:
    threshold: float

DelegationStrategy = Union[Literal["FirstAvailable"], Literal["CapabilityMatch"], Literal["ParallelSplit"], Literal["Hierarchical"], _DelegationStrategyConsensus, Literal["Broadcast"], Literal["Best"], Literal["RoundRobin"]]

Priority = Literal["Low", "Medium", "High", "Critical"]

KnowledgeType = Literal["Pattern", "Solution", "BestPractice", "Warning", "Insight"]

@dataclass
class _RetentionPolicyConditional:
    condition: str

RetentionPolicy = Union[Literal["Ephemeral"], Literal["Session"], Literal["Persistent"], _RetentionPolicyConditional]

DiscoveryStrategy = Literal["Broadcast", "Targeted", "Hierarchical", "LearningBased"]

AdaptationType = Literal["Performance", "Reliability", "Usability", "Compatibility", "Learning"]

LearningTarget = Literal["UserBehavior", "ExecutionPatterns", "ErrorPatterns", "PerformanceMetrics", "ToolUsage"]

LearningStrategy = Literal["PatternRecognition", "StatisticalAnalysis", "MachineLearning", "RuleBased"]

AdaptationAction = Literal["OptimizeToolChain", "ImproveErrorHandling", "UpdateAgentSelection", "ModifyExecutionStrategy", "LearnNewPatterns"]

@dataclass
class ParameterSchema:
    name: str
    description: str
    type_hint: str
    required: bool = True
    default_value: Optional[Any] = None

@dataclass
class ToolSchema:
    name: str
    description: str
    return_type: str
    parameters: Dict[str, ParameterSchema] = field(default_factory=dict)
    mcp_server: Optional[str] = None
    mcp_method: Optional[str] = None

@dataclass
class _LearningSourcePeerAgents:
    agent_ids: List[str] = field(default_factory=list)

LearningSource = Union[Literal["ExecutionResults"], Literal["UserFeedback"], Literal["EnvironmentObservations"], _LearningSourcePeerAgents]

AdaptationStrategy = Literal["PerformanceOptimization", "Personalization", "CapabilityExpansion", "CollaborationEnhancement"]

@dataclass
class ExecutionContext:
    environment: List[str] = field(default_factory=list)
    resources: List[str] = field(default_factory=list)
    permissions: List[str] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)

@dataclass
class CollaborationPattern:
    pattern_type: str
    communication_style: str
    decision_making: str
    participants: List[str] = field(default_factory=list)

